- examples/module/websocket-demo.we
- ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.m
- ios/sdk/WeexSDK/Sources/Module/WXWebSocketModule.m
- websocket module crash when reason is nil in specific environment 
- update websocket demo
- loadmore should be actived in up derection
> + [ios] fix websocket module crash when reason is nil in specific environment 

- ios/sdk/WeexSDK/Sources/Utility/WXConvert.m
because rax transform number to native,the text weight will lose effect when textweight   is number. change logic to make textweight  effect in rax
> + [ios] because rax transform number to native,the text weight will lose effect

- android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
reset list cell count when js call list component method resetLoadmore , or can not trigger loadmore event again
> * [android] reset list cell count when resetLoadmore

- doc/source/cn/faq.md
- doc/source/cn/references/common-style.md
- doc/source/cn/references/components/scroller.md
- doc/source/faq.md
- doc/source/references/common-style.md
- doc/source/references/components/scroller.md
* Android now supports emoji.
* Android now supports 1px border.
* Add document for the behavior of border-radius clipping, which is really confusing.
> Fix doc for android problem.

- ios/sdk/WeexSDK.xcodeproj/project.pbxproj
- ios/sdk/WeexSDK/Sources/Bridge/WXBridgeMethod.m
- ios/sdk/WeexSDK/Sources/Component/WXEditComponent.h
- ios/sdk/WeexSDK/Sources/Component/WXTextInputComponent.h
- ios/sdk/WeexSDK/Sources/Utility/WXConvert.h
- ios/sdk/WeexSDK/Sources/Utility/WXConvert.m
fix compile bug about wxeditcomponent
> + [ios] fix compile bug about wxeditcomponent

- ios/sdk/WeexSDK/Sources/Component/WXSliderNeighborComponent.m
* [ios] fix bug:The calculation of neighbor-space does not take into account the current item scaling.
> * [ios] fix bug:The calculation of neighbor-space does not take into account the current item scaling.

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
add updateStyle and updateAttrs API
> * [android] add updateStyle and updateAttrs API

- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
- android/sdk/src/main/java/com/taobao/weex/WXSDKManager.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXValidateProcessor.java
- android/sdk/src/main/java/com/taobao/weex/dom/WXDomObject.java
- ios/sdk/WeexSDK.xcodeproj/project.pbxproj
- ios/sdk/WeexSDK/Sources/Bridge/WXModuleMethod.m
- ios/sdk/WeexSDK/Sources/Manager/WXComponentManager.m
- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.h
- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
- ios/sdk/WeexSDK/Sources/Protocol/WXValidateProtocol.h
> Feature validate support

- ios/sdk/WeexSDKTests/WXStorageTests.m
> modify unit test

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXScroller.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
> Fix scroller loadmoreoffset

- android/sdk/src/main/java/com/taobao/weex/utils/WXSoInstallMgrSdk.java
> * [android] add so checkSoIsValid

- examples/vue/components/waterfall.vue
- ios/sdk/WeexSDK/Sources/Component/Recycler/WXRecyclerComponent.m
- ios/sdk/WeexSDK/Sources/Component/Recycler/WXRecyclerUpdateController.h
- ios/sdk/WeexSDK/Sources/Component/Recycler/WXRecyclerUpdateController.m
- ios/sdk/WeexSDK/Sources/Component/WXListComponent.m
* [ios] support loadmore event in recycler
* [ios] remove unused exception handler
> * [ios] support loadmore event in recycler

- android/sdk/src/main/java/com/taobao/weex/common/WXThread.java
Ignore the Runnable send from system
> * [android] ignore system action on WXThread.secure()

- android/sdk/build.gradle
- android/sdk/src/main/java/com/taobao/weex/utils/WXSoInstallMgrSdk.java
1. add gradle script task to get so size & fix JSFVersionGet bug
> * [android] add gradle script  task to get so size

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXVContainer.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
1. bugFix for fixed component recycle attribute
> 0.11 dev support update recycler

- android/sdk/src/main/java/com/taobao/weex/ui/animation/WXAnimationModule.java
> Fix android animation npe

- ios/sdk/WeexSDK/Sources/Bridge/WXJSCoreBridge.m
- ios/sdk/WeexSDK/Sources/Component/Recycler/WXRecyclerComponent.m
- ios/sdk/WeexSDK/Sources/Component/WXListComponent.m
If cell movings are frequent(like list sorting)， doing them one by one is slow , we need a mechanism to batch them.
> * [ios] Add reload interval to list to batch move updates

- android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/ListComponentView.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/SimpleRecyclerView.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/refresh/wrapper/BounceRecyclerView.java
support keepScrollPosition
@sospartan
> 0.11 dev insert keep position

- doc/source/cn/references/components/cell.md
- doc/source/references/components/cell.md
> * [doc] update cell doc

- examples/module/websocket-demo.we
- ios/playground/WeexDemo.xcodeproj/xcshareddata/xcschemes/WeexDemo.xcscheme
- ios/sdk/WeexSDK/Sources/Display/WXComponent+BoxShadow.h
- ios/sdk/WeexSDK/Sources/Display/WXComponent+BoxShadow.m
- ios/sdk/WeexSDK/Sources/Events/WXComponent+Events.m
- ios/sdk/WeexSDK/Sources/Layout/WXComponent+Layout.m
- ios/sdk/WeexSDK/Sources/Model/WXComponent.m
- ios/sdk/WeexSDK/Sources/View/WXComponent+ViewManagement.m
- package.json
- To support the follow case: use  box-shadow and  pseudo-class,update box-shadow logic to fix bug
- demo:http://dotwe.org/vue/bda48e3c453f1eb6f28732c5063f3bbf
-  rax in follow case will re-render , so save flag to recovery
- demo
```html
import {createElement, Component, render} from 'rax';
import {Text} from 'rax-components';
class App extends Component {
constructor(props){
super(props);
this.state = {
test: '1'
}
}
press(){
this.setState({
test: this.state.test === '1' ?'2':'1'
})
}
render() { 
return (
<Text style={Styles.item} onPress={this.press.bind(this)}>233{this.state.test}</Text>
);
}
}
const Styles = {
item:{
backgroundColor:'red',
'backgroundColor:active':'blue'
}
}
render(<App />);
```
> + [ios] fix bug box-shadow

- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
Fix fail process when re-register component/module/service, when possible cause ConcurrentModificationException.
@zshshr @littleseven
> [android] fix ConcurrentModificationException in registeration.

- android/sdk/src/main/java/com/taobao/weex/ui/module/WXMetaModule.java
- android/sdk/src/main/java/com/taobao/weex/utils/WXViewUtils.java
1. Set DensityDpi  to Viewport to  deal with “dp” unit, when viewport width is equal  "device-width"
> * [android] Set DensityDpi  to Viewport to  deal with “dp” unit

- ios/sdk/WeexSDK/Sources/Module/WXStreamModule.m
- ios/sdk/WeexSDK/Sources/Network/WXResourceRequestHandlerDefaultImpl.m
fix stream failed callback failed
fix call failed request with error when failed
refactor stream module
> * [ios] refactor stream 

- Dangerfile
- Dangerfile-ios
- android/sdk/src/test/java/com/taobao/weex/TestActivity.java
- test/ci-funcs.sh
Danger script will find any modification match pattern `/^-\s*?public\s+[\s\S]+$/ `, java file only.
> Use danger to find potential break change

- ios/sdk/WeexSDK/Sources/Component/WXImageComponent.m
* Update Image to WXImageComponent when filter:blur changed
> bugfix:updateImage when blur radius changed

- ios/sdk/WeexSDK/Sources/Bridge/WXJSCoreBridge.m
- ios/sdk/WeexSDK/Sources/Engine/WXSDKEngine.m
fix default handler override
remove dlsym for jscore garbage Collection
> * [ios] 0.10.2 bugfix

- android/sdk/src/main/java/com/taobao/weex/common/Constants.java
- android/sdk/src/main/java/com/taobao/weex/ui/module/WXMetaModule.java
- android/sdk/src/main/java/com/taobao/weex/utils/WXViewUtils.java
> * [android] bug fix viewport

- doc/source/cn/guide/integrate-to-your-app.md
- doc/source/cn/guide/intro/app-architecture.md
- doc/source/cn/guide/intro/how-it-works.md
- doc/source/cn/guide/intro/index.md
- doc/source/cn/guide/intro/page-architecture.md
- doc/source/cn/guide/intro/using-vue.md
- doc/source/cn/guide/intro/web-dev-experience.md
- doc/source/cn/guide/intro/write-once.md
- doc/source/cn/guide/set-up-env.md
- doc/source/cn/guide/tools/devtools.md
- doc/source/cn/guide/tools/index.md
- doc/source/cn/guide/tools/weexpack.md
- doc/source/guide/integrate-to-your-app.md
- doc/source/guide/set-up-env.md
- doc/themes/weex/languages/cn.yml
- doc/themes/weex/languages/en.yml
- doc/themes/weex/layout/_partial/header.ejs
- doc/themes/weex/layout/_partial/sidebar.ejs
* Re-ordered the guide content: `set-up-env` and `integrate-to-your-app` in `get started`, `intro` up, `tools` down.
* Updated header menu and link more tools internal.
> [website] improved the menu

- android/sdk/src/main/java/com/taobao/weex/dom/WXStyle.java
1. `enable` is treat as regular style, but was not put into regular style map.
2. Rename style map field name.
> [android] Fix 'enable' pesudo class does not working.

- doc/source/cn/faq.md
- doc/source/cn/guide/integrate-to-your-app.md
- doc/source/cn/references/modules/storage.md
- doc/source/cn/references/modules/websocket.md
- doc/source/cn/v-0.10/advanced/extend-to-html5.md
- doc/source/cn/v-0.10/advanced/integrate-to-android.md
- doc/source/cn/v-0.10/references/modules/storage.md
- doc/source/cn/v-0.10/tools/devtools.md
- doc/source/faq.md
- doc/source/references/modules/websocket.md
- doc/source/v-0.10/advanced/extend-to-html5.md
- doc/source/v-0.10/advanced/integrate-to-android.md
- doc/source/v-0.10/guide/how-to/preview-in-playground-app.md
- doc/themes/weex/layout/_partial/header.ejs
- doc/themes/weex/layout/_partial/sidebar.ejs
- doc/themes/weex/layout/_partial/slider.ejs
* [doc] Update GitHub link, change from alibaba/weex to apache/weex.
> * [doc] Update GitHub link, change from alibaba/weex to apache/weex.

- doc/themes/weex/languages/en.yml
> Fix some grammatical issues on the English webpage

- doc/source/cn/references/components/a.md
- doc/source/cn/references/components/div.md
- doc/source/cn/references/components/image.md
- doc/source/cn/references/components/indicator.md
- doc/source/cn/references/components/list.md
- doc/source/cn/references/modules/globalevent.md
- doc/source/cn/references/path.md
- doc/source/cn/v-0.10/references/modules/globalevent.md
- doc/source/references/components/image.md
- doc/source/references/modules/globalevent.md
- doc/source/v-0.10/references/modules/globalevent.md
> * [doc] Update some examples.

- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
- android/sdk/src/main/java/com/taobao/weex/WXSDKManager.java
- android/sdk/src/main/java/com/taobao/weex/dom/WXDomModule.java
- android/sdk/src/main/java/com/taobao/weex/dom/WXDomObject.java
- android/sdk/src/main/java/com/taobao/weex/dom/WXDomStatement.java
- android/sdk/src/main/java/com/taobao/weex/ui/WXRenderStatement.java
- android/sdk/src/main/java/com/taobao/weex/ui/animation/WXAnimationModule.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/AbstractEditComponent.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXEmbed.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXIndicator.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXSliderNeighbor.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
- android/sdk/src/main/java/com/taobao/weex/ui/module/WXMetaModule.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/gesture/WXGesture.java
- android/sdk/src/test/java/com/taobao/weex/ui/module/WXMetaModuleTest.java
> * [android] support set individual instance viewport

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/border/BorderDrawable.java
> * [android] update modify linear-gradline default value

- android/playground/app/src/main/java/com/alibaba/weex/WXPageActivity.java
- android/playground/app/src/main/java/com/alibaba/weex/extend/module/location/DefaultLocation.java
@sospartan modify playground null pointer
> * [android] update modify nullpoint

- doc/_config.yml
- doc/themes/weex/layout/_partial/after-footer.ejs
Update cnzz id, cnzz is an analysis tool.
> * [doc] Update cnzz id.

- examples/vue/components/waterfall.vue
- ios/sdk/WeexSDK/Sources/Component/Recycler/WXMultiColumnLayout.m
- ios/sdk/WeexSDK/Sources/Component/Recycler/WXRecyclerComponent.m
* fix issue that header at bottom not work
* add footer support to waterfall example
> * [ios] fix issue that header at bottom not work

- doc/themes/weex/layout/_partial/header.ejs
- doc/themes/weex/layout/_partial/sidebar.ejs
> * [site] Update market link.

- ios/sdk/WeexSDK/Sources/Component/WXComponent+GradientColor.m
- ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.m
- ios/sdk/WeexSDK/Sources/Layout/WXComponent+Layout.m
- ios/sdk/WeexSDK/Sources/Module/WXAnimationModule.m
1.  fix pulling down event fire time
2. fix animation about bounds
3. bug fix backgroundImage about gradientColor
> 0.11 dev bugfixs

- android/sdk/src/main/java/com/taobao/weex/dom/DOMActionContextImpl.java
- android/sdk/src/main/java/com/taobao/weex/dom/RenderAction.java
- android/sdk/src/main/java/com/taobao/weex/dom/WXDomModule.java
- android/sdk/src/main/java/com/taobao/weex/dom/action/Action.java
- android/sdk/src/main/java/com/taobao/weex/dom/action/Actions.java
- android/sdk/src/main/java/com/taobao/weex/dom/action/GetComponentRectAction.java
- android/sdk/src/main/java/com/taobao/weex/ui/WXRenderManager.java
the 'action' part is not release yet, so modify these public method would not make more 'break change'.
@xkli @YorkShen
> [android] post render-only action direct to UI thread.

- ios/sdk/WeexSDK/Sources/Component/WXSliderComponent.m
> * [ios] bug fix slider can not scroll to special area.

- CHANGELOG.md
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/ListComponentView.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/SimpleRecyclerView.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/StickyHeaderHelper.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/refresh/wrapper/BounceRecyclerView.java
Use list instead of stack to store sticky components and views.
In list, use #updateSticyView(currentStickyPos) to find the current sticky component.
>  [android] refactor list sticky implementation

- ios/sdk/WeexSDK.xcodeproj/project.pbxproj
> + [ios] remove WXVlidateProtocol.h to Public

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXHeader.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXLoading.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXRefresh.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
1. some special component set no recycle
> * [android] some special component set no recycle

- ios/sdk/WeexSDK/Sources/Component/Recycler/WXRecyclerComponent.m
- ios/sdk/WeexSDK/Sources/Component/WXRefreshComponent.m
try  case :   http://dotwe.org/weex/cf4f637a1de1a9ca6d0385553ac4b623
> * [ios] fix contentOffset reset

- android/sdk/src/main/java/com/taobao/weex/ui/component/NestedContainer.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXEmbed.java
WXEmbed add reload interface when embed need reload
> + [android] embed reload

- ios/sdk/WeexSDK/Sources/Bridge/WXBridgeMethod.h
- ios/sdk/WeexSDK/Sources/Bridge/WXBridgeMethod.m
+ [ios] support mutable arguments
> + [ios] support mutable arguments

- ios/sdk/WeexSDK/Sources/Component/WXEditComponent.m
- input and textarea add number type
- when keyboard show or hide will fire event
> + [ios] add keyboard shown event

- android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
> 0.11 dev bugfix header

- ios/sdk/WeexSDK/Sources/Display/WXComponent+BoxShadow.m
- ios/sdk/WeexSDK/Sources/Utility/WXBoxShadow.m
+ [ios] bug fix: try to repair  boxshadow crash in setshadowcolor
refer to :https://github.com/gnustep/quartzcore/blob/master/Source/CALayer.m
> + [ios] bug fix: try to repair  boxshadow crash in setshadowcolor

- examples/component/list/list-basic.we
- examples/module/chatroom-demo.we
- examples/module/websocket-demo.we
- examples/vue/components/input.vue
- examples/vue/components/list.vue
- examples/vue/index.vue
- examples/vue/showcase/boxshadow.vue
+ [example] add showcase input box shadow chatroom
> + [example] add showcase input box shadow chatroom

- examples/component/input-demo.we
- examples/include/example-list-item.we
- examples/index.we
- examples/showcase/boxshadow.we
+ [example] update index, list add box shadow demo
> + [example] update index, list add box shadow demo

- examples/linear-gradient.we
- ios/sdk/WeexSDK/Sources/Component/WXComponent+GradientColor.m
try case: http://dotwe.org/vue/107df922e7c0b882ef1085085e4c956a
> *[ios] 0.12 support alpha gradient

- README.md
- ios/sdk/WeexSDK/Sources/Bridge/WXJSCoreBridge.m
- ios/sdk/WeexSDK/Sources/Manager/WXComponentManager.m
> 【iOS】If setFrame(0, 0, width, 0), sometime it will not adjust the height with content

- ios/sdk/WeexSDK/Sources/Display/WXComponent+BoxShadow.h
- ios/sdk/WeexSDK/Sources/Display/WXComponent+BoxShadow.m
- ios/sdk/WeexSDK/Sources/Display/WXInnerLayer.h
- ios/sdk/WeexSDK/Sources/Display/WXInnerLayer.m
- ios/sdk/WeexSDK/Sources/Layout/WXComponent+Layout.m
- ios/sdk/WeexSDK/Sources/Utility/WXBoxShadow.h
- ios/sdk/WeexSDK/Sources/Utility/WXBoxShadow.m
+ [ios] boxshadow shadowcolor change to color
> + [ios] boxshadow shadowcolor change to color

- build/config.js
- build/karma.vue.conf.js
- package.json
> [html5] fix flow plugin in build config.

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXImage.java
> * [android] update imageView

- package.json
> * [jsfm] update rax framework to latest

- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
See more:  https://issues.apache.org/jira/browse/WEEX-20
> * [android] fix setSize when defaultHeight is use screen height

- doc/package.json
- doc/source/cn/releasenote.md
- doc/source/releasenote.md
- doc/themes/weex/languages/cn.yml
- doc/themes/weex/languages/en.yml
- doc/themes/weex/layout/_partial/header.ejs
- doc/themes/weex/source/css/partial/article.scss
> * [doc] update release note

- html5/frameworks/legacy/app/ctrl/init.js
call  C++ timer instead of  WxTimerModule with in weex jsfm to improve settimeout/setinterval performance.
>  call  C++ timer instead of  WxTimerModule with in weex jsfm

- package.json
> * [jsfm] v0.20.3

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXSlider.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/WXCircleViewPager.java
- test/pages/slider-infinite.we
- test/scripts/components/slider-infinite.test.js
Changes:
- allows auto play when the number of items is 2
- allows infinite scroll when the number of items items is 2
- ability to disable infinite scroll
Testcase:
- http://dotwe.org/weex/f7e8b0cb0e0a2bfe613011b28d8c0276
Known issue:
- When the number of items is 2,  the loop scroll from item 2 to item 1 will have no animation effect
> * [android] slider improvement

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/gesture/WXGesture.java
Disable click event when gesture is consumed same serial touch-event.
> [android] disable click event when gesture already consume touch event

- ios/sdk/WeexSDK/Sources/Protocol/WXBridgeProtocol.h
> * [ios] fix bug ci

- android/sdk/src/main/java/com/taobao/weex/WXSDKEngine.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXBasicComponentType.java
add alias `cycleslider` to slider component unified with iOS
> * [android] add alias for slider component

- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
- android/sdk/src/main/java/com/taobao/weex/appfram/navigator/WXNavigatorModule.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXEmbed.java
> 0.11 dev bugfix

- ios/sdk/WeexSDK/Sources/Engine/WXSDKEngine.m
[more details](https://github.com/alibaba/weex/issues/2911)
> * [ios] fix commit wrongly

- ios/playground/WeexDemo.xcodeproj/project.pbxproj
Open use  the default system application to open the file, maybe user has  changed  to a different application, then  start sample will fail.
> [ios]Explicit start samples by terminal.

- doc/source/cn/references/modules/modal.md
- doc/source/references/modules/modal.md
Change doc of toast to what the reality is.
> * [doc] Change doc of toast.

- ios/sdk/WeexSDK/Sources/Module/WXPickerModule.m
* fixbug text color is not right
* fixbug  default seletion have no backgroundcolor
> + [ios] fix bug picker

- html5/frameworks/legacy/app/ctrl/init.js
- package.json
revert commit call C++ timer instead of WxTimerModule with in weex jsfm
> * [jsfm] v0.20.4

- test/pages/components/text-layout.vue
- test/scripts/components/text.test.js
The test case mainly focus on the layout of text.
> * [test] add Macaca test case for text

- ios/playground/Podfile
- ios/sdk/WeexSDK/Sources/Loader/WXResourceLoader.m
- ios/sdk/WeexSDK/Sources/Network/WXResourceRequestHandler.h
- ios/sdk/WeexSDK/Sources/Network/WXResourceRequestHandlerDefaultImpl.m
> + [ios] support timeline

- ios/playground/Podfile
> + [ios] update  podfile

- android/sdk/src/main/java/com/taobao/weex/dom/TextDecorationSpan.java
- android/sdk/src/main/java/com/taobao/weex/dom/WXStyle.java
- android/sdk/src/main/java/com/taobao/weex/dom/WXTextDomObject.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXTextDecoration.java
This is just an optimization, the behavior of the .js code would not be affected.
> + [android] Use TextDecorationSpan to implement "text-decoraion"

- ios/sdk/WeexSDK/Sources/Manager/WXComponentManager.m
because Android Support DP, so iOS need support too。
> 【iOS】 Make Weex Support DP

- NOTICE
This is mainly to test the change in the notification system.
> Added Apache notice in NOTICE file

- ios/sdk/WeexSDK/Sources/Component/WXImageComponent.m
+ [ios] fix bug: image load maybe send wrong imagesize
> + [ios] fix bug: image load maybe send wrong imagesize

- ios/playground/WeexDemo/Scanner/WXScannerHistoryVC.m
fix scan history tap gesture conflict
> * [ios] fix scan history tap gesture conflict

- ios/sdk/WeexSDK/Sources/Model/WXComponent.m
+ [ios] fix bug: active not work when update
> + [ios] fix bug: active not work when update

- test/pages/modules/vue_timer.vue
- test/pages/modules/we_timer.we
- test/scripts/components/text.test.js
- test/scripts/modules/timer.test.js
> Test timer

- android/sdk/src/test/java/com/taobao/weex/utils/WXUtilsTest.java
> [android] fix wx unit test

- ios/sdk/WeexSDK/Sources/Bridge/WXJSCoreBridge.m
- ios/sdk/WeexSDK/Sources/Component/WXListComponent.m
+ [ios] add timer method clearIntervalWeex clearTimeoutWeex
> + [ios] add timer method

- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
+ [ios] add slider switch function
> + [ios] add slider switch function

- examples/vue/market/gcanvas.vue
+ [example] fix bug: gcanvas demo bug
> + [example] fix bug: gcanvas demo bug

- ios/sdk/WeexSDK/Sources/Component/WXListComponent.m
ios add list component sticky/unSticky event
example: http://dotwe.org/vue/a6a28eca4ca9b92764104fa18e0b9863
> Ios feature add list sticky event 0.13

- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
+ [ios] update slider config logic
> + [ios] update slider config logic

- ios/sdk/WeexSDK/Sources/Bridge/WXModuleMethod.m
> * [ios] Add Module invoke monitor

- android/sdk/src/main/java/com/taobao/weex/dom/WXSwitchDomObject.java
See http://dotwe.org/vue/06b1d740fb69d04f9ebe9eaf730974d1
> * [android] Fix switchDom issue

- ios/sdk/WeexSDK/Sources/Component/WXCycleSliderComponent.m
+ [ios] iOS slider mod bug fix
> + [ios] iOS slider mod bug fix

- ios/sdk/WeexSDK/Sources/Component/WXListComponent.m
bug fix listcomponent for index beyond
> * [ios] bug fix listcomponent for index beyond

- doc/source/cn/references/modules/websocket.md
- doc/source/references/modules/websocket.md
+ [doc] feature: update websocket doc
> + [doc] feature: update websocket doc

- android/sdk/src/main/java/com/taobao/weex/adapter/IWXUserTrackAdapter.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXModuleManager.java
> add module monitor info

- ios/sdk/WeexSDK/Sources/Component/WXIndicatorComponent.m
+ [ios] fix bug:IndicatorView will hide when show again
> + [ios] fix bug:IndicatorView will hide when show again

- android/sdk/src/main/java/com/taobao/weex/adapter/IDrawableLoader.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/border/BorderDrawable.java
- android/sdk/src/main/java/com/taobao/weex/utils/WXViewUtils.java
Remove magic numbers from WXViewUtils and use the power of API 24.
1. Use IntDef Annotation to imply return value.
2. Use Version_CODES.N to replace 24.
> * [android] Use the power of API 24

- ios/sdk/WeexSDK/Sources/Loader/WXResourceLoader.m
- ios/sdk/WeexSDK/Sources/Module/WXPrerenderManager.m
- ios/sdk/WeexSDK/Sources/Network/WXResourceRequestHandler.h
- ios/sdk/WeexSDK/Sources/Network/WXResourceRequestHandlerDefaultImpl.m
> + [ios] bug fix compile error

- ios/sdk/WeexSDK/Sources/View/WXComponent+PseudoClassManagement.m
> + [ios] update pseudo class

- ios/playground/WeexDemo/WXDemoViewController.m
- ios/sdk/WeexSDK/Sources/Controller/WXBaseViewController.m
- ios/sdk/WeexSDK/Sources/Module/WXPrerenderManager.h
- ios/sdk/WeexSDK/Sources/Module/WXPrerenderManager.m
+ [ios] update pretender logic
> + [ios] update prerender logic

- package.json
changes in rax framework：
1.  [add userAgent in navigator](https://github.com/alibaba/rax/commit/728337665d26108aa6d77ce4baf46274320cacff)
2.  [cache bundle init function default](https://github.com/alibaba/rax/commit/619b7778518d238882f6ed95c47c3bf0881ee0e4)
3.  [use about:blank as the default value when bundle url missing](https://github.com/alibaba/rax/pull/262)
4.  [add location.replace location.assign location.reload](https://github.com/alibaba/rax/commit/d44544f4d053a9a91660b7e9376f73b185df521c)
> [jsfm] update rax jsfm to 0.3.4

- ios/sdk/WeexSDK/Sources/Component/WXComponent_internal.h
- ios/sdk/WeexSDK/Sources/Events/WXComponent+Events.m
- ios/sdk/WeexSDK/Sources/Layout/WXComponent+Layout.m
- ios/sdk/WeexSDK/Sources/Model/WXComponent.m
* [ios] Fix wrong borderRadius in resetting		
- [ios] remove unused methods	
* [ios] reset absolute position if layout is changed.
* [ios] Add cancel event to horizontal/vertical pan and fix issue that panend can not be triggered
> * [ios] bugfix for 0.13 features

- ios/sdk/WeexSDK/Sources/View/WXComponent+ViewManagement.m
+ [ios] fixbug: fix border reset bug
demo
http://dotwe.org/vue/a0980ed6d68cf81557a61d810fbe9446
> + [ios] fixbug: fix border reset bug

- package.json
changes in rax framework:
1. [add XMLHttpRequest](https://github.com/alibaba/rax/commit/fba30ec23e4641ef45804dc52fc80eda83523544)
> [jsfm] update rax jsfm to 0.3.5

- ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.h
> * [ios] fix WXBridgeContext.h annotation

- test/scripts/components/scroll-event.test.js
- test/scripts/util.js
> + [ios] update maraca case

- ios/sdk/WeexSDK/Sources/Utility/WXUtility.h
- ios/sdk/WeexSDK/Sources/Utility/WXUtility.m
+ [ios] add feature custom monitor info
> + [ios] add feature custom monitor info

- test/scripts/components/recycler.test.js
+ [ios] update macaca case to android
> + [ios] update macaca case to android

- ios/sdk/WeexSDK/Sources/Component/WXTransform.h
- ios/sdk/WeexSDK/Sources/Component/WXTransform.m
- ios/sdk/WeexSDK/Sources/Model/WXComponent.h
- ios/sdk/WeexSDK/Sources/Model/WXComponent.m
- ios/sdk/WeexSDK/Sources/View/WXComponent+ViewManagement.m
* [ios] add updateTransform interface to WXComponent to enable setting native transform directly, instead of updating css styles and parsing them.
> * [ios] add updateTransform interface to WXComponent

- android/sdk/src/main/java/com/taobao/weex/ui/component/AbstractEditComponent.java
> * [android] ignore fire the oninput event after setText called

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
support default style for border-width, border-radius and border-color
iOS: https://github.com/apache/incubator-weex/pull/376
> + [android] provide default style for view border

- ios/sdk/WeexSDK/Sources/Component/WXCycleSliderComponent.m
- test/scripts/components/recycler.test.js
+ [ios] fixbug: cycle slider
slider set current index, it will send event to jsfm. but slider index maybe not change
add judgement for slider index
> + [ios] fixbug: cycle slider

- ios/playground/WeexDemo.xcodeproj/project.pbxproj
- test/run.sh
+ [ios] if user define auto run shell , not open terminal
> + [ios] if user define auto run shell , not open terminal

- doc/source/cn/v-0.10/references/components/input.md
- doc/source/references/components/input.md
> + [example] update input demo

- doc/source/cn/references/components/input.md
- doc/source/references/components/input.md
> + [doc] update input doc

- doc/source/cn/references/modules/websocket.md
- doc/source/references/modules/websocket.md
> + [ios] update websocket doc

- doc/source/cn/references/modules/websocket.md
- doc/source/references/modules/websocket.md
> + [doc] update websocket doc

- dangerfile.js
Include ios, android and js code files which are added, modified or deleted in PR.
> * [all] danger: Add check about test and doc

- doc/source/guide/index.md
> Fix some typos

- ios/sdk/WeexSDK/Sources/Component/WXCycleSliderComponent.m
- ios/sdk/WeexSDK/Sources/Module/WXTimerModule.m
> + [ios] bugfix timer & slider

- doc/source/guide/index.md
> Improved English Documentation Grammar 

- ios/sdk/WeexSDK/Sources/Component/WXCycleSliderComponent.m
+ [ios] update slider for maraca case
> + [ios] update slider for maraca case

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXSlider.java
I am already testing the basic gesture and it working well
> * [android] enable gesture for slider

- ios/sdk/WeexSDK/Sources/Component/WXEditComponent.m
- ios/sdk/WeexSDK/Sources/Utility/WXUtility.m
+ [ios] not input \n when return key type  is not set default
> + [ios] not input \n when return key type  is not set default

- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
> modify activity event

- doc/source/guide/intro/using-vue.md
This is optional. I noticed some awkward wording, and tried to reword some of it to make more sense. Feel free to reject if anyone disagrees.
> reword pieces of 'Getting Started' in using-vue.md

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
The animation.vue sample, all botton's click event will call twice
> * [android] fix:Repeat adding the same event

- html5/render/vue/components/input.js
- html5/render/vue/components/scrollable/loading-indicator.js
- html5/render/vue/utils/style.js
this pr enable `<input>` component support `placeholder-color` style.
```css
.input {
placeholder-color: red;
}
```
> [html5] support placeholder-color for input.

- ios/sdk/WeexSDK/Sources/Component/WXListComponent.m
- ios/sdk/WeexSDK/Sources/Component/WXTextComponent.m
- ios/sdk/WeexSDK/Sources/Events/WXComponent+Events.m
- ios/sdk/WeexSDK/Sources/Module/WXDomModule.m
- improve text draw performance
- fix gesture crash
- fix remove empty array crash
> * [ios] imporve text draw performance

- ios/sdk/WeexSDK/Sources/Component/WXCycleSliderComponent.m
+ [ios] add dealloc for sliderview
> + [ios] add dealloc for sliderview

- ios/sdk/WeexSDK/Sources/Component/WXCycleSliderComponent.m
+ [ios] fix slider bug when weex run in iOS 8.x
> + [ios] fix slider bug when weex run in iOS 8.x

- test/pages/components/textarea-maxlength.vue
- test/scripts/components/textarea-maxlength.test.js
- test/scripts/util.js
- test/serve.sh
> Ios bugfix mamaca 0.14 dev 0624

- html5/render/vue/README.md
- html5/render/vue/components/slider/slideMixin.js
- html5/render/vue/core/style.js
- html5/render/vue/mixins/scrollable.js
- html5/render/vue/utils/style.js
- package.json
- packages/weex-vue-render/package.json
this pr adds some new features, which contains:
* support pseudo-class styles: https://github.com/alibaba/weex/issues/942
* support `loadmore` event for horizontal scroller.
* fix slider's autoplay.
> [html5] add more features, such as pseudo-class styles, loadmore event for horizontal-scroller, etc.

- ios/sdk/WeexSDK/Sources/Utility/WXUtility.h
- ios/sdk/WeexSDK/Sources/Utility/WXUtility.m
1. support iPad when screen rotation
2. remove unused function
> * [ios] support iPad when screen rotation

- doc/source/cn/references/weex-variable.md
- doc/source/references/weex-variable.md
platform 'android' is lowercase.
> [doc] correct platform information.

- examples/vue/market/gcanvas.vue
- package.json
> * [example] update gcanvas version and example

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/WXCell.java
caculate by layout engine. @not-danger
https://issues.apache.org/jira/browse/WEEX-55
> * [android] change 'contentSize' value in list 'scroll' event, use value

- doc/source/cn/references/modules/meta.md
- doc/source/references/modules/meta.md
Add documents for the `meta` module, both in English and in Chinese.
> [doc] Add documents for the meta module

- ios/sdk/WeexSDK/Sources/Component/WXTransform.m
try case:  http://dotwe.org/vue/983c1437737a85c754c1e5e18e4848bd
> * [ios] bugfix when roate3d concat

- ios/sdk/WeexSDK/Sources/Module/WXPickerModule.m
bugfix：
弹出 picker 的同时，如果返回到了上个页面，无法关闭 picker
> * [ios] bugfix, dismiss pickerview if present

- doc/source/guide/set-up-env.md
Howdy!
I was hoping to update a few things I noticed on the Setting Environment website.
-Denny
> Fixing English grammar 

- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
- ios/sdk/WeexSDK/Sources/Module/WXAnimationModule.m
+ [ios] fix bug if duration is 0 or negative, animation time is given 0.25
example
http://dotwe.org/vue/4ac17cab8845cd4a5fd469e930ea9b9e
> + [ios] fix bug if duration is 0 or negative, animation time is given 0.25

- ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.m
> + [ios] merge method 

- doc/source/cn/references/advanced/extend-to-android.md
- doc/source/cn/references/components/image.md
- doc/source/cn/references/components/list.md
- doc/source/references/advanced/extend-to-android.md
- doc/source/references/components/image.md
> + [doc] update doc for proguard rules

- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
+ [ios] update default to cycslider
> + [ios] update default to cycslider

- ios/sdk/WeexSDK/Sources/Layout/WXComponent+Layout.m
> + [ios] delete ;

- html5/test/render/vue/core/node.js
- html5/test/render/vue/data/dotvue/event-bubble-bar.vue
- html5/test/render/vue/data/dotvue/event-bubble.vue
changes:
- remove some useless style code
- remove surplus instance from test case
> [html5] fix core test case error

- ios/sdk/WeexSDK.xcodeproj/project.pbxproj
- ios/sdk/WeexSDK/Sources/Manager/WXTracingManager.h
- ios/sdk/WeexSDK/Sources/WeexSDK.h
> + [ios] delete ,

- dangerfile.js
- html5/test/render/vue/core/node.js
- html5/test/render/vue/data/dotvue/event-bubble-bar.vue
- html5/test/render/vue/data/dotvue/event-bubble.vue
- html5/test/render/vue/modules/animation.js
- html5/test/render/vue/modules/dom.js
- html5/test/render/vue/modules/globalEvent.js
- html5/test/render/vue/modules/navigator.js
- html5/test/render/vue/modules/webview.js
Some errors occur when testing the core code, I modified the bubbles property to prevent the duplicate event of the click event to generate duplicate strings！
> * [html5] fix core node test case error

- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
add newNestedInstance method in WXSDKInstance, thus SubClass can instance custom nested WXSDKInstance in WXEmbed
> + [android] add newNestedInstance method in WXSDKInstance

- ios/playground/Podfile
> + [ios] update pod file

- ios/playground/Podfile
> + [ios] update podfile

- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
bugfix memoryleak component observer
> * [android] fix WXSDKInstance filed mComponentObserver memory leak

- ios/sdk/WeexSDK/Sources/Component/WXImageComponent.m
- test/pages/image-onload.vue
- test/scripts/components/image-onload.test.js
support to save the image to Photo Album in image component method
case:  http://dotwe.org/vue/55b9f0683f9c8bb9e12788626608da4c
jira issues: https://issues.apache.org/jira/browse/WEEX-62
> *[iOS] support new feature image component can save to Photo Album

- examples/vue/index.vue
- examples/vue/modules/picker.vue
> +[ios] add picker demo

- ios/sdk/WeexSDK/Sources/Component/WXEditComponent.m
- ios/sdk/WeexSDK/Sources/Component/WXTextAreaComponent.m
+ [ios] bugfix: textarea placeholder not right
> + [ios] bugfix: textarea placeholder not right

- build/karma.vue.conf.js
- examples/vue/components/scroller.vue
- examples/vue/modules/picker.vue
- html5/render/vue/components/scrollable/scroller.js
- html5/render/vue/components/scrollable/style.css
- html5/render/vue/modules/dom.js
- html5/test/render/vue/modules/dom.js
- package.json
- vue.html
changes:
- add contentsize return in getComponentRect function
- add scrollable property to control scroller is scrollable or not
- update picker demo
> [html5] update some featrues

- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridge.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXValidateProcessor.java
- android/sdk/src/main/java/com/taobao/weex/dom/WXDomObject.java
- android/sdk/src/main/java/com/taobao/weex/dom/action/AbstractAddElementAction.java
modify WXValidateProcessor and WXBridgeManager.etc to make  options params avalible.
> modify WXValidateProcessor to make  options params avalible@notdanger

- android/sdk/src/main/java/com/taobao/weex/dom/WXTextDomObject.java
This is for the purpose of lines in richtext , which inherits text.
> * [android] Refactor the process of lines style in text.

- .travis.yml
- android/build.gradle
- android/sdk/src/main/java/com/taobao/weex/utils/WXViewUtils.java
Ref <https://issues.apache.org/jira/browse/WEEX-64>
> * [android] Upgrade to API 25.

- ios/sdk/WeexSDK/Sources/Component/WXListComponent.m
> Add 32-bit device support.

- test/run.sh
> * [test] update retry

- android/sdk/src/main/java/com/taobao/weex/ui/view/refresh/core/WXSwipeLayout.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/refresh/wrapper/BaseBounceView.java
fix list on refresh header lost bug in viewpager
> *[android] fix list on refresh header lost bug in viewpager

- html5/render/browser/extend/api/storage.js
[html5] fix setItem cannot set value to 0 bug. https://aone.alibaba-inc.com/issue/12020693
> [html5] fix setItem cannot set value to 0 bug.

- dangerfile.js
test danger file when we need no danger
> test danger file

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
Testcase:
list: http://dotwe.org/weex/0eacaa08c50a9ef00474f2333c56743c
waterfall: http://dotwe.org/vue/7a9195643e9e8da352b0d879cdbe68c0
> * [android] compute content size and offset based on css layout result

- ios/playground/WeexDemo/WXExtModule.m
- test/scripts/attributes/compositing.test.js
- test/scripts/components/hyperlink.test.js
- test/scripts/components/iconfont.test.js
- test/scripts/components/image-onload.test.js
- test/scripts/components/input-event.test.js
- test/scripts/components/recycler.test.js
- test/scripts/components/refresh-loading.test.js
- test/scripts/components/scroll-event.test.js
- test/scripts/components/scroller-fixed.test.js
- test/scripts/components/slider-common.test.js
- test/scripts/components/slider-infinite.test.js
- test/scripts/components/switch-event.test.js
- test/scripts/components/text.test.js
- test/scripts/components/textarea-maxlength.test.js
- test/scripts/components/web-event.test.js
- test/scripts/css/border.test.js
- test/scripts/dom.test.js
- test/scripts/index.test.js
- test/scripts/modules/animation-translate.test.js
- test/scripts/modules/clipboard-event.test.js
- test/scripts/modules/downgrade-event.test.js
- test/scripts/modules/gesture-longpress.test.js
- test/scripts/modules/globalEvent.test.js
- test/scripts/modules/modal-event.test.js
- test/scripts/modules/picker-event.test.js
- test/scripts/modules/storage-event.test.js
- test/scripts/modules/stream-result.test.js
- test/scripts/modules/timer.test.js
- test/scripts/zcover-generate.js
* [test] retry when test failed, we need reopen the url
before -> beforeEach
after -> afterEach
> * [test] retry when test failed, we need reopen the url

- android/sdk/src/main/java/com/taobao/weex/ui/view/refresh/core/WXSwipeLayout.java
sample：https://alibaba.github.io/rax/playground/21a6bbf6-6836-41dd-ba53-03aa8e61dba7
> [android] fix WXRefresh won`t finish as expected

- doc/source/cn/guide/tools/index.md
- doc/source/cn/guide/tools/plugin.md
- doc/source/guide/tools/index.md
- doc/source/guide/tools/plugin.md
- doc/themes/weex/layout/_partial/sidebar.ejs
> * [doc] add doc of idea plugin

- android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
> * [android] change offset on scroll event to negative number

- doc/source/cn/references/common-style.md
- doc/source/cn/references/modules/animation.md
- doc/source/references/common-style.md
- doc/source/references/modules/animation.md
Add doc about transition and fix animation needLayout doc
> * [doc]  doc about transition and animation

- test/pages/components/switch-event.vue
- test/pages/include/wxc-desc.vue
- test/pages/modules/vue_timer.vue
- test/run.sh
- test/scripts/components/text.test.js
- test/scripts/dom.test.js
- test/scripts/modules/globalEvent.test.js
- test/scripts/modules/modal-event.test.js
- test/scripts/modules/timer.test.js
- test/scripts/util.js
* [test] bugfix caused by mocha retries changes
1、test script delete some case
2、test script logic change
> * [test] bugfix caused by mocha retries changes 

- examples/vue/index.vue
- examples/vue/transition.vue
- ios/sdk/WeexSDK/Sources/Module/WXAnimationModule.h
- ios/sdk/WeexSDK/Sources/Module/WXAnimationModule.m
- ios/sdk/WeexSDK/Sources/Module/WXTransition.h
- ios/sdk/WeexSDK/Sources/Module/WXTransition.m
- ios/sdk/WeexSDK/Sources/Utility/WXConvert.h
- ios/sdk/WeexSDK/Sources/Utility/WXConvert.m
- ios/sdk/WeexSDK/Sources/View/WXComponent+ViewManagement.m
- ios/sdk/WeexSDKTests/WXConvertTests.m
> * [ios] transition fix bug and fix examples

- doc/source/cn/references/common-style.md
- doc/source/cn/references/modules/animation.md
- doc/source/references/common-style.md
- doc/source/references/modules/animation.md
fix website can not show table bug
> * [doc] fix transition table can not show bug

- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
> * [android] fix NPE on reading bundle data size

- android/commons/src/main/java/com/alibaba/weex/commons/adapter/FrescoImageComponent.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXImage.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/WXImageView.java
- android/sdk/src/main/java/com/taobao/weex/utils/ImageDrawable.java
The "resize" attribute on image doesn't depend on ImageView.setScaleType any longer, BitmapShader can do all the work.
@notdanger
> * [android] Refactor the code of resize attr on image.

- doc/themes/weex/languages/en.yml
> Fix typo in involved

- android/sdk/src/main/java/com/taobao/weex/ui/component/AbstractEditComponent.java
Testcase: http://dotwe.org/vue/9b024ef78f8b8fd18095569aa8d72021
> * [android] fix wrong setting font size

- android/sdk/src/main/java/com/taobao/weex/dom/action/TraceableAction.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
> * [android] fix crash caused by invalid position

- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
show alert in debug mode when pageName equals to `default`
> * [android] show alert in debug mode when pageName not be set

- ios/playground/WeexDemo/WXConfigCenterDefaultImpl.m
- ios/sdk/WeexSDK/Sources/Manager/WXComponentManager.m
- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
- ios/sdk/WeexSDK/Sources/Module/WXPrerenderManager.h
- ios/sdk/WeexSDK/Sources/Module/WXPrerenderManager.m
+ [ios] protect remove in pretender
> + [ios] protect remove in pretender

- ios/sdk/WeexSDK/Sources/Module/WXPrerenderManager.m
> + [ios]  delete no user code

- android/sdk/src/main/java/com/taobao/weex/ui/component/AppearanceHelper.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXScroller.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
1、fix sticky bug, when back to top
2、when child height is zero,  appear event in list should be fired
@notdanger
> 0.16 dev fix sticky

- android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
as the title, no testcase needed
> * [android] fix NPE on findFirstVisibleItemPosition

- ios/sdk/WeexSDK/Sources/Controller/WXBaseViewController.m
- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
- ios/sdk/WeexSDK/Sources/Module/WXPrerenderManager.h
- ios/sdk/WeexSDK/Sources/Module/WXPrerenderManager.m
+ [ios] distinguish the global pretender and user pretender
> + [ios] distinguish the global pretender and user pretender

- android/sdk/src/main/java/com/taobao/weex/common/Constants.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
- android/sdk/src/main/java/com/taobao/weex/utils/WXUtils.java
1. handle undefined&auto value to Float.NaN remove exception log output
2. fix list memory leak when exist more than one
> 0.16 dev list bugfix

- ios/sdk/WeexSDK/Sources/Component/WXEditComponent.m
- ios/sdk/WeexSDK/Sources/Component/WXImageComponent.m
- ios/sdk/WeexSDK/Sources/Utility/WXConvert.m
set image default quality  none
> * [ios] fix image default quality

- ios/sdk/WeexSDK/Sources/Component/WXWebComponent.m
> * [iOS] webview scale page to fit

- test/pages/components/textarea-placeholder.vue
- test/pages/include/navbar.vue
- test/pages/include/navpage.vue
- test/pages/modules/navigator-event.vue
- test/pages/modules/viewport-basic.vue
- test/scripts/components/textarea-placeholder.test.js
- test/scripts/modules/navigator-event.test.js
- test/scripts/modules/viewport-basic.test.js
- test/scripts/util.js
0.16 dev add tc
1、add navigator viewport tc
> 0.16 dev add tc

- android/sdk/src/main/java/com/taobao/weex/ui/component/list/WXCell.java
1. fix the bug that  the cell  with ”fixed” attribute can not render in list
> * [android] fix the bug that  the cell  with ”fixed” attribute

- ios/sdk/WeexSDK/Sources/Module/WXPrerenderManager.m
+ [ios] judge task from config
> + [ios] judge task from config

- test/run.sh
fix jacoco assemble build else
> * [test] add jacoco test else assemble

- doc/source/cn/references/advanced/extend-to-android.md
1. add  the right proguard config of extend-to-android
> * [android] add  the right proguard config of extend-to-android

- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
* 0.16 dev bugfix wx parallax scrollerlistener memoryleak
* bugfix renderContainer memoryleak
> 0.16 dev bugfix wx parallax scrollerlistener memoryleak

- android/sdk/src/main/java/com/taobao/weex/dom/WXStyle.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/border/BorderCorner.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/border/BorderUtil.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/border/BottomLeftCorner.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/border/BottomRightCorner.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/border/TopLeftCorner.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/border/TopRightCorner.java
- android/sdk/src/main/java/com/taobao/weex/utils/FunctionParser.java
> Remove useless method in Android

- android/sdk/src/main/java/com/taobao/weex/appfram/websocket/WebSocketCloseCodes.java
- android/sdk/src/main/java/com/taobao/weex/utils/OsVersion.java
- android/sdk/src/main/java/com/taobao/weex/utils/Trace.java
> * [android] fix java doc

- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
- scripts/build_from_source.sh
* [android] gradle update to version 3.3 and fix javadoc issues
> * [android] gradle update to version 3.3 and fix javadoc issues

- doc/source/cn/guide/set-up-env.md
- doc/source/cn/guide/tools/toolkit.md
- doc/source/guide/set-up-env.md
- doc/source/guide/tools/toolkit.md
bugfix week init project run command
> * [doc] bugfix weex init project run command @notdanger

- doc/source/cn/guide/index.md
- doc/source/guide/index.md
bugfix behind：
1、The lack of link，some desc not right in cn doc
2、cannot open link in en doc
> * [doc] bug fix index

- .travis.yml
- POSSIBLE-NOTICES-FOR-BIN-DIST
- dangerfile-android.js
- dangerfile-ios.js
- dangerfile-jsfm.js
- package.json
- scripts/generate_apache_release.sh
- test/pages/components/iconfont.vue
travis CI update
1、don't run ios if nochange about ios
2、don't run android if nochange about android
3、don't run jsfm if nochange about jsfm
4、don't run build when release type
5、add shelljs devdependence for run shell in nodejs
> Test bugfix travis

- doc/source/cn/guide/set-up-env.md
- doc/source/guide/set-up-env.md
Update generate command for weex-toolkit.
> * [doc] update set-up-env.md

- android/sdk/src/main/java/com/taobao/weex/dom/WXTextDomObject.java
* [android] Fix the problem of  'text-overflow:clip'  will delete the second last word
> * [android] Fix the problem of  'text-overflow:clip' 

- .travis.yml
> * [test] bugfix env iOS

- android/sdk/src/main/java/com/taobao/weex/ui/view/WXBaseCircleIndicator.java
Testcase:
http://dotwe.org/weex/66c39d1999e50e9b8274b1a4a7aa02c5
> * [android] fix wrong draw indicator

- ios/sdk/WeexSDK/Sources/Manager/WXComponentManager.m
- ios/sdk/WeexSDK/Sources/Model/WXComponent.m
- ios/sdk/WeexSDK/Sources/Module/WXAnimationModule.m
fix a bug about transition filter make crash
> * [ios] fix transition filter crash bug && animationmodule callback bug

- ios/sdk/WeexSDK.xcodeproj/project.pbxproj
- ios/sdk/WeexSDK/Sources/Display/WXComponent+Display.m
case: http://dotwe.org/weex/4da9faa8e4b6ab0e45822b5758d82caa
> * [ios] bugfix about single border radius conflict with opacity

- ios/sdk/WeexSDK/Sources/Bridge/WXJSCoreBridge.m
> + [ios] add timers

- doc/source/guide/set-up-env.md
* fix doc dotwe scheme
* bug issuse link https://issues.apache.org/jira/browse/WEEX-72
> * [doc] fix doc dotwe address

- .travis.yml
Test bugfix remove ios：
1、delete all ios env dependence.
> * [test] remove travis iOS

- doc/source/cn/guide/index.md
- doc/source/cn/guide/set-up-env.md
- doc/source/cn/guide/tools/toolkit.md
- doc/source/cn/references/advanced/extend-to-android.md
- doc/source/cn/references/common-style.md
- doc/source/cn/references/components/text.md
- doc/source/cn/references/modules/animation.md
- doc/source/cn/references/modules/dom.md
- doc/source/guide/index.md
- doc/source/guide/set-up-env.md
- doc/source/guide/tools/toolkit.md
- doc/source/references/common-style.md
- doc/source/references/components/text.md
- doc/source/references/modules/animation.md
- doc/source/references/modules/dom.md
- ios/sdk/WeexSDK/Sources/Component/WXWebComponent.m
merge dev doc to 0.16-dev
1、doc 
2、out pr about ios web
> Doc merge dev

- ios/sdk/WeexSDK.xcodeproj/project.pbxproj
- ios/sdk/WeexSDK/Sources/WeexSDK.h
+ [ios] set the wxwebsock handler public
> + [ios] set the wxwebsock handler public

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXImage.java
fix image view bug, clear image when resuse
> fix image view bug, clear image when resuse

- .travis.yml
- dangerfile-android.js
- dangerfile-ios.js
- dangerfile-jsfm.js
- dangerfile.js
- package.json
update danger version and danger file import:
1. danger version > 1.0.0 has bug,revert version to 0.18.0
2. danger file import danger
> * [test] update danger version and danger file import

- doc/source/cn/references/modules/animation.md
- doc/source/references/modules/animation.md
animationModule doc add callback message and fix some bug with doc
> * [doc] add message about animation callback

- html5/render/vue/components/input.js
- ios/sdk/WeexSDK/Sources/Component/WXWebComponent.m
> * [doc] fix typo

- doc/source/cn/guide/set-up-env.md
- doc/source/guide/set-up-env.md
- start
Update start  command for develop。
> * [html5] update start  command for develop

- ios/sdk/WeexSDK/Sources/Display/WXComponent+Display.m
- ios/sdk/WeexSDK/Sources/Manager/WXComponentManager.m
- ios/sdk/WeexSDK/Sources/Model/WXComponent.m
- ios/sdk/WeexSDK/Sources/Module/WXTransition.h
- ios/sdk/WeexSDK/Sources/Module/WXTransition.m
> * [ios] fix pr bug about filter crash

- android/sdk/src/main/java/com/taobao/weex/ui/component/binding/Statements.java
> correct code

- .github/PULL_REQUEST_TEMPLATE.md
> Doc feature pr rule

- ios/sdk/WeexSDK/Sources/Component/WXWebComponent.m
> 去掉webview最下面的黑线

- html5/render/browser/extend/api/stream.js
Add custom jsonp callback name support, refer to #298
> * [html5] add custom jsonp callback name support

- android/sdk/src/main/java/com/taobao/weex/dom/WXEvent.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
> handle null junit failed test case

- android/sdk/src/main/java/com/taobao/weex/dom/WXAttr.java
- android/sdk/src/main/java/com/taobao/weex/dom/binding/ELUtils.java
- android/sdk/src/main/java/com/taobao/weex/dom/binding/WXStatement.java
> reduce method for weex

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
- android/sdk/src/main/java/com/taobao/weex/utils/BoxShadowUtil.java
Using `BlurMaskFilter` instead of the `Paint.setSahdowLayer` to draw shadow layer
Testcase:
http://dotwe.org/vue/2023765cfe6cfc27f722ab88e014fbfe
> * [android] better solution for draw box-shadow

- android/sdk/src/main/java/com/taobao/weex/WXSDKEngine.java
- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridge.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
- android/sdk/src/main/java/com/taobao/weex/utils/WXLogUtils.java
1. open exception log for debug
2. use tlog to upload debug log
3. when jsf init fail will return false and use h5 render page
> 0.16 dev fix whitescreen

- ios/sdk/WeexSDK/Sources/Component/WXImageComponent.m
- ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.m
- ios/sdk/WeexSDK/Sources/Component/WXTransform.m
- ios/sdk/WeexSDK/Sources/Controller/WXBaseViewController.h
- ios/sdk/WeexSDK/Sources/Module/WXWebSocketModule.m
- ios/sdk/WeexSDK/Sources/Utility/WXUtility.m
* [ios] support attributes to set scrollVertical when the scrollView contentSize smaller than the scrollview frame size 
try case : http://dotwe.org/vue/7f349e0545703a3f17d7757e27c80849
> * [ios]  support attributes to set scrollVertical when the scrollView contentSize smaller than the scrollview frame size 

- doc/source/cn/guide/set-up-env.md
- doc/source/guide/set-up-env.md
Updated grammar and expression glitches in "Setup Development
Environment", also added dotWe link to the corresponding Chinese
version of this document.
Bug: WEEX-76
> * [doc] Fixed grammar glitches in set-up-env.

- doc/source/cn/references/advanced/extend-to-ios.md
- doc/source/cn/references/components/image.md
- doc/source/references/advanced/extend-to-ios.md
- doc/source/references/components/image.md
update new feature documentation for image component
> + [doc] update new feature documentation for image component

- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
if init framework fail, will collect info and upload
>  * [android] add init jsf exception collection

- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
- android/sdk/src/test/java/com/taobao/weex/WXSDKEngineTest.java
> Fix test case

- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
- android/sdk/src/main/java/com/taobao/weex/utils/WXFileUtils.java
- android/sdk/src/test/java/com/taobao/weex/utils/WXFileUtilsTest.java
1、record md5 when js execute exception
2、fix scroll to element not scroll when none scroll action
> fix scroll to bug and  add md5 for template

- ios/sdk/WeexSDK/Sources/Component/WXCycleSliderComponent.m
* Change current index on cycleSlider.
> change current index

- android/sdk/build.gradle
- android/sdk/src/test/java/com/taobao/weex/utils/WXUtilsTest.java
* [android] fix unit android test log mocked
> * [android] fix unit android test log mocked

- android/sdk/src/main/java/com/taobao/weex/WXSDKEngine.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
- android/sdk/src/main/java/com/taobao/weex/dom/WXDomObject.java
- android/sdk/src/main/java/com/taobao/weex/dom/action/AbstractAddElementAction.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponentFactory.java
- android/sdk/src/main/java/com/taobao/weex/utils/WXLogUtils.java
- android/sdk/src/test/java/com/taobao/weex/utils/WXLogUtilsTest.java
1. modify log level according to App environment
2. open some  log  switch if log level > LogLevel.WARN
> WXLogUtils Log Level

- android/sdk/src/main/java/com/taobao/weex/ui/view/listview/WXRecyclerView.java
1、handle scroll to element position right
> when touch  use scroll handler, when none touch use nonstop

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
- android/sdk/src/main/java/com/taobao/weex/utils/BoxShadowUtil.java
add switcher to disable box-shadow globally
> * [android] add switcher to disable box-shadow globally

- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
* [android] create instance exception when jsf not ready or jsc cannot start up will use h5 to render page
> Release 0.16 bugfix

- android/sdk/src/main/java/com/taobao/weex/common/Constants.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXImage.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/WXImageView.java
Auto Recycle ImageView's Bitmap
> Auto Recycle ImageView's Bitmap

- html5/runtime/vdom/Element.js
Add `setAttrs` and `setStyles` method on `Element.prototype` to support batch update styles and attributes.
This feature can be used in the DSL framework (Vue.js or Rax) to optimize performance.
> [jsfm] Support batch update styles and attributes

- html5/render/browser/extend/api/storage.js
- html5/render/browser/extend/api/stream.js
- html5/render/vue/README.md
- html5/render/vue/components/a.js
- html5/render/vue/components/image.js
- html5/render/vue/components/slider/indicator.js
- html5/render/vue/env/weex.js
- html5/render/vue/index.js
- html5/render/vue/mixins/base.js
- html5/render/vue/mixins/style.js
- html5/render/vue/modules/dom.js
- html5/render/vue/utils/component.js
- html5/render/vue/utils/lazyload.js
- html5/test/render/vue/components/image.js
- html5/test/render/vue/components/switch.js
- html5/test/render/vue/components/text.js
- html5/test/render/vue/modules/dom.js
- package.json
- packages/weex-vue-render/README.md
- packages/weex-vue-render/package.json
- scroll event listenning on window.
- img lazyloading.
- scrollToElement on latest chrome.
- rm id of a comp.
- fix stream.fetch.
- add statistics for components and modules.
- support lazyload and appear watcher when body height set to 100%
- add try catch for accessing localStorage may throw a error.
- image support sprite (sprite-src, sprite-position, sprite-width).
- fix indicator when there's only one slide in slider.
> * [html5] bugfix

- android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
when cell amount is big, watch appear will none changed will result too many logs when scroll, move log after appear changed
> when cell amount is big, watch appear will none changed will result too many logs

- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
- android/sdk/src/main/java/com/taobao/weex/ui/module/WXTimerModule.java
remove log when app run, improve performance， too many logs
> remove log when app run in production, improve performance

- android/sdk/src/main/java/com/taobao/weex/ui/component/list/WXCell.java
1、when header view has parent, remove it from parent
> when header view has parent, remove it from parent

- android/sdk/src/main/java/com/taobao/weex/WXEnvironment.java
* [devtool] fix devtool network mode
> * [devtool] fix devtool network mode

- android/sdk/src/main/java/com/taobao/weex/utils/WXLogUtils.java
* [android] android  bugfixed logwatcher
> * [android] android  bugfixed logwatcher

- ios/sdk/WeexSDK/Sources/Module/WXWebSocketModule.m
> [ios] delete some spaces.

- android/sdk/src/main/java/com/taobao/weex/appfram/pickers/DatePickerImpl.java
- android/sdk/src/main/java/com/taobao/weex/appfram/pickers/WXPickersModule.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/helper/WXTimeInputHelper.java
Allow user setting button text on every system UI we used
> [WEEX-100][Android] support multi language on dialog

- android/sdk/src/main/java/com/taobao/weex/ui/component/list/WXListComponent.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/template/WXRecyclerTemplateList.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/refresh/core/WXSwipeLayout.java
[WEEX-110][android]WXSwipeLayout support nested scroll for list
http://dotwe.org/vue/5ffa330ee135b61c37544879d89ddd08
>  [WEEX-110][android]WXSwipeLayout support nested scrolling for list

- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/WXCell.java
- android/sdk/src/main/java/com/taobao/weex/ui/module/WXTimerModule.java
- android/sdk/src/main/java/com/taobao/weex/utils/WXLogUtils.java
* instance support extend dimensionality and indicator to tolerance of performance
* fix logwatcher bug in release mode
see
[[WEEX-115]](https://issues.apache.org/jira/browse/WEEX-115)
[android]logwatcher is design to support release environment critical issuses analyzing
> [WEEX-115] [android]logwatcher is design to support release environment critical issuses analyzing

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
replace RippleDrawable to Drawable
> * [android] avoid crash on some device caused by RippleDrawable

- android/sdk/src/main/java/com/taobao/weex/utils/WXViewUtils.java
revert to only judge on android version.
keep the param of targetView for future try.
> revert clip path targetview judge.

- ios/sdk/WeexSDK/Sources/Module/WXTransition.h
- ios/sdk/WeexSDK/Sources/Module/WXTransition.m
Improve transition's stability and fix some bugs about various transform.
Also, make some variable names become nice.
> [WEEX-125][iOS]Transition Animation Support

- ios/sdk/WeexSDK/Sources/Bridge/WXJSCoreBridge.m
- ios/sdk/WeexSDK/Sources/Monitor/WXExceptionUtils.m
1. compatible old logic;
2. use instance.pageName as default for front user.
CheckList:
> [WEEX-126][iOS] protect for pagename when need send jserror

- ios/sdk/WeexSDK/Sources/Manager/WXComponentManager.m
try to optimize unload too much component
> [WEEX-120][iOS]try to optimize unload weex component

- ios/sdk/WeexSDK/Sources/Component/WXTransform.m
bugfix transform crash about unknow selector
Bug:124
> [WEEX-124][iOS] bugfix transform crash about unknow selector

- android/sdk/src/main/java/com/taobao/weex/common/Constants.java
- android/sdk/src/main/java/com/taobao/weex/dom/WXDomObject.java
Release 0.17 layout animation improve, overflow :hidden default switch off
> Release 0.17 layout animation improve, overflow :hidden default switch off

- html5/runtime/utils.js
- html5/runtime/vdom/Element.js
- html5/test/unit/runtime/utils.js
Check if the batched styles and attributes are empty, and then, only send the mutations to native.
> [WEEX-182][jsfm] only update batched and mutated attributes and styles

- android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
[WEEX-179][android]List View Component supported show scrollbar options
> [WEEX-179][android]List View Component supported show scrollbar options

- android/sdk/src/main/java/com/taobao/weex/WXEnvironment.java
rm "final" so that we can change sForceEnableDevTool's value
> [android] [bugfix] rm "final" for "sForceEnableDevTool"

- ios/sdk/WeexSDK/Sources/Manager/WXServiceFactory.m
fix unregisterServiceScript service name with js string
> [WEEX-196][iOS] fix unregisterServiceScript service name

- android/sdk/src/main/java/com/taobao/weex/common/Constants.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/AbstractEditComponent.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/WXEditText.java
Testcase:
http://dotwe.org/vue/fbe2897970b37269be07d17b0e9cf4a2
> [Android]Enhancement for input component

- ios/sdk/WeexSDK/Sources/Component/RecycleList/WXRecycleListComponent.m
*[iOS]fix annotation spell error.
> *[iOS]fix annotation spell error.

- ios/sdk/WeexSDK/Sources/Component/WXEditComponent.m
move up WXRootView according to configuraiton
> * [iOS] move up WXRootView according to configuraiton

- ios/sdk/WeexSDK/Sources/Component/Recycler/WXMultiColumnLayout.h
- ios/sdk/WeexSDK/Sources/Component/Recycler/WXMultiColumnLayout.m
- ios/sdk/WeexSDK/Sources/Component/Recycler/WXRecyclerComponent.m
try case:  http://dotwe.org/vue/16ca2c8a9b0d7298f67bc0e7a1314c15
support leftGap and rightGap for waterfall component, thus you 
can specify the leftGap and rightGap for cell inside waterfall.
feature:218
> [WEEX-218][iOS] support leftGap and rightGap for waterfall component

- ios/playground/WeexDemo/extend/handler/WXImgLoaderDefaultImpl.m
- ios/sdk/WeexSDK/Sources/Component/WXImageComponent.m
- ios/sdk/WeexSDK/Sources/Protocol/WXImgLoaderProtocol.h
add more download image interface, you can obtain more details such as the progress of downloading image
Bug:239
> [WEEX-239] add more download image interface for imageloader

- ios/sdk/WeexSDK/Sources/Component/WXTextComponent.m
> [WEEX-245][ios]fix CTFont crash on iOS10

- android/sdk/src/main/java/com/taobao/weex/ui/view/gesture/WXGesture.java
- android/sdk/src/main/java/com/taobao/weex/wson/Wson.java
- android/sdk/src/test/java/com/taobao/weex/wson/AnnoTest.java
- android/sdk/src/test/java/com/taobao/weex/wson/Person.java
[WEEX-244][android]Weex Android Support W3c Force Api
db3895a
> [WEEX-244][android]Weex Android Support W3c Force Api

- android/sdk/src/main/java/com/taobao/weex/dom/WXTextDomObject.java
- android/sdk/src/main/java/com/taobao/weex/dom/text/FontBroadcastReceiver.java
[WEEX-224][android] WXDomObject Destory Method Should Be Called avoid Memory Leak
>  [WEEX-224][android] WXDomObject Destory Method Should Be Called avoid Memory Leak

- ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.m
fix typo of WXScrollerComponentView
> fix typo of WXScrollerComponentView

- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
[WEEX-288][android] bug fix, fix on some case cannot get bundle type
>  [WEEX-288][android] bug fix, fix on some case cannot get bundle type

- ios/playground/Podfile
remove canvas dependency for playground app
> remove canvas dependency for playground app

- ios/sdk/WeexSDK.xcodeproj/project.pbxproj
- ios/sdk/WeexSDK/Sources/WeexSDK.h
> set recyclerComponent.h public

- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
move update context instanceId out so that debug tool can update it
> move update context instanceId out

- ios/sdk/WeexSDK.xcodeproj/project.pbxproj
*isBugFix* **:**
- public head  WXRecyclerComponent.h
- add build WXTransition.mm
> * [iOS] build fix

- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
- android/sdk/src/main/java/com/taobao/weex/common/WXImageStrategy.java
- android/sdk/src/main/java/com/taobao/weex/common/WXRequest.java
- android/sdk/src/main/java/com/taobao/weex/http/WXStreamModule.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXImage.java
> + [android] add instanceId declaring the caller instance

- ios/sdk/WeexSDK/Sources/Manager/WXComponentManager.mm
- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance_performance.h
- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance_performance.m
- ios/sdk/WeexSDK/Sources/Monitor/WXAnalyzerCenter.m
- ios/sdk/WeexSDK/Sources/Monitor/WXMonitor.h
- ios/sdk/WeexSDK/Sources/Monitor/WXMonitor.m
- ios/sdk/WeexSDK/Sources/Protocol/WXAppMonitorProtocol.h
*isNewFeature* **:**
* [ x] Update API docs for the component.
* [ x] Update/Add demo to demonstrate new feature.
- add 4 performance point 
- componentCount
- componentCreateTime
- fsComponentCount
- fsComponentCreateTime
> [WEEX-339][iOS] add componentTime/Count monitor

- ios/sdk/WeexSDK/Sources/Module/WXAnimationModule.m
fix some pr bug about animation with nill property
> [WEEX-345] [iOS] fix animationModule with needLayout bug with nil propery

- android/sdk/build.gradle
- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
[WEEX-399][Android] remove extra api js
remove extra api js
Bug: WEEX-399
https://issues.apache.org/jira/browse/WEEX-399
> [WEEX-399][Android] remove extra api js

- ios/sdk/WeexSDK/Sources/Model/WXComponent.mm
1. All gesture recognizer delegate added to WXComponent should be set to nil on iOS8
2. Provided a config to turn on/off, default is on
> [Weex-410][iOS] Fix gesture related crash on iOS8 with config

- weex_core/Source/CMakeLists.txt
- weex_core/Source/wson/CMakeLists.txt
1. make wson compilation modular
2. build IPC WSON only if Android taget
> [WEEX-405] [core] make wson compilation modular

- android/sdk/src/main/java/com/taobao/weex/common/Constants.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/gesture/WXGesture.java
[WEEX-419][android] weeks bugfix for weex AccessibilityNodeInfoCompat&rax stopPropagation event listener
> [WEEX-419][android] weeks bugfix for weex AccessibilityNodeInfoCompat&rax stopPropagation event listener

- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridge.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
- android/sdk/src/main/java/com/taobao/weex/common/IWXBridge.java
- android/sdk/src/main/java/com/taobao/weex/dom/WXAttr.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/template/WXRecyclerTemplateList.java
- weex_core/Source/android/bridge/impl/bridge_impl_android.cpp
- weex_core/Source/android/bridge/impl/bridge_impl_android.h
- weex_core/Source/core/layout/measure_func_adapter_impl_android.h
[WEEX-408][android] measure func not right recyclelist update measurefunction and support horizontal
> [WEEX-408][android] measure func not right recyclelist update measurefunction and support horizontal

- android/sdk/src/main/java/com/taobao/weex/bridge/WXJsFunctions.java
- android/sdk/src/main/java/com/taobao/weex/utils/WXWsonJSONSwitch.java
- weex_core/Source/CMakeLists.txt
- weex_core/Source/android/base/jni/jbytearray_ref.cpp
- weex_core/Source/android/base/jni/jbytearray_ref.h
- weex_core/Source/android/bridge/impl/jsfunction_impl_android.cpp
[WEEX-408][android] weex dev tool update
> [WEEX-408][android] weex dev tool update 

- weex_core/Source/core/manager/weex_core_manager.cpp
- weex_core/Source/core/manager/weex_core_manager.h
return return type  with `WeexCoreManager`
> [WEEX-458][core] remove coremanager setxxx returntype

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/gesture/WXGesture.java
- scripts/generate_apache_release.sh
[WEEX-342][android] ava.util.ConcurrentModificationException  at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)at
> [WEEX-342][android] ava.util.ConcurrentModificationException  at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)at 

- ios/sdk/WeexSDK/Sources/Manager/WXComponentManager.mm
> [WEEX-468][iOS] Try to fix Fixed component related crash.

- POSSIBLE-NOTICES-FOR-BIN-DIST
- examples/vue/include/base-url.js
- index.html
- package.json
- rm 'autoprefixer', 'query-string', 'weex-picker' from 'POSSIBLE-NOTICES-FOR-BIN-DIST' and clean dependencies accordingly.
- fix repo info of 'weex-vue-render' in 'POSSIBLE-NOTICES-FOR-BIN-DIST'.
- fix examples' path on web.
- clean codes in 'index.html'.
> clean notices & fix web demo & add dependency of weex-vue-render.

- android/sdk/src/main/java/com/taobao/weex/WXSDKEngine.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXModuleManager.java
https://issues.apache.org/jira/browse/WEEX-488
> [Weex-488] InstanceWrap unavailable on Android

- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
- android/sdk/src/main/java/com/taobao/weex/WXSDKManager.java
- android/sdk/src/main/java/com/taobao/weex/utils/WXExceptionUtils.java
bug fix: report url is bundleUrlDefault
before createInstance success stage ,we can't get instance  by id from WXSDKManager,
case :
- [✓]after createInstance success,some error
> [WEEX-498][Android] fix report url is bundleUrlDefault

- ios/sdk/WeexSDK/Sources/Component/WXListComponent.mm
- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
- ios/sdk/WeexSDK/Sources/Utility/WXUtility.h
- ios/sdk/WeexSDK/Sources/Utility/WXUtility.m
> [WEEX-501][iOS] Try to fix insert table view cell exception abort on iOS

- build/build.js
- build/config.js
- scripts/build_from_source.sh
+ Change the build target of js framework files to the `dist` path instead of `pre-build`.
+ Modify the `build_from_source.sh` to copy the correct js framework files to the `pre-build` folder.
> [WEEX-397][jsfm] update build script of js framework

- ios/sdk/WeexSDK/Sources/Component/WXTextAreaComponent.m
http://dotwe.org/vue/7c839c2484f247095e27f0276acaabc8
placeholder在设置padding-right时显示也异常
> [WEEX-528][iOS] fix textaera set padding-right invalid

- runtime/bridge/TaskCenter.js
> [jsfm] task center normalize for native virtual element

- CHANGELOG.md
> Fixed Spelling.

- runtime/bridge/TaskCenter.js
> [jsfm] change vRef to ref

- android/sdk/src/main/java/com/taobao/weex/common/Constants.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/WXListComponent.java
doc update ：https://github.com/apache/incubator-weex-site/pull/182
> * [android] add  pagingEnabled ="true"  attribute of list component

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXImage.java
Change access level for image component of android
> * [Android] Change method access level for image

- weex_core/Source/core/layout/layout.cpp
Fix http://dotwe.org/vue/ce6283454398d66ceb0fca068aa704ec
> * [Android] Fix text layout problem.

- android/sdk/src/main/java/com/taobao/weex/WXSDKEngine.java
- android/sdk/src/main/java/com/taobao/weex/WXSDKManager.java
- android/sdk/src/main/java/com/taobao/weex/appfram/navigator/INavigator.java
- android/sdk/src/main/java/com/taobao/weex/appfram/navigator/WXNavigatorModule.java
1. add Navigator interface to adapter ''push"&“pop”
> [android] add Navigator interface to adapter ''push"&“pop”

- weex_core/Source/core/layout/layout.cpp
Fix the following case, which is the same case in my opinion.
* http://dotwe.org/vue/cf3151b4998e8f5c7adda9a85b47d864
* http://dotwe.org/vue/42176496c85d43b2016513588eeb6b10
* http://dotwe.org/vue/55014cc3ada41e048ac0f90c1454096a
> * [Android] Fix text height problem.

- android/sdk/src/main/java/com/taobao/weex/appfram/navigator/INavigator.java
- android/sdk/src/main/java/com/taobao/weex/appfram/navigator/WXNavigatorModule.java
1. add "activity" param  to INavigator interface
> [android] add "activity" param  to INavigator interface

- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
- android/sdk/src/main/java/com/taobao/weex/performance/WXInstanceApm.java
- android/sdk/src/main/java/com/taobao/weex/ui/action/GraphicActionCreateFinish.java
> [WEEX-554][Android] fix fsRender Time

- ios/sdk/WeexSDK/Sources/Layout/WXCoreLayout.cpp
- layoutEngin Fix text height problem.
- layoutEngin Fix text layout problem.
-  Fix flex-grow problem on text
http://dotwe.org/vue/ce6283454398d66ceb0fca068aa704ec
http://dotwe.org/vue/cf3151b4998e8f5c7adda9a85b47d864
http://dotwe.org/vue/42176496c85d43b2016513588eeb6b10
http://dotwe.org/vue/55014cc3ada41e048ac0f90c1454096a
- Fix max-width problem. 
http://dotwe.org/vue/4022e76a68de681d423ea49ae434deff
> [WEEX-555][iOS] fix layout engin bug

- android/sdk/src/main/java/com/taobao/weex/ui/config/AutoScanConfigRegister.java
[WEEX-568][Android]Add Scan Delay Interface For AutoScanConfigRegister
> [WEEX-568][Android]Add Scan Delay Interface For AutoScanConfigRegister

- ios/sdk/WeexSDK/Sources/Component/WXImageComponent.m
bug fix 
- NSDictionary value can't be nil
>  [WEEX-561][iOS] performance : fix dic value is nil 

- ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.m
three case of create instance 
- normal
- sandbox
- devtool
> [WEEX-571][iOS]peformance record, fix createInstance time in snandbox

- ios/sdk/WeexSDK/Sources/Model/WXComponent.mm
Try to solve transition's occasional crash, may due to missing copy styles dictionary.
> [WEEX-573][iOS] try to solve transition's occasional crash

- ios/sdk/WeexSDK/Sources/Component/WXVideoComponent.m
- ios/sdk/WeexSDK/Sources/Display/WXComponent+Display.m
- ios/sdk/WeexSDK/Sources/Model/WXComponent.h
Make 'video' and 'videoplus' support border radius.
You can see demo here:http://rax.alibaba-inc.com/playground/8dff7a17-1a0b-407d-a77d-6a86e11c87a9
> [WEEX-574][iOS] make 'video' and 'videoplus' support border radius

- android/playground/app/src/main/java/com/alibaba/weex/WXPageActivity.java
- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridge.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
- android/sdk/src/main/java/com/taobao/weex/performance/WXInstanceApm.java
- android/sdk/src/main/java/com/taobao/weex/performance/WXInstanceExceptionRecord.java
- android/sdk/src/main/java/com/taobao/weex/ui/action/GraphicActionCreateBody.java
- android/sdk/src/main/java/com/taobao/weex/ui/action/GraphicActionCreateFinish.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXEmbed.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXImage.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXVContainer.java
- android/sdk/src/main/java/com/taobao/weex/utils/WXExceptionUtils.java
- stage
- fix  loadbundle  
- add createfinish
- properties
- add bundleurl 
- add bundletype 
- add embedcount,
- fix embedtype
> [WEEX-578][Android] edit performance point

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
[WEEX-580][Android]view key is not unique, RecycleList data repeat render not right,
> [WEEX-580][Android]view key is not unique, RecycleList data repeat render not right,

- ios/playground/WeexDemo/extend/handler/WXApmImpl.m
- ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.m
- ios/sdk/WeexSDK/Sources/Component/WXEmbedComponent.m
- ios/sdk/WeexSDK/Sources/Component/WXImageComponent.m
- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance_performance.m
- ios/sdk/WeexSDK/Sources/Module/WXTimerModule.m
- ios/sdk/WeexSDK/Sources/Performance/WXApmForInstance.h
- ios/sdk/WeexSDK/Sources/Performance/WXInstanceApm.m
- ios/sdk/WeexSDK/Sources/Utility/WXUtility.h
- ios/sdk/WeexSDK/Sources/Utility/WXUtility.m
- add fields for monitor
- fix playground crash ,(write dic on multithread case)
>  [WEEX-583][iOS] add fields for monitor

- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
- android/sdk/src/main/java/com/taobao/weex/performance/WXInstanceApm.java
- android/sdk/src/main/java/com/taobao/weex/performance/WXInstanceExceptionRecord.java
- android/sdk/src/main/java/com/taobao/weex/ui/action/GraphicActionCreateFinish.java
- android/sdk/src/main/java/com/taobao/weex/utils/WXExceptionUtils.java
> [WEEX-588][Android] fix too much msg when record error/stage

- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
- android/sdk/src/main/java/com/taobao/weex/performance/WXInstanceApm.java
- android/sdk/src/main/java/com/taobao/weex/ui/action/GraphicActionMoveElement.java
- android/sdk/src/main/java/com/taobao/weex/ui/action/GraphicActionRemoveElement.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXImage.java
- android/sdk/src/main/java/com/taobao/weex/utils/WXExceptionUtils.java
- fix interaction logic
- ignore rm op
- ignore move op
- ignore videoplus add op  
- fix repeat record img url  
- support default url when commit exception  
- add init time of sdk when report exception  
- if pagename is empty ,use activityName
> [WEEX-591][Android] fix interaction logic

- android/sdk/src/main/java/com/taobao/weex/performance/WXInstanceApm.java
- android/sdk/src/main/java/com/taobao/weex/performance/WXInstanceExceptionRecord.java
- android/sdk/src/main/java/com/taobao/weex/ui/action/GraphicActionCreateBody.java
improvement apm monitor
- limit useTime of instance when check is empty
- report first InteractionView render time
> [WEEX-595][Android]improvement apm monitor

- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance_performance.m
- ios/sdk/WeexSDK/Sources/Monitor/WXExceptionUtils.m
> [WEEX-592][iOS] fix dic for-each read crash

- ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.m
> [iOS] Avoid exceptionHandler be invoked by self and cause stackoverflow.

- ios/sdk/WeexSDK/Sources/Component/WXImageComponent.m
fix image can not show correct borderRadius
> [WEEX-593][iOS]image can not show correct borderRadius

- ios/sdk/WeexSDK/Sources/Performance/WXInstanceApm.m
> [WEEX-599][iOS] add apm record isEnd flag

- android/sdk/src/main/java/com/taobao/weex/ui/component/binding/AsynLayoutTask.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/template/WXRecyclerTemplateList.java
[WEEX-586][Android] add synchronized for recycle list template layout
> [WEEX-586][Android] add synchronized for recycle list template layout

- ios/sdk/WeexSDK/Sources/Component/WXEditComponent.m
> [iOS] Fix on iOS9, text cannot be deleted when exceeds maxLength.

- android/sdk/build.gradle
- scripts/build_from_source.sh
- scripts/generate_apache_release.sh
Fix build problem of apache release by removing gradle wrapper.
> * [Android] Fix build problem of apache release

- ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.mm
> [iOS] Add page stop event and custom pageSize ability to Scroller

- ios/sdk/WeexSDK.xcodeproj/project.pbxproj
- ios/sdk/WeexSDK/Sources/Component/WXImageComponent.m
- ios/sdk/WeexSDK/Sources/Engine/WXSDKError.h
- ios/sdk/WeexSDK/Sources/Engine/WXSDKError.m
- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance_performance.m
- ios/sdk/WeexSDK/Sources/Monitor/WXAnalyzerCenter.m
- ios/sdk/WeexSDK/Sources/Monitor/WXExceptionUtils.m
- ios/sdk/WeexSDK/Sources/Performance/WXApmForInstance.h
- ios/sdk/WeexSDK/Sources/Performance/WXApmForInstance.m
* [iOS] rename WXInstanceApm.m -> WXApmForInstance.m
* [iOS] img size && write screen && monitor download faild
* [iOS] emptyscreen check,bad case fix (destroy but js not excute)
* [iOS] request type add
> [WEEX-607][iOS] [weex monitor improvement

- ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.m
- ios/sdk/WeexSDK/Sources/Component/WXEmbedComponent.m
- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance_performance.m
- ios/sdk/WeexSDK/Sources/Monitor/WXExceptionUtils.m
- ios/sdk/WeexSDK/Sources/Performance/WXApmForInstance.m
* [iOS] add instance id info  when exec in globalContext `WXBridgeContext.m`
* [iOS] interactionTime should not calculate rootcomponent
> [WEEX-609][iOS]apm monitor logic modify

- android/sdk/src/main/java/com/taobao/weex/WeexFrameRateControl.java
Fix Crash due to unsatisfiedLinked, downgrade to h5 if unsatisfiedLinked error happened
> * [Android] Downgrade to h5 if unsatisfiedLinked error happened

- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
- android/sdk/src/main/java/com/taobao/weex/performance/WXInstanceApm.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXImage.java
* [Android] ignore the count down 10 view for interaction time calculate
* [Android] modify imageSize logic
* [Android] fix origin fsRender time ,and newFsRenderTime
> [WEEX-614][Android] apm monitor logic fix

- android/sdk/src/main/java/com/taobao/weex/WeexFrameRateControl.java
* [Android] Stop sync if exception occurs
(cherry picked from commit 139c0bd)
> * [Android] Stop sync if exception occurs

- ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.mm
- ios/sdk/WeexSDK/Sources/Layout/WXComponent+Layout.mm
- ios/sdk/WeexSDK/Sources/Model/WXComponent.h
- ios/sdk/WeexSDK/Sources/View/WXComponent+ViewManagement.mm
> [Core] Refactor. Adapt for scroller nested in scroller.

- ios/sdk/WeexSDK/Sources/Bridge/WXCoreBridge.mm
- ios/sdk/WeexSDK/Sources/Layout/WXComponent+Layout.h
- ios/sdk/WeexSDK/Sources/Layout/WXComponent+Layout.mm
- ios/sdk/WeexSDK/Sources/Model/WXComponent.mm
> [Core] Refactor. Fix memory leak and border pixel scale.

- ios/sdk/WeexSDK/Sources/Component/WXComponent_internal.h
- ios/sdk/WeexSDK/Sources/Display/WXComponent+Display.m
- ios/sdk/WeexSDK/Sources/Model/WXComponent.mm
Now,scroller support borderRadius
you can try demo here:http://dotwe.org/vue/f6c6f96361e20fce021d52bb6b89b3ac
also,you can try demo:http://rax.alibaba-inc.com/playground/9fffa56f-0c61-40df-a147-3602aa0541ca
> [WEEX-616][iOS] scroller support borderRadius

- ios/sdk/WeexSDK/Sources/Component/RecycleList/WXRecycleListComponent.mm
- ios/sdk/WeexSDK/Sources/Component/RecycleList/WXRecycleListUpdateManager.m
- ios/sdk/WeexSDK/Sources/Utility/WXDiffUtil.h
- ios/sdk/WeexSDK/Sources/Utility/WXDiffUtil.m
This pr is about fixing some bugs of recycle list.
- recycle list may splash when push data.
- recycle list can not show list length.
- ...
> [WEEX-585][iOS] recycle list bugfix

- ios/sdk/WeexSDK.xcodeproj/project.pbxproj
- ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.m
- ios/sdk/WeexSDK/Sources/Engine/WXSDKEngine.m
- ios/sdk/WeexSDK/Sources/Handler/WXJSFrameworkLoadDefaultImpl.h
- ios/sdk/WeexSDK/Sources/Handler/WXJSFrameworkLoadDefaultImpl.m
- ios/sdk/WeexSDK/Sources/Protocol/WXApmProtocol.h
- ios/sdk/WeexSDK/Sources/Protocol/WXJSFrameworkLoadProtocol.h
- ios/sdk/WeexSDK/Sources/WeexSDK.h
hotpatch jsframework && support JSFrameworkLoadProtocol
> [WEEX-625][iOS] hotpatch jsframework && support JSFrameworkLoadProtocol

- ios/sdk/WeexSDK.xcodeproj/project.pbxproj
- ios/sdk/WeexSDK/Sources/Utility/WXDefine.h
- ios/sdk/WeexSDK/Sources/Utility/WXVersion.h
- ios/sdk/WeexSDK/Sources/Utility/WXVersion.m
- ios/sdk/buildScripts.sh
> [iOS] Generate build time and time stamp when build.

- ios/sdk/WeexSDK/Sources/Component/WXImageComponent.m
> [iOS] Pass pageURL to external image loader.

- ios/sdk/WeexSDK/Sources/Model/WXComponent_performance.h
- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance_performance.m
- ios/sdk/WeexSDK/Sources/Performance/WXApmForInstance.h
- ios/sdk/WeexSDK/Sources/Performance/WXApmForInstance.m
-  before render,check pagename is nil or "",if yes, set pagename order  url -> vcname -> "unKnowSet"
- revert interaction code (revert ignore countDown top10 view)
> [WEEX-620][iOS] pageName check and render_error report modify

- ios/sdk/WeexSDK/Sources/Bridge/WXCoreBridge.h
- ios/sdk/WeexSDK/Sources/Bridge/WXCoreBridge.mm
- ios/sdk/WeexSDK/Sources/Layout/WXComponent+Layout.mm
- weex_core/Source/core/render/page/render_page.h
> [iOS] Remove object from ref map after delete.

- ios/sdk/WeexSDK.xcodeproj/project.pbxproj
- weex_core/Source/core/render/node/render_document.cpp
- weex_core/Source/core/render/page/render_page.cpp
> [Core] Build error on iOS.

- ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.m
- ios/sdk/WeexSDK/Sources/Bridge/WXCoreBridge.mm
- ios/sdk/WeexSDK/Sources/Component/WXCellComponent.mm
- ios/sdk/WeexSDK/Sources/Component/WXComponent_internal.h
- ios/sdk/WeexSDK/Sources/Manager/WXComponentManager.mm
- ios/sdk/WeexSDK/Sources/Model/WXComponent.mm
- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
- ios/sdk/WeexSDK/Sources/Module/WXTransition.h
- ios/sdk/WeexSDK/Sources/Module/WXTransition.mm
- ios/sdk/WeexSDK/Sources/Utility/WXUtility.h
- ios/sdk/WeexSDK/Sources/Utility/WXUtility.m
- weex_core/Source/core/render/node/render_mask.cpp
> Merge 0927 bugfixes

- ios/sdk/WeexSDK.xcodeproj/project.pbxproj
> [iOS] Project fix, remove invalid files.

- ios/sdk/WeexSDK/Sources/Component/RecycleList/WXCellSlotComponent.mm
- ios/sdk/WeexSDK/Sources/Component/RecycleList/WXComponent+DataBinding.mm
- ios/sdk/WeexSDK/Sources/Component/WXCellComponent.mm
- ios/sdk/WeexSDK/Sources/Component/WXComponent_internal.h
- ios/sdk/WeexSDK/Sources/Component/WXHeaderComponent.mm
- ios/sdk/WeexSDK/Sources/Component/WXListComponent.mm
- ios/sdk/WeexSDK/Sources/Model/WXComponent.mm
- ios/sdk/WeexSDK/Sources/View/WXComponent+ViewManagement.mm
> Fix div in list which cause weexcore render objects not ordered.

- weex_core/Source/android/base/jni/android_jni.cpp
https://issues.apache.org/jira/browse/WEEX-638
[WEEX-638][Android] fix attacheCurrentThread crash
fix attacheCurrentThread crash
Bug: WEEX-638
> [WEEX-638][Android] fix attacheCurrentThread crash

- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
https://issues.apache.org/jira/browse/WEEX-640
degrade to h5 If create instance error
> degrade to h5 If create instance error

- ios/sdk/WeexSDK/Sources/Handler/WXURLRewriteDefaultImpl.m
- ios/sdk/WeexSDK/Sources/Module/WXStreamModule.m
> [iOS] Protect stream module arguments.

- ios/sdk/WeexSDK/Sources/Component/WXEditComponent.mm
> [iOS] Add keyboardSize in "keyboard" event.

- ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.m
- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
- ios/sdk/WeexSDK/Sources/Performance/WXApmForInstance.h
- ios/sdk/WeexSDK/Sources/Performance/WXApmForInstance.m
- fix wxPageRatio not report  
- add instanceId to weexContext ,if fucn `createInstanceContext` failure ，then we will know which instance has problem
>  [WEEX-642][iOS] fix wxpageRatio not report  && report createInstaceContext failed info

- ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.m
- ios/sdk/WeexSDK/Sources/Utility/WXUtility.h
- ios/sdk/WeexSDK/Sources/Utility/WXUtility.m
> [iOS] fix rax object leak.

- ios/sdk/WeexSDK/Sources/Component/WXVideoComponent.m
videocomponent support hide controls
you can try demo here: http://rax.alibaba-inc.com/playground/3f449805-49d7-4b80-ae92-e8c34039e521
> [WEEX-645][iOS] videocomponent support hide controls

- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
add `isBundleRequest` flag to requestParams when downLoadBundle
> [WEEX-649][Android] add `isBundleRequest` flag to requestParams when downLoadBundle

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXScroller.java
There are two problem fixed in this situation.
1. When a scroller is shown by sliding up a list, appear events of the item in scroller can not be fired. This is caused by the scroller component in Android only fires appear / disappear event when scrolling exclude the time that scroller is attached / detached to window. 
2. The logic that check a view is visible in scroller component is defective, because in the time of call check method, the view may not in screen but it will show after this tick.
> [WEEX-650][Android] fix appear & disappear problem of items in scroller

- weex_core/Source/core/layout/layout.cpp
https://alibaba.github.io/rax/jsplayground/e58e828f-83b4-4607-812e-4f6afe31bdd4
> * [Android] Fix text layout problem

- weex_core/Source/core/layout/layout.cpp
- weex_core/Source/core/layout/layout.h
Fix layout problem for item with position:absolute style and align-item:center in its parent.
http://dotwe.org/vue/016485161d20f06bf1060af9ca66db4b
> * [Android] Fix layout problem for position:absolute

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXText.java
Refresh the text node when iconfont download finished.
> * [Android] Fix iconfont refresh problem

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXImage.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/WXImageView.java
Fix the problem that changing image.resize in JS doesn't work
http://dotwe.org/vue/a49cd5f19d332e822ffa32c07ae96a71
> * [Android] Fix image.resize problem

- android/playground/app/build.gradle
Reverts apache/incubator-weex#1708
> Revert "* [android] Update devtool version"

- ios/sdk/WeexSDK/Sources/Component/WXTransform.m
Failure of parsing transform parameter when in third-party
> [WEEX-484][iOS] Failure of parsing transform parameter when in third-party

- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
> [iOS] add userinfo to bundle loader failed error message.

- ios/sdk/WeexSDK/Sources/Component/WXEditComponent.mm
fix input component can not limit words number correctly.
you can see demo here:http://dotwe.org/vue/96be65e58e982a719d412f8888a0609b
> [WEEX-639][iOS] fix input component can not limit words number correctly

- ios/sdk/WeexSDK/Sources/Component/WXVideoComponent.m
fix video component show control's bug.
> [iOS] fix video component show control's bug

- ios/sdk/WeexSDK/Sources/Utility/WXThreadSafeMutableArray.h
- ios/sdk/WeexSDK/Sources/Utility/WXThreadSafeMutableArray.m
- ios/sdk/WeexSDK/Sources/Utility/WXThreadSafeMutableDictionary.h
- ios/sdk/WeexSDK/Sources/Utility/WXThreadSafeMutableDictionary.m
> [iOS] Restore recursive lock and add some comments.

- ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.mm
demo:http://dotwe.org/vue/6722f649532342b45fea5e44a2b93299
> [iOS] fix scrollEnd can not get offset

- weex_core/Source/core/render/page/render_page.cpp
> [iOS] Trigger vsync on iOS in every batch.

- ios/sdk/WeexSDK/Sources/Engine/WXSDKEngine.h
- ios/sdk/WeexSDK/Sources/Engine/WXSDKEngine.m
- ios/sdk/WeexSDK/Sources/Manager/WXBridgeManager.h
- ios/sdk/WeexSDK/Sources/Manager/WXBridgeManager.m
> [iOS] Add completion callback for registerService

- android/sdk/build.gradle
Move testCoverageEnabled = true config to debug mode
> [android] move testCoverageEnabled = true config to debug mode

- android/sdk/src/main/java/com/taobao/weex/ui/component/list/WXListComponent.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/template/WXRecyclerTemplateList.java
Update 0 zero column report as column is not used when mLayoutType == TYPE_LINEAR_LAYOUT
> * [Android] Update 0 zero column report

- ios/sdk/WeexSDK/Sources/Component/WXCycleSliderComponent.mm
- ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.mm
- ios/sdk/WeexSDK/Sources/Engine/WXSDKEngine.h
- ios/sdk/WeexSDK/Sources/Engine/WXSDKEngine.m
- ios/sdk/WeexSDK/Sources/Layout/WXComponent+Layout.h
- ios/sdk/WeexSDK/Sources/Layout/WXComponent+Layout.mm
- ios/sdk/WeexSDK/Sources/Manager/WXBridgeManager.h
- ios/sdk/WeexSDK/Sources/Manager/WXBridgeManager.m
- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
- ios/sdk/WeexSDK/Sources/Module/WXAnimationModule.m
- ios/sdk/WeexSDK/Sources/Utility/WXThreadSafeMutableDictionary.m
- weex_core/Source/core/layout/flex_enum.h
- weex_core/Source/core/layout/layout.h
- weex_core/Source/core/render/page/render_page.cpp
> Fix rc 0.20

- ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.m
- ios/sdk/WeexSDK/Sources/Bridge/WXCoreBridge.mm
> [iOS] Also write js error log to monitor.

- ios/sdk/WeexSDK/Sources/Component/WXRichText.mm
> [iOS] Protect invalid rich-text data.

- android/sdk/src/main/java/com/taobao/weex/common/WXErrorCode.java
errorCode type edit 
`-2013` is js exception
> [WEEX-668][Android] errorCode type edit (-2013 is a js exception)

- android/sdk/build.gradle
Fix the crash of Android weex Playground
> * [Android] Fix Jacoco crash

- ios/sdk/WeexSDK.xcodeproj/project.pbxproj
- ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.m
- ios/sdk/WeexSDK/Sources/Bridge/WXJSCoreBridge.h
- ios/sdk/WeexSDK/Sources/Bridge/WXJSCoreBridge.mm
- ios/sdk/WeexSDK/Sources/Engine/WXSDKEngine.m
- ios/sdk/WeexSDK/Sources/Manager/WXSDKManager.h
- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
> Fix multicontext recreate

- WeexSDK.podspec
> [iOS] Use libc++.

- ios/sdk/WeexSDK/Sources/Bridge/WXJSCoreBridge.mm
- ios/sdk/WeexSDK/Sources/Manager/WXBridgeManager.h
> [iOS] Release jscontext in bridge thread to avoid main thread deadlock.

- android/playground/app/src/main/java/com/alibaba/weex/WXPageActivity.java
Feature:
- support for hot updates under specified ports.
> [Android] support for hot updates under specified ports

- android/playground/app/src/main/java/com/alibaba/weex/WXPageActivity.java
Bugfix:
- fix WXpageActivity class on playground app.
> [Android] fix WXpageActivity class on playground app

- android/sdk/src/main/java/com/taobao/weex/el/parse/Parser.java
Bugfix： Parser.nextToken dot work
> [Android]  fix sdk Parser.nextToken malfunction

- android/playground/app/src/main/java/com/alibaba/weex/extend/adapter/WXInstanceApmAdapter.java
- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
- android/sdk/src/main/java/com/taobao/weex/performance/IWXApmMonitorAdapter.java
- android/sdk/src/main/java/com/taobao/weex/performance/WXInstanceApm.java
- android/sdk/src/main/java/com/taobao/weex/ui/action/GraphicActionAddElement.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/WXFrameLayout.java
- android/sdk/src/main/java/com/taobao/weex/utils/WXExceptionUtils.java
- determine if the element is on the screen (element edge)
- if component has "ignoreInteraction" attrs，componentTree will not calculate
- report pageName  (not url)
- every instance report one overlay exception at most
> * [Android] edit interaction logic && edit exception report logic

- android/playground/app/src/main/java/com/alibaba/weex/WXApplication.java
- android/playground/app/src/main/java/com/alibaba/weex/extend/adapter/WXAnalyzerDemoListener.java
- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
- android/sdk/src/main/java/com/taobao/weex/bridge/NativeInvokeHelper.java
- android/sdk/src/main/java/com/taobao/weex/bridge/SimpleJSCallback.java
- android/sdk/src/main/java/com/taobao/weex/performance/WXAnalyzerDataTransfer.java
- android/sdk/src/main/java/com/taobao/weex/performance/WXInstanceApm.java
- android/sdk/src/main/java/com/taobao/weex/ui/action/GraphicActionAddElement.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXImage.java
- weex_core/Source/core/config/core_environment.cpp
- weex_core/Source/core/config/core_environment.h
- weex_core/Source/core/render/page/render_page.cpp
- transfer peformance info to devtool
- show interactionView
- add log switch of jsengin/jsfm/weexcore ,to analyze interactionTime
- for large img，log url，size
> *[Android] update for weex dev-tool

- HOW-TO-BUILD.md
> Fixed minor grammatical errors and typos.

- android/commons/src/main/java/com/alibaba/weex/commons/adapter/BlurTool.java
- android/commons/src/main/java/com/alibaba/weex/commons/adapter/JSExceptionAdapter.java
- android/playground/app/src/main/java/com/alibaba/weex/extend/module/location/DefaultLocation.java
- android/sdk/src/main/java/com/taobao/weex/WXEnvironment.java
- android/sdk/src/main/java/com/taobao/weex/WXSDKEngine.java
- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
- android/sdk/src/main/java/com/taobao/weex/adapter/IWXUserTrackAdapter.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXText.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/template/WXRecyclerTemplateList.java
- android/sdk/src/main/java/com/taobao/weex/ui/module/WXModalUIModule.java
- android/sdk/src/main/java/com/taobao/weex/utils/TypefaceUtil.java
- android/sdk/src/main/java/com/taobao/weex/utils/WXSoInstallMgrSdk.java
- android/sdk/src/main/java/com/taobao/weex/utils/WXUtils.java
* try get debug flag from env params
* rm useless log rm
* try get debugflag from environment
* get cpu abi from Build.CPU_ABI;
> *[Android] weex performance optimization

- ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.m
- ios/sdk/WeexSDK/Sources/Bridge/WXJSCoreBridge.mm
move `extendCallNative` method from globalContext to instanceContext
> [WEEX-671][iOS] `extendCallNative` method move to instance jscontext

- ios/sdk/WeexSDK/Sources/Monitor/WXAnalyzerCenter.m
fix sdk build error :
add `ignored "-Wundeclared-selector"` pragma
> * [iOS] fix sdk build error, ignored "-Wundeclared-selector"

- weex_core/Source/core/layout/layout.cpp
fix weex_core crash point when call getLayoutDirectionFromPathNode, it just guess
> [weex_core] fix crash point just maybe 

- README.md
Use travis-ci badge instead of outdated circleci badge
> [doc]Use travis-ci badge instead of outdated circleci badge

- ios/sdk/WeexSDK/Sources/Utility/WXUtility.m
> [iOS] Fix md5 potential crash.

- HOW-TO-BUILD.md
> *[Android] update HOW-TO-BUILD for android build

- ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.m
- ios/sdk/WeexSDK/Sources/Manager/WXComponentManager.mm
- fix bundleTypeParse 
- modify ignoreInteraction flag parse
> * [iOS] fix bundleTypeParse && ignoreInteraction flag

- weex_core/Source/core/data_render/class_console.cc
- weex_core/Source/core/data_render/class_function.cc
- weex_core/Source/core/data_render/class_regex.cc
> [iOS] Fix header misuse.

- ios/sdk/WeexSDK/Sources/Component/WXEditComponent.mm
> [iOS] Add upriseOffset for edit component.

- ios/sdk/WeexSDK/Sources/Component/WXListComponent.mm
> [iOS] Avoid unnecessary invocation.

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXScroller.java
Make scroller support on touch Event
> Make scroller support on touch Event

- android/sdk/src/main/java/com/taobao/weex/ui/action/GraphicActionAddElement.java
- ignore fixed element for interactionTime
> * [Android] modify interactionTime algorithm ，ignore fixd element

- ios/sdk/WeexSDK/Sources/Model/WXComponent.mm
- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance_performance.m
- ignore fixed element for interactionTime
- test case：http://dotwe.org/vue/5255b5a9fd86ca58877f06f0abeda1d8
> * [iOS]ignore fixed element for interactionTime

- ios/sdk/WeexSDK/Sources/Manager/WXBridgeManager.h
> [iOS] Public WXPerformBlockSyncOnBridgeThread.

- android/commons/build.gradle
- android/playground/app/build.gradle
- android/sdk/build.gradle
Use the following command to publish to jCenter
./gradlew install -PbintrayUser=xxxx -PbintrayApiKey=yyyyy bintray
xxxx and yyyyy are the user name and key
> * [Android] Update gradle for jCenter publish.

- android/sdk/build.gradle
- gradle nullPoint fix for ndk.dir check
- issue: https://github.com/apache/incubator-weex/issues/1907
> * [Android] (gradle build) nullPoint fix for ndk.dir check

- ios/playground/WeexDemo.xcodeproj/project.pbxproj
- ios/playground/WeexDemo/AppDelegate.m
- ios/playground/WeexDemo/Websocket/SRWebSocket+Weex.h
- ios/playground/WeexDemo/Websocket/SRWebSocket+Weex.m
- ios/playground/WeexDemo/Websocket/WXWebSocketDefaultImpl.h
- ios/playground/WeexDemo/Websocket/WXWebSocketDefaultImpl.m
This pull request add WebSocket' implementation in playground's project.
Note, you need change your code to http://dotwe.org/vue/a235218427ab3a2a918c3fe16ec19b51.
You need change
`websocket.onmessage = (e)=>{
this.onmessage = e.data;
};
`
to code like this
`websocket.onmessage((e) => {
this.onmessage = e.data;
});
`
> [iOS] Add WebSocket' implementation in playground's project.

- ios/sdk/WeexSDK/Sources/Component/WXCycleSliderComponent.mm
- ios/sdk/WeexSDK/Sources/Model/WXComponent.mm
- ios/sdk/WeexSDK/Sources/View/WXComponent+PseudoClassManagement.h
- ios/sdk/WeexSDK/Sources/View/WXComponent+PseudoClassManagement.m
> [iOS] [BugFix] Fix remove active pseudo class doesn't work.

- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
- android/sdk/src/main/java/com/taobao/weex/performance/WXInstanceApm.java
- android/sdk/src/main/java/com/taobao/weex/utils/WXExceptionUtils.java
record dataLength received from network.
if `time out exception`, could help us fix issue quickly.
> * [Android] record dataLength received from network.

- ios/sdk/WeexSDK/Sources/Display/WXComponent+Display.m
Fix bug with borderRadius's calculation.
You can try demo here:http://dotwe.org/vue/0d11e4387ad4fee6a267d652f96896cd
> [iOS] Fix bug with borderRadius's calculation.

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
public `OnFocusChangeListener`
> * [Android] cp commit  a06dca013987869184bb8312904a53f8b04c194f:

- android/build.gradle
- android/sdk/build.gradle
add aliyun repo , for some net issue
> [Android] add aliyun repo in gradle

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXImage.java
[WEEX][Android] Fix Image Bright When ReBind The Same Image In Some Image Framework
> [WEEX][Android] Fix Image Bright When ReBind The Same Image In Some Image Framework

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXEmbed.java
[WEEX][Android]  WXEmbed ViewAppear  DisAppear Event  Twice
> [WEEX][Android]  WXEmbed ViewAppear  DisAppear Event  Twice

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXScroller.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/helper/ScrollStartEndHelper.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/template/WXRecyclerTemplateList.java
[WEEX][Android] Fix Scroll End Be Fired When ScrollEnd But Touch Not End
http://rax.alibaba-inc.com/playground/7f76cc7b-4486-4d08-bfba-42824359742f
> [WEEX][Android] Fix Scroll End Be Fired When ScrollEnd But Touch Not End

- ios/sdk/WeexSDK/Sources/Component/WXEditComponent.mm
> [iOS] WXEditComponent provides keyboardSize with front-end px value.

- ios/playground/Podfile
- ios/playground/WeexDemo/AppDelegate.m
[WEEX-674] [iOS] add bindingx for playground
> [iOS] add bindingx for playground

- android/sdk/src/main/java/com/taobao/weex/WXSDKEngine.java
- android/sdk/src/main/java/com/taobao/weex/utils/WXViewUtils.java
- adapter screen height for full screen 
- adapter miui  fullscreen switch (`force_fsg_nav_bar`)
> * [Android] adapter screen height for full screen

- ios/sdk/WeexSDK/Sources/Component/WXImageComponent.m
- ios/sdk/WeexSDK/Sources/Component/WXTextComponent.h
- ios/sdk/WeexSDK/Sources/Component/WXTextComponent.mm
- ios/sdk/WeexSDK/Sources/Model/WXComponent.h
- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
- ios/sdk/WeexSDK/Sources/Utility/WXUtility.h
- ios/sdk/WeexSDK/Sources/Utility/WXUtility.m
> [iOS] Remove unused options.

- WeexSDK.podspec
- ios/playground/Podfile
- ios/playground/WeexDemo/WXDemoViewController.m
> [iOS] Remove old tracing system. Adapt for playground.

- android/sdk/src/main/java/com/taobao/weex/performance/WXInstanceApm.java
send performane info to js delay 8s
> * [Android] feature :send performane info to js delay 8s

- android/sdk/src/main/java/com/taobao/weex/common/WXPerformance.java
- android/sdk/src/main/java/com/taobao/weex/performance/WXInstanceApm.java
build fix for https://github.com/apache/incubator-weex/pull/2000
> * [Android] build fix

- WeexSDK.podspec
- ios/sdk/WeexSDK/Sources/Module/WXWebSocketModule.m
- ios/sdk/WeexSDK/Sources/Performance/WXApmForInstance.m
> [iOS] Protect websocket url argument.

- weex_core/release.sh
> * [Android] edit build release.sh for cp jss so

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXDiv.java
> [Bug Fixing] avoid crash when getFlatUIContext() return null

- ios/sdk/WeexSDK/Sources/Component/WXComponent_internal.h
- ios/sdk/WeexSDK/Sources/Events/WXComponent+Events.m
- ios/sdk/WeexSDK/Sources/Model/WXComponent.mm
Add support for custom event with stoppropagation.
you can use demo here:http://dotwe.org/vue/0f59a166ba038079049541a49cf4d548
> * [iOS] Add support for custom event with stoppropagation

- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
Fix fireEvent problem in data render when data or domchange is null
> * [Android] Fix fireEvent problem in data render

- weex_core/Source/android/bridge/script_bridge_in_multi_process.cpp
> Remove Dup Exception report

- android/sdk/src/main/java/com/taobao/weex/bridge/NativeInvokeHelper.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXModuleManager.java
* [Android] rm unnecessary exception，just loge
* [Android] fix multithread crash，when instance destroy in ui，but task still post from jsThread
> [Android] fix multithread task crash after instance crash && rm unnecessary exception

- weex_core/Source/android/jsengine/weex_jsc_utils.cpp
- weex_core/Source/android/jsengine/wson/wson_jsc.cpp
Cherry-pick file of weex_jsc_utils.cpp, won_jsc.cpp in commit 1058b5c2120bb965ffdb554a96bdcb5a1d7a5421 in weex_v8core repos to weex_sdk
> * [Android] Fix the problem of updateComponentData in jsc for eagle

- ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.mm
Fixed iOS scroller crash ，because I forget change the scroll implement at last my pr。
> [ios] fixed layout.cpp crash in scrollercomponent

- android/sdk/src/main/java/com/taobao/weex/ui/component/helper/ScrollStartEndHelper.java
try to fix js exception: scroll event.xxx is undefined
> * [Android] try to fix js exception: scroll event.xxx is undefined

- android/sdk/src/main/java/com/taobao/weex/ui/animation/TransformParser.java
[WEEX][Android] Fix Illegak Input Parse Exception
> [WEEX][Android] Fix Illegak Input Parse Exception

- ios/sdk/WeexSDK/Sources/Utility/WXUtility.h
> [iOS] Fix bridge method with BOOL argument on 32bit devices.

- android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
[WEEX][Android] When LoadMore Offset Is Float, Exception Happen LOADMORE Function Loss
> [WEEX][Android] When LoadMore Offset Is Float, Exception Happen LOADMORE Function Loss

- android/sdk/src/main/java/com/taobao/weex/ui/WXComponentRegistry.java
- android/sdk/src/main/java/com/taobao/weex/ui/config/AutoScanConfigRegister.java
[WEEX][Android] Remove Unused PreLoad Statics Method Count Logical
> [WEEX][Android] Remove Unused PreLoad Statics Method Count Logical

- android/sdk/src/main/java/com/taobao/weex/WXSDKEngine.java
- android/sdk/src/main/java/com/taobao/weex/utils/WXViewUtils.java
rollback pr https://github.com/apache/incubator-weex/pull/1981
bug： some case view is hidden  by navigatorbar
> Revert "* [Android] adapter screen height for full screen (#1981)"

- ios/sdk/WeexSDK/Sources/Bridge/WXCoreBridge.h
- ios/sdk/WeexSDK/Sources/Bridge/WXCoreBridge.mm
- weex_core/Source/core/bridge/platform/core_side_in_platform.cpp
- weex_core/Source/core/render/manager/render_manager.cpp
> [iOS] Fix setViewportWidth on iOS.

- android/sdk/src/main/java/com/taobao/weex/WXSDKEngine.java
reload js service when reload weexSDKEngine
> reload js service when reload weexSDKEngine

- android/sdk/src/main/java/com/taobao/weex/WXEnvironment.java
- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
每次打开页面都检查一遍是否开启多 jsEngine 线程的 Orange 的开关, 如果发生变化则重启 jsframework.
> Restart jsframework if jsEngineMultiThread switch changed

- android/sdk/src/main/java/com/taobao/weex/appfram/storage/DefaultWXStorage.java
try to fix RejectedExecutionException on DefaultWXStorage.
> [Android] try to fix RejectedExecutionException on DefaultWXStorage.

- CONTRIBUTING.md
Update contributing.md which is a copy of how-to-contribute.md in https://github.com/apache/incubator-weex-site/pull/318
> * [Doc] Update contributing.md

- ios/sdk/WeexSDK/Sources/Component/WXRichText.mm
> [iOS] Fix richtext multi-thread issue.

- ios/sdk/WeexSDK/Sources/Handler/WXNavigationDefaultImpl.m
> [iOS] navigator module argument adapt.

- ios/sdk/WeexSDK.xcodeproj/project.pbxproj
修复iOS WeexSDK-Dynamic WXRecyclerComponent.h 头文件没有public
> [iOS] Fixed WeexSDK-Dynamic WXRecyclerComponent.h to public

- ios/sdk/WeexSDK.xcodeproj/project.pbxproj
- ios/sdk/WeexSDK/Sources/Utility/WXVersion.m
- weex_core/Source/include/WeexApiHeader.h
- weex_core/Source/include/WeexApiValue.h
> [Core] Separate weex api result type from WeexApiHeader

- weex_core/Source/include/WeexApiValue.h
> [Core] Add missing header so that each file can compile.

- weex_core/Source/include/WeexApiValue.h
> [Core] Add default constructors for VALUE_WITH_TYPE

- ios/sdk/WeexSDK/Sources/Utility/WXConvertUtility.mm
> [iOS] Add detect object recursion debug code.

- android/sdk/src/main/java/com/taobao/weex/dom/transition/WXTransition.java
- weex_core/Source/android/bridge/platform/android_side.cpp
[WEEX][Weex-Core]  Fix CSS Transition Not Works Bug And Adapter For Rax Wrong Duration Unit
> [WEEX][Weex-Core]  Fix CSS Transition Not Works Bug And Adapter For Rax Wrong Duration Unit

- android/sdk/src/main/java/com/taobao/weex/WXSDKManager.java
- android/sdk/src/main/java/com/taobao/weex/adapter/IWXConfigAdapter.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
- android/sdk/src/main/java/com/taobao/weex/performance/WXInstanceApm.java
- android/sdk/src/main/java/com/taobao/weex/utils/WXExceptionUtils.java
- add ConfigAdapter for get config easily
- check repeat report (can't get module when scroll case )
- report bundleType value modiy "Others"->"other" same as iOS
> [Android] check dup exception report for every instance

- ios/sdk/WeexSDK/Sources/Engine/WXSDKEngine.m
- ios/sdk/WeexSDK/Sources/Events/WXComponent+Events.m
- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
> [iOS] Fix crashes.

- android/sdk/src/main/java/com/taobao/weex/bridge/WXServiceManager.java
fix ConcurrentModificationException when reload jsEngine
> fix ConcurrentModificationException

- ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.mm
* feature: Add "isDragging" property to scroll event of a list component.
* doc pr: apache/incubator-weex-site#361
> [iOS] Add "isDragging" property to scroll event of a list component.

- ios/sdk/WeexSDK/Sources/Bridge/WXCoreBridge.h
- ios/sdk/WeexSDK/Sources/Bridge/WXCoreBridge.mm
- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.h
- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
* feature: used on landscape started apps.
> [iOS] Support change device width and height by external interface.

- ios/sdk/WeexSDK/Sources/Component/WXListComponent.mm
- ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.mm
* demo: http://dotwe.org/vue/aa1af34e5fc745c0f1520e346904682a
* [] Demo
* [] Document
> [iOS] Ignore scroll action if contentSize smaller than scroller frame.

- android/sdk/src/main/java/com/taobao/weex/common/Constants.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/template/WXRecyclerTemplateList.java
* feature: Add "isDragging" property to scroll event of a list component.
* doc pr: https://github.com/apache/incubator-weex-site/pull/361
> [Android] Add "isDragging" property to scroll event of a list component.

- android/sdk/src/main/java/com/taobao/weex/ui/WXRenderManager.java
* bugfix: Fix blank page when JS exception raised before batch end.
* issue: https://github.com/apache/incubator-weex/issues/2253
> [Android] Fix blank page when JS exception raised before batch end.

- android/sdk/src/main/java/com/taobao/weex/WXEnvironment.java
- android/sdk/src/main/java/com/taobao/weex/utils/WXUtils.java
[WEEX][Weex-Android] Supported Pad Render Mode For Big Screen
> [WEEX][Weex-Android] Supported Pad Render Mode For Big Screen

- android/sdk/src/main/java/com/taobao/weex/ui/component/richtext/node/ANode.java
… richtext component.
* feature: If a span is clicked which is in an a-label of a richtext component, an itemclick event will be fired.
* demo: http://editor.weex.io/p/sunshl/Contribute/commit/b21e1133830b48767c6d00d712e415b2
* doc pr: apache/incubator-weex-site#362
> [Android]Fire event when span within an a-label is clicked.

- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
> [iOS] Add bundle response url in options dictionary.

- android/build.gradle
- android/sdk/build.gradle
Update build.gradle to support external build scripts
> * Android update build.gradle

- android/sdk/build.gradle
Delete libweexcore.so and libweexjss.so only if transformNativeLibsWithStripDebugSymbolForRelease is triggered.
> * [Android] Update build.gradle

- ios/sdk/WeexSDK/Sources/Display/WXComponent+Display.m
> [iOS] Fix background is set to transparent when no border.

- ios/sdk/WeexSDK/Sources/Events/WXComponent+Events.m
> [iOS] Avoid conflict between Pan & Tap gestures.

- weex_core/Source/core/layout/layout.cpp
> Fix potential crash of layout node.

- WeexSDK.podspec
- ios/sdk/WeexSDK.xcodeproj/project.pbxproj
- ios/sdk/WeexSDK/Sources/Utility/WXVersion.m
- ios/sdk/WeexSDK/Sources/WeexSDK.h
> Public refresh

- android/sdk/src/main/java/com/taobao/weex/WXEnvironment.java
[WEEX][Weex-Android]  Android Q Weex System Version Adapter
> [WEEX][Weex-Android]  Android Q Weex System Version Adapter

- weex_core/Source/base/core_constants.h
- weex_core/Source/core/common/view_utils.h
> [Core] Remove C++ static initializers.

- ios/sdk/WeexSDK/Sources/Bridge/WXCoreBridge.h
- ios/sdk/WeexSDK/Sources/Bridge/WXCoreBridge.mm
- weex_core/Source/core/bridge/eagle_bridge.cpp
- weex_core/Source/core/bridge/eagle_bridge.h
- weex_core/Source/core/bridge/platform_bridge.h
fix ios call native component method before the plugin register
> fix ios call native component method before the plugin register

- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
https://github.com/apache/incubator-weex/projects/3
> [Android] remove unnecessary frameworkInit check in WXBridgeManager for data-render mode

- ios/sdk/WeexSDK/Sources/Manager/WXSDKManager.m
> Fix bug that +[WXSDKManager bridgeMgr] is not thread safe.

- android/sdk/src/main/java/com/taobao/weex/WXHttpListener.java
- android/sdk/src/main/java/com/taobao/weex/bridge/RequestHandler.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
- android/sdk/src/main/java/com/taobao/weex/common/WXErrorCode.java
check bundle_type and report error
iOS pr:https://github.com/apache/incubator-weex/pull/2420/files
> [Android] feature : check bundle_type and report error

- weex_core/Source/core/layout/layout.cpp
> [Core] Protect potential crash.

- android/sdk/src/main/java/com/taobao/weex/ui/action/GraphicActionAddElement.java
add option to ignore element time calculate
> [Android] add option to ignore element time calculate

- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance_performance.m
> [iOS] Fix not proper use of block of WXPerformance.

- ios/sdk/WeexSDK/Sources/Module/WXTransition.mm
> [iOS] 修正动画处理时的计算误差及计算逻辑问题。

- ios/sdk/WeexSDK/Sources/Component/WXTextComponent.mm
- ios/sdk/WeexSDK/Sources/Display/WXComponent+Display.m
> Fix text crash

- weex_core/Source/android/jsengine/bridge/script/script_side_in_queue.cpp
[WEEX][Weex-Android] Fix Compile Error
> [WEEX][Weex-Android] Fix Compile Error

- ios/sdk/WeexSDK/Sources/Component/WXTextComponent.mm
> [iOS] Wordwrap set to break by word by default.

- ios/sdk/WeexSDK/Sources/Component/WXTextComponent.mm
> Fix default wordwrap

- HOW-TO-BUILD.md
> Add Ninja build dep

- ios/sdk/WeexSDK/Sources/Component/WXEditComponent.mm
the issue:
https://github.com/apache/incubator-weex/issues/2380
> [iOS] fix input text show error when has a attribute of maxlength

- ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.m
issue:
https://github.com/apache/incubator-weex/issues/2356
> [iOS] WXCoreBridge install should run in main thread

- android/sdk/src/main/java/com/taobao/weex/utils/WXDeviceUtils.java
- android/sdk/src/main/java/com/taobao/weex/utils/WXViewUtils.java
[WEEX][Weex-Android] Add Supported For Multi Screen Render Supported, Exception Fix
> [WEEX][Weex-Android] Add Supported For Multi Screen Render Supported Exception Fix

- android/build.gradle
- android/sdk/build.gradle
- package.json
> Fix potential security vulnerable in android

- ios/sdk/WeexSDK.xcodeproj/project.pbxproj
- ios/sdk/WeexSDK/Sources/Bridge/WXCoreBridge.mm
- weex_core/Source/base/CMakeLists.txt
- weex_core/Source/base/log_defines.cpp
- weex_core/Source/base/log_defines.h
- weex_core/Source/core/bridge/log_bridge.h
- weex_core/Source/core/manager/weex_core_manager.h
> [Core] Add WeexCore log bridge.

- ios/sdk/WeexSDK/Sources/Bridge/WXComponentMethod.m
- ios/sdk/WeexSDK/Sources/Manager/WXComponentFactory.h
- ios/sdk/WeexSDK/Sources/Manager/WXComponentFactory.m
support component method call in background thread
> [IOS] support component method call in background thread

- android/playground/app/src/main/java/com/alibaba/weex/WXPageActivity.java
- android/playground/app/src/main/java/com/alibaba/weex/WXPreLoadManager.java
- android/playground/app/src/main/java_zxing/com/google/zxing/client/android/CaptureActivity.java
- android/sdk/src/main/java/com/taobao/weex/WXHttpListener.java
- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
- android/sdk/src/main/java/com/taobao/weex/performance/WXInstanceApm.java
- weex_core/Source/android/bridge/script/script_side_in_multi_process.cpp
- weex_core/Source/android/bridge/script/script_side_in_multi_process.h
- weex_core/Source/android/bridge/script/script_side_in_multi_so.cpp
- weex_core/Source/android/bridge/script/script_side_in_multi_so.h
- weex_core/Source/android/jsengine/bridge/script/script_bridge_in_multi_process.cpp
- weex_core/Source/android/jsengine/bridge/script/script_bridge_in_multi_so.cpp
- weex_core/Source/android/jsengine/bridge/script/script_bridge_in_multi_so.h
- weex_core/Source/android/jsengine/bridge/script/script_side_in_queue.cpp
- weex_core/Source/android/jsengine/bridge/script/script_side_in_queue.h
- weex_core/Source/android/jsengine/bridge/script/script_side_in_simple.cpp
- weex_core/Source/android/jsengine/bridge/script/script_side_in_simple.h
- weex_core/Source/android/jsengine/weex_runtime.cpp
- weex_core/Source/android/wrap/wx_bridge.cpp
- weex_core/Source/core/bridge/platform/core_side_in_platform.cpp
- weex_core/Source/core/bridge/platform/core_side_in_platform.h
- weex_core/Source/core/bridge/platform_bridge.h
- weex_core/Source/core/bridge/script_bridge.h
- weex_core/Source/include/WeexApiHeader.h
feature : 
1. supprot preDownLoad bundle
2. support preInitInstanceContext
performance : 200ms improve 
usage: add url  params 
- ` ?preDownLoad=true`
- or `?preInitInstance=vue/rax`
- or both of them `?preDownLoad=true&preInitInstance=vue/rax`
sample: 
- case: `http://editor.weex.io/compiled/8afdb78575e9cbbdf35d32d102843885/bundle.weex.js?preInitInstance=vue&preDownLoad=true`
- originurl: `http://editor.weex.io/compiled/8afdb78575e9cbbdf35d32d102843885/bundle.weex.js`
> [Android] support preinit && predonload mode

- ios/sdk/WeexSDK/Sources/Bridge/WXCoreBridge.mm
- weex_core/Source/base/log_defines.cpp
> Log update iOS compile error.

- ios/sdk/WeexSDK/Sources/Manager/WXSDKManager.m
> [iOS] Fix devtool unloading bridge manager.

- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
- ios/sdk/WeexSDK/Sources/Utility/WXUtility.h
- ios/sdk/WeexSDK/Sources/Utility/WXUtility.m
- ios/sdk/WeexSDK/Sources/View/WXComponent+ViewManagement.mm
- ios/sdk/WeexSDKTests/WXComponentTests.m
> [iOS] Set overflow to  hidden by default on iOS to conform to Android.

- ios/sdk/WeexSDK.xcodeproj/project.pbxproj
- ios/sdk/WeexSDK/Sources/Engine/WXSDKEngine.m
- ios/sdk/WeexSDK/Sources/Manager/WXComponentManager.mm
- ios/sdk/WeexSDK/Sources/Module/WXConsoleLogModule.h
- ios/sdk/WeexSDK/Sources/Module/WXConsoleLogModule.m
- ios/sdk/WeexSDK/Sources/Utility/WXLog.h
- ios/sdk/WeexSDK/Sources/Utility/WXLog.m
> Log scan switch

- ios/sdk/WeexSDK/Sources/Bridge/WXCoreBridge.mm
- ios/sdk/WeexSDK/Sources/Engine/WXSDKEngine.h
- ios/sdk/WeexSDK/Sources/Engine/WXSDKEngine.m
> [iOS] Public methods for getting/setting global device size.

- weex_core/Source/android/multiprocess/weex_js_connection.cpp
Fix close server fd repeatedly
> Fix close server fd repeatedly

- ios/sdk/WeexSDK/Sources/Module/WXTimerModule.m
> [Fix] First remove invalid timers and the report.

- ios/sdk/WeexSDK/Sources/Component/WXTransform.m
> [iOS] Use static regular expression instance for transform parsing.

- ios/sdk/WeexSDK/Sources/Module/WXAnimationModule.m
> Fix animation needlayout

- HOW-TO-BUILD.md
- README.md
Update documents for update ndk 18
> Update weex android build env

- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
1. fix the Android console output format in `WXBridgeManager` by using `String.format`
> [Android] Fix String output error

- android/sdk/src/main/java/com/taobao/weex/ui/animation/TransformParser.java
> [android] support rotateZ

- ios/sdk/WeexSDK/Sources/Component/WXListComponent.mm
> Protect crash of list update inserting header.

- android/sdk/src/main/java/com/taobao/weex/performance/WhiteScreenUtils.java
whiteScreen check ignore 
- height <10 || width <10 (check 3 deep max)
> [Android] fix whiteScreen check for 1pixel height/width

- android/sdk/src/main/java/com/taobao/weex/performance/WXInstanceApm.java
- android/sdk/src/main/java/com/taobao/weex/performance/WhiteScreenUtils.java
1. fix rootView height&width <10 check
2. add performance state check
3. add whiteScreen whiteList check
> [Android] fix rootView size check && performance state fix 

- ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.m
bundleType can be Vue, Rax
when the bundleType is "vue", the program goes bundleType = "other"
> [iOS] fix bundleType

- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
- android/sdk/src/main/java/com/taobao/weex/performance/WXStateRecord.java
- android/sdk/src/main/java/com/taobao/weex/performance/WhiteScreenUtils.java
- fix whiteScreen viewTree record
- fix  recordList record (should remove position 0)
- rm useless && rename func
> [Android] fix whiteScreen viewTree record && run state history record

- ios/sdk/WeexSDK.xcodeproj/project.pbxproj
> [iOS] Fix dynamic library build issue.

- .travis.yml
- dangerfile-android.js
Ref the following files:
* https://github.com/facebook/buck/blob/master/.travis.yml
* https://github.com/square/duktape-android/blob/master/.travis.yml
* https://github.com/aldochristiaan/travis-android-ndk/blob/master/.travis.yml
* https://github.com/googlesamples/android-ndk/blob/master/.travis.yml
> Update TravisCI for android NDK

- WeexSDK.podspec
- ios/playground/Podfile
- ios/playground/WeexDemo.xcodeproj/project.pbxproj
- ios/sdk/WeexSDK.xcodeproj/project.pbxproj
- ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.m
- ios/sdk/WeexSDK/Sources/Bridge/WXJSCoreBridge.mm
- ios/sdk/WeexSDK/Sources/Component/WXVideoComponent.m
- ios/sdk/WeexSDK/Sources/Controller/WXRootViewController.m
- ios/sdk/WeexSDK/Sources/Events/WXComponent+Events.m
- ios/sdk/WeexSDK/Sources/Manager/WXBridgeManager.m
- ios/sdk/WeexSDK/Sources/Manager/WXComponentManager.mm
- ios/sdk/WeexSDK/Sources/Model/WXComponent.mm
- ios/sdk/WeexSDK/Sources/Module/WXModalUIModule.m
- ios/sdk/WeexSDK/Sources/Utility/WXConvert.m
- ios/sdk/WeexSDK/Sources/Utility/WXUtility.m
> Upgrade iOS deployment target to 9.0

- ios/sdk/WeexSDK/Sources/Component/WXVideoComponent.m
- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
- ios/sdk/WeexSDK/Sources/Module/WXModalUIModule.m
> Remove iOS9 deprecated interface usage.

- android/sdk/build.gradle
- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridge.java
- weex_core/Source/android/bridge/script_bridge_in_multi_process.cpp
- weex_core/Source/android/jsengine/bridge/script/script_side_in_queue.cpp
- weex_core/Source/android/jsengine/object/tlog.h
- weex_core/Source/android/jsengine/object/weex_env.cpp
- weex_core/Source/android/jsengine/object/weex_env.h
- weex_core/Source/android/jsengine/task/back_to_weex_core_queue.cpp
- weex_core/Source/android/jsengine/task/back_to_weex_core_queue.h
- weex_core/Source/android/jsengine/task/impl/create_instance_task.cpp
- weex_core/Source/android/jsengine/weex_runtime.cpp
- weex_core/Source/android/jsengine/weex_runtime.h
- weex_core/Source/base/time_calculator.h
- weex_core/Source/third_party/IPC/IPCMessageJS.h
1. t log for sonProcess
2. add HeartBeat
3. Downgrade ndk api level to 16
> t log for sonProcess

- weex_core/Source/core/common/view_utils.h
fix android 4.4.4 load weexcore.so failed
> strtof -> strtod

- android/sdk/src/main/java/com/taobao/weex/performance/WXInstanceApm.java
> [Android] FIX NP

- ios/sdk/WeexSDK/Sources/Performance/WXApmForInstance.m
> Fix crash of accessing apm stage data not in component thread.

- weex_core/Source/wson/wson_parser.cpp
> remove high-ndk-api-level

- weex_core/Source/core/parser/dom_wson.cpp
> Remove invalid header usage which will cause iOS build failure.

- WeexSDK.podspec
- ios/sdk/WeexSDK.xcodeproj/project.pbxproj
- weex_core/Source/core/parser/dom_wson.cpp
> Merge 0.26

- WeexSDK.podspec
- ios/sdk/WeexSDK.xcodeproj/project.pbxproj
> Remove unused files of iOS.

- android/sdk/src/main/java/com/taobao/weex/utils/WXSoInstallMgrSdk.java
Throw link error if load so failed in debugApp
> Throw link error if load so failed in debugApp

- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
here is no need to reboot js engine if render by eagle
> here is no need to reboot js engine if render by eagle

- android/sdk/src/main/java/com/taobao/weex/WXEnvironment.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXParams.java
- android/sdk/src/main/java/com/taobao/weex/utils/WXSoInstallMgrSdk.java
- weex_core/Source/android/multiprocess/weex_js_connection.cpp
- weex_core/Source/android/utils/params_utils.cpp
- weex_core/Source/android/utils/so_utils.cpp
- weex_core/Source/android/utils/so_utils.h
1. add DefaultSetting SharedPreferences
2. unify so copy path with cpu type
> Update for libweexjsb path

- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
- android/sdk/src/main/java/com/taobao/weex/common/WXErrorCode.java
[Android] report error when reboot count > CRASHREINIT
> [Android] report error when reboot count > CRASHREINIT

- android/sdk/src/main/java/com/taobao/weex/WXSDKEngine.java
- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridge.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
- android/sdk/src/main/java/com/taobao/weex/performance/WXInstanceApm.java
- android/sdk/src/main/java/com/taobao/weex/performance/WXStateRecord.java
for fix  whitescreen fix, we need more msg
1. add jsthread watch dog (500ms loop)
2. record action
> [Android] add jsthread watch dog and record action for whitescreen fix

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXSlider.java
http://dotwe.org/vue/d99248504f47b25309f80aa5b11eb9d6
> [Android] Fix show-indicators doesn't work.

- ios/sdk/WeexSDK/Sources/Bridge/WXCoreBridge.mm
- ios/sdk/WeexSDK/Sources/Module/WXDomModule.m
> Fix heron event

- android/sdk/src/main/java/com/taobao/weex/ui/component/AbstractEditComponent.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
1. keybord show and input (addview)
2. slider children position fix (inScreen?)
> [Android] fix interaction badcase

- ios/sdk/WeexSDK/Sources/Component/WXEditComponent.mm
- ios/sdk/WeexSDK/Sources/Performance/WXApmForInstance.h
- ios/sdk/WeexSDK/Sources/Performance/WXApmForInstance.m
fix interaction time bad case : keyboard show and input (addView)
> [iOS] fix interaction time bad case : keyboard show and input (addView)

- ios/sdk/WeexSDK/Sources/Utility/WXUtility.m
> [iOS] Convert to immutable instance. Make code stronger.

- android/sdk/build.gradle
- android/sdk/src/main/AndroidManifest.xml
- android/sdk/src/main/java/com/taobao/weex/render/WXAbstractRenderContainer.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
- android/sdk/src/main/java/com/taobao/weex/ui/module/WXModalUIModule.java
- android/sdk/src/main/java/com/taobao/weex/ui/module/WXTimerModule.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/WXWebView.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/refresh/wrapper/BounceRecyclerView.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/refresh/wrapper/BounceScrollerView.java
One can verify the result by run `./gradlew lint` in Android directory or have a look of the result in https://github.com/apache/incubator-weex/pull/2731
> [Android] Fix some lint problems

- android/sdk/build.gradle
- android/sdk/src/main/java/com/taobao/weex/WXEnvironment.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXJSObject.java
- android/sdk/src/main/java/com/taobao/weex/http/WXStreamModule.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXImage.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXScroller.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/WXEditText.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/WXImageView.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/refresh/circlebar/CircleProgressBar.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/refresh/core/WXSwipeLayout.java
- android/sdk/src/main/java/com/taobao/weex/utils/WXResourceUtils.java
- android/sdk/src/main/java/com/taobao/weex/utils/WXSoInstallMgrSdk.java
- android/sdk/src/main/java/com/taobao/weex/utils/tools/LogDetail.java
- android/sdk/src/main/res/values/isrtl.xml
Run `./gradlew lint` or ref https://github.com/apache/incubator-weex/pull/2731 to see detail of the lint
> [Android] Fix problems in Android Lint

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/WXSlider.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/pesudo/TouchActivePseudoListener.java
- android/sdk/src/main/java/com/taobao/weex/ui/component/richtext/WXRichTextView.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/WXCircleViewPager.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/WXEditText.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/WXHorizontalScrollView.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/WXImageView.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/WXScrollView.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/WXSwitchView.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/WXTextView.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/WXVideoView.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/gesture/WXGesture.java
- android/sdk/src/main/java/com/taobao/weex/ui/view/listview/WXRecyclerView.java
- android/sdk/src/main/java/com/taobao/weex/utils/WXSoInstallMgrSdk.java
Ref #2731 or run `./gradlew lint` to see more.
> [Android] Add some annotation to suppress android lint.

- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
Do not reboot jsc manually if jsc is crashed
> Do not reboot jsc manually if jsc is crashed

- android/sdk/src/main/java/com/taobao/weex/http/WXStreamModule.java
- android/sdk/src/main/java/com/taobao/weex/performance/WXStateRecord.java
- android/sdk/src/main/java/com/taobao/weex/performance/WhiteScreenUtils.java
- android/sdk/src/main/java/com/taobao/weex/utils/WXViewUtils.java
1. white_screen check ignore unvisible view (alpha unvisible)
2. sort record state msg by time 
3. record streamModule end msg
> [Android] white_screen check ignore unvisible view (alpha unvisible)

- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
> [Android] record jsbundle execute time

- android/sdk/src/main/java/com/taobao/weex/performance/WXStateRecord.java
[Android] fix list op bug in Multithreading
> [Android] fix list op bug in Multithreading

- ios/sdk/WeexSDK/Sources/Utility/WXUtility.m
> [iOS] Protect nil argument for convertContainerToImmutable.

- weex_core/Source/third_party/IPC/IPCCommunicator.cpp
Do Not abort when Ipc receive end type
> Do Not abort when Ipc receive end type

- ios/sdk/WeexSDK/Sources/Bridge/WXCoreBridge.mm
> [iOS] layout引擎Frame计算向上取整

- android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
add new TimeCalculator for defaultConstructor
> add new TimeCalculator for defaultConstructor

- ios/sdk/WeexSDK/Sources/Manager/WXComponentManager.mm
- ios/sdk/WeexSDK/Sources/Module/WXTransition.mm
> Fix potential crash of animation.

- ios/sdk/WeexSDK/Sources/Bridge/WXCoreBridge.mm
> Initialize weex using portrait screen size.

- ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.m
- ios/sdk/WeexSDK/Sources/Bridge/WXCoreBridge.mm
- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
- weex_core/Source/core/bridge/platform/core_side_in_platform.cpp
> bugfix ios 8.11.1 multithreading crash by eagle destroy instance

- android/sdk/src/main/java/com/taobao/weex/WXEnvironment.java
- android/sdk/src/main/java/com/taobao/weex/adapter/IWXConfigAdapter.java
- android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
- android/sdk/src/main/java/com/taobao/weex/performance/WXStateRecord.java
1 add check mode could switch fix on/off
2 record instanceid when reload/jsccrash
> [Android] add mode check

- .travis.yml
> [Android] Build playground in Travis

- android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
> [Android] Avoid multiple error upload

- .travis.yml
>  [Android] Make Travis quiet.

- android/gradle.properties
- android/sdk/.gitignore
- android/sdk/build.gradle
* `-PapachePackageName=true`, use `org.apache.weex` as package name.
* `-PapachePackageName=false`, use `com.taobao.weex` as package name.
> [Android] Add the ability of renaming package by -PapachePackageName=false

- android/build.gradle
- android/sdk/build.gradle
- android/sdk/buildSrc/asan.gradle
- android/sdk/buildSrc/checkStyle.gradle
- android/sdk/buildSrc/jcenter.gradle
- android/sdk/buildSrc/packageName.gradle
- android/sdk/buildSrc/unstripped.gradle
> [Android] Split build.gradle file into 6 files.

- ios/sdk/WeexSDK/Sources/Component/WXCycleSliderComponent.mm
> [iOS] Protect endless iteration when setting index for slider view.

- ios/sdk/WeexSDK/Sources/Component/WXComponent_internal.h
- ios/sdk/WeexSDK/Sources/Display/WXComponent+Display.m
- ios/sdk/WeexSDK/Sources/Loader/WXResourceLoader.m
- ios/sdk/WeexSDK/Sources/Model/WXComponent.mm
- ios/sdk/WeexSDK/Sources/Utility/WXConvert.h
- ios/sdk/WeexSDK/Sources/Utility/WXConvert.m
- ios/sdk/WeexSDK/Sources/View/WXComponent+ViewManagement.mm
> Revert backgroundcolor

- ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.m
Break retain cycle of WXBridgeContext->jsBridge->jsContext->WXBridgeContext.
> [iOS] Break retain cycle when set function of JSContext

- ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.m
Release property name after set property.
> [iOS] Release property name after set property

- ios/sdk/WeexSDK/Sources/Component/WXComponent_internal.h
- ios/sdk/WeexSDK/Sources/Display/WXComponent+Display.m
- ios/sdk/WeexSDK/Sources/Model/WXComponent.mm
- ios/sdk/WeexSDK/Sources/View/WXComponent+ViewManagement.mm
> [iOS] Rename the backgroundColor property name.

- ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.mm
- weex_core/Source/core/layout/layout.h
> Add clearBFCs method and clear BFCs after self-layout of scroller node.

- .gitignore
- CHANGELOG.md
- HOW-TO-BUILD.md
- LICENSE
- README.md
- android/sdk/build.gradle
- android/sdk/buildSrc/unstripped.gradle
- android/sdk/src/main/java/org/apache/weex/utils/WXDataStructureUtil.java
- dangerfile.js
- ios/sdk/WeexSDK.xcodeproj/project.pbxproj
- ios/sdk/WeexSDK/Sources/Utility/WXVersion.m
- scripts/build_from_source.sh
- scripts/generate_apache_source.sh
- scripts/release_files.rules
> Update scripts for apace release.

- android/sdk/build.gradle
- android/sdk/src/main/java/org/apache/weex/WXEnvironment.java
- android/sdk/src/main/java/org/apache/weex/utils/WXSoInstallMgrSdk.java
- weex_core/Source/js_runtime/weex/utils/weex_jsc_utils.h
[Android] support switch javascriptCore (legacy)or jsc (apache)
> [Android] support switch javascriptCore (legacy)or jsc (apache)

- LICENSE
- android/build.gradle
- android/sdk/buildSrc/asan.gradle
- android/sdk/buildSrc/checkStyle.gradle
- android/sdk/buildSrc/download_jsc.gradle
- android/sdk/buildSrc/jcenter.gradle
- android/sdk/buildSrc/packageName.gradle
- android/sdk/buildSrc/unstripped.gradle
- android/sdk/build_jss_r.sh
- android/sdk/lint.xml
- android/sdk/wrap.sh
- android/settings.gradle
- weex_core/Source/third_party/json11/CMakeLists.txt
> Add ASF license header to a bunch of files.

- ios/sdk/WeexSDK/Sources/Component/WXTextComponent.mm
> Fix text component's property multi-thread crash.

- ios/sdk/WeexSDK/Sources/Module/WXTimerModule.m
> [iOS] Fix crash that creating timer with NAN interval.

- WeexSDK.podspec
> [iOS] update WeexSDK.podspec

- WeexSDK.podspec
> [iOS] Update pods

- android/sdk/buildSrc/download_jsc.gradle
- android/sdk/buildSrc/jcenter.gradle
> [Android] Fix task skipping problem of download.

- README.md
> update weex-vue-render badge

- test/scripts/util.js
change getDeviceHost servePort
CheckList:
> build: change getDeviceHost servePort

- ios/sdk/WeexSDK/Sources/Utility/WXDefine.h
update weex ios version to 0.28.0
> fix weex iOS version

- android/sdk/src/main/java/org/apache/weex/ui/component/WXScroller.java
- support loadMore event for horizontalScrollView
- democase: http://editor.weex.io/p/lucky-chen/scroler-appear/commit/0b489fe4c8e095ed908577ff1f1f62d8
> [Android] support loadMore for horizontalScrollView

- .travis.yml
> Use xcode11 for travis CI.

- ios/sdk/WeexSDK/Sources/Module/WXAnimationModule.m
- ios/sdk/WeexSDK/Sources/Module/WXTransition.mm
> [iOS] Fix dark-scheme animation logic.

- ios/sdk/WeexSDK/Sources/Module/WXModalUIModule.m
> [iOS] Do not use queue for iOS toast.

- ios/sdk/WeexSDK/Sources/Module/WXClipboardModule.m
> [iOS] Clip module should be used in main thread.

- weex_core/Source/core/render/page/render_page_custom.cpp
- weex_core/Source/core/render/target/render_target.h
> Optimize for custom render target.

- ios/sdk/WeexSDK/Sources/Module/WXDarkSchemeModule.m
> [iOS] Add unregisterSchemeChangeListener method.

- ios/sdk/WeexSDK/Sources/Bridge/WXJSCoreBridge.mm
- ios/sdk/WeexSDK/Sources/Component/WXRichText.mm
- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
- ios/sdk/WeexSDK/Sources/Module/WXDarkSchemeModule.m
- ios/sdk/WeexSDK/Sources/Utility/WXUtility.h
- ios/sdk/WeexSDK/Sources/Utility/WXUtility.m
- ios/sdk/WeexSDK/Sources/View/WXRootView.m
> [iOS] Optimize dark scheme logic.

- ios/sdk/WeexSDK/Sources/Model/WXComponent.mm
> [iOS] Fix dark scheme.

- ios/sdk/WeexSDK.xcodeproj/project.pbxproj
- ios/sdk/WeexSDK/Sources/Component/WXWebComponent.h
- ios/sdk/WeexSDK/Sources/Component/WXWebComponent.m
- ios/sdk/WeexSDK/Sources/Utility/WXVersion.m
Apple will stop accepting submissions of apps that use UIWebView APIs and urges developers to use WKWebView instead.
> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
Related issue:
https://github.com/apache/incubator-weex/issues/2866
> [iOS] Replace UIWebView with WKWebView

- ios/sdk/WeexSDK/Sources/Utility/WXUtility.m
> [iOS] Remove log which may cause infinite loop printing invalid object.

- ios/sdk/WeexSDK/Sources/Component/WXEmbedComponent.m
> [iOS] Inherit auto-invert for embed.

- README.md
> Upgrade readme for iOS minimum supported version.

- ios/sdk/WeexSDK/Sources/Component/WXTextComponent.mm
> [iOS] Fix text italic width not sufficient.

- ios/sdk/WeexSDK/Sources/Component/WXWebComponent.m
> [iOS]fix bug wkwebview crash

- ios/sdk/WeexSDK/Sources/Component/WXEditComponent.h
- ios/sdk/WeexSDK/Sources/Component/WXEditComponent.mm
- ios/sdk/WeexSDK/Sources/Component/WXTextAreaComponent.mm
> [iOS] Support dark scheme for input controls.

- ios/sdk/WeexSDK/Sources/Manager/WXComponentManager.mm
fix uncaught exception when nan value passed from front end
* Demo:
> [iOS] fix uncaught exception when nan value passed from front end

- ios/sdk/WeexSDK/Sources/Protocol/WXDarkSchemeProtocol.h
- ios/sdk/WeexSDK/Sources/Utility/WXUtility.m
> Dark switch fix

- ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
> [iOS] Do not reserve dark scheme handler.

- android/sdk/src/main/java/org/apache/weex/performance/WXInstanceApm.java
Delete the unused code in Android Weex SDK.
* Demo:
> T:  delete unused code

- .travis.yml
- android/build.gradle
1. Remove Maven mirror in Aliyun for TravisCI speed purpose
2. Update weex-playground to latest.
3. Ugrade support library to 28
This suppose to be the last commit before migrating AndroidX
* Demo:
> Refactor: Remove Maven mirror in Aliyun for speed.

- android/sdk/src/main/java/org/apache/weex/ui/component/AbstractEditComponent.java
> [Android]Fix rows doesn't work in textarea

- .travis.yml
- ios/sdk/WeexSDK/Sources/Module/WXPickerModule.m
Demo:
http://dotwe.org/vue/5fdb67685e4cf8eee1f4aa496a9c22c1
Documentation:
ios version above 13.4，UIDatePicker need set preferredDatePickerStyle property
update travis ci xcode version to 12
> [ios] ios14 set datepicker style

- ios/sdk/WeexSDK/Sources/Manager/WXDatePickerManager.m
- ios/sdk/WeexSDK/Sources/Module/WXPickerModule.m
* Demo
* http://dotwe.org/vue/aa4e8e72297559722ced75dd410e4033
* http://dotwe.org/vue/5fdb67685e4cf8eee1f4aa496a9c22c1
> [iOS] fix input component wakeup UIDatePicker

- android/sdk/src/main/java/org/apache/weex/WXEnvironment.java
- weex_core/Source/android/multiprocess/weex_js_connection.cpp
> [Android]Optimize AndroidR logic 

- RETIRED.txt
According to the http://incubator.apache.org/guides/retirement.html we need to add the RETIRED file into the repo.
> Added RETIRED.txt file
