apache/incubator-weex

doc/_config.yml
doc/package.json

Automatically deploy website to apache gitpubsub repo through `hexo d` in `doc` folder.

[website] updated website deploy config

---

.travis.yml
android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
android/sdk/src/main/java/com/taobao/weex/common/Constants.java
android/sdk/src/main/java/com/taobao/weex/http/WXStreamModule.java
android/sdk/src/main/java/com/taobao/weex/ui/animation/BackgroundColorProperty.java
android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
android/sdk/src/main/java/com/taobao/weex/ui/view/border/BorderDrawable.java
android/sdk/src/main/java/com/taobao/weex/ui/view/refresh/wrapper/BaseBounceView.java
android/sdk/src/main/java/com/taobao/weex/utils/WXFileUtils.java
android/sdk/src/main/java/com/taobao/weex/utils/WXViewUtils.java
test/ci-funcs.sh

Fix NPE in list's `BaseBounceView`.

* [android] fix domobject NPE

---

android/sdk/src/main/java/com/taobao/weex/ui/component/WXSlider.java

WXSlider add Android event [scrollstart&scrollend] @

WXSlider add event [scrollstart&scrollend]

---

ios/sdk/WeexSDK/Sources/Module/WXStorageModule.m
ios/sdk/WeexSDKTests/WXStorageTests.m

1. WXStorage: return data:undefined when getItem fail

return data-undefined when getItem fail

---

android/sdk/src/main/java/com/taobao/weex/ui/component/WXScroller.java
android/sdk/src/main/java/com/taobao/weex/ui/component/helper/WXStickyHelper.java
android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
android/sdk/src/main/java/com/taobao/weex/ui/view/WXScrollView.java

```
java.util.ConcurrentModificationException
at java.util.HashMap$HashIterator.nextEntry(HashMap.java:806)
at java.util.HashMap$EntryIterator.next(HashMap.java:843)
at java.util.HashMap$EntryIterator.next(HashMap.java:841)
at com.taobao.weex.ui.component.list.BasicListComponent.(BasicListComponent.java:618)
at com.taobao.weex.ui.view.listview.adapter.WXRecyclerViewOnScrollListener.(WXRecyclerViewOnScrollListener.java:270)
at android.support.v7.widget.RecyclerView.(RecyclerView.java:3954)
at android.support.v7.widget.RecyclerView.(RecyclerView.java:3115)
at android.support.v7.widget.RecyclerView.(RecyclerView.java:2917)
```
@YorkShen

* [android] fix ConcurrentModificationException in list sticky map

---

android/sdk/src/main/java/com/taobao/weex/ui/component/WXEmbed.java

clear listener when activity destroy to prevent memory leak

* [android] clear listener when activity destroy to prevent memory leak

---

android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
package.json
test/README.md
test/pages/components/scroller-fixed.we
test/scripts/components/scroller-fixed.test.js

Fix item with 'position:fixed' scroll with parent.
The reason of this bug is 'fixed' view will add to root node's view. So when the root is 'scroller','fixed' not working.
Testcase: http://dotwe.org/weex/a281d7db58ba73ef0a143535d3703bc4

Fix pos fixed failed when parent is scroller

---

doc/source/references/gesture.md
doc/source/references/vue/difference-with-web.md

fix a typo in gesture reference doc about longPress
fix the weex-loader url broken in vue/difference-with-web

fix a typo in doc

---

android/sdk/src/main/java/com/taobao/weex/dom/ImmutableDomObject.java
android/sdk/src/main/java/com/taobao/weex/dom/WXDomObject.java
android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java

Use a placeholder object for component's dom after destory.

* [android] use a dom for destroy , avoid NPE after component destroyed.

---

android/sdk/src/main/java/com/taobao/weex/ui/component/WXScroller.java
android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java

Deprecate `loadmorerety` in android ,use same reset logic scroller/list with iOS.
@misakuo

Deprecate loadmoreretry attribute

---

ios/sdk/WeexSDK/Sources/Module/WXAnimationModule.m

* all CABasicAnimaitions should be removed when animation stops, otherwise it will affect view or layer's transform property
* test demo: http://dotwe.org/weex/6a0695ca46f6abfe9638eb391aac729c

* [ios] Fix issue that [view setTransform:] not working after animation

---

android/sdk/src/main/java/com/taobao/weex/ui/component/WXBaseRefresh.java

Layout is ignore is refresh component (both WXRefresh and WXLoading), when its parent is scrollable component. That will cause style do not working in these component.
Testcase: http://dotwe.org/weex/58c9fbbda7ddb368631602c1595a717b

 [android] remove special set layout parameter in baserefesh

---

ios/sdk/WeexSDK/Sources/Engine/WXSDKError.h

[ios] fix wrong spelling caused compile error on Xcode version 8.2.1(8C1002)

spelling mistake

---

CHANGELOG.md
android/sdk/src/main/java/com/taobao/weex/dom/DOMActionContextImpl.java
android/sdk/src/main/java/com/taobao/weex/dom/WXDomHandler.java
android/sdk/src/main/java/com/taobao/weex/dom/action/Actions.java
android/sdk/src/main/java/com/taobao/weex/dom/action/AnimationAction.java
android/sdk/src/main/java/com/taobao/weex/ui/RenderActionContextImpl.java
android/sdk/src/main/java/com/taobao/weex/ui/WXRenderManager.java
android/sdk/src/main/java/com/taobao/weex/ui/animation/DimensionUpdateListener.java
android/sdk/src/main/java/com/taobao/weex/ui/animation/WXAnimationBean.java
android/sdk/src/main/java/com/taobao/weex/ui/animation/WXAnimationModule.java
android/sdk/src/test/java/com/taobao/weex/dom/WXDomStatementTest.java
android/sdk/src/test/java/com/taobao/weex/ui/animation/WXAnimationModuleTest.java

[Android] Refactor animation using Action and perserve `transformOrigin`'s last time state.
Before this commit, transformOrigin is stateless during a sequence of animation, e.g. tranformOrigin would reset to `50%, 50%` every time if it was not given. This commit respect `transformOrigin` last time state unless it is specified this time. Developers who depends on the wrong implementation may run into a problem.
Potential break changes:
* For Android developer: Those who start animation by invoking AnimationModule, RenderManager, or DomManager directly may run into compiling error or runtimeException.
* For Front-end developer: Those who depends on transformOrigin reset to `center center` after each animation will run into problem.

* [Android] refactor animation

---

android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
android/sdk/src/main/java/com/taobao/weex/adapter/DefaultUriAdapter.java

* [android] update modify rewrite

---

ios/sdk/WeexSDK/Sources/Component/WXEditComponent.m
package.json
test/pages/components/textarea-maxlength.vue
test/scripts/components/textarea-maxlength.test.js

-  textarea add maxlength ,because android textarea has this attributes
- demo
```html
<template>
<div class="wrapper">
<textarea class="textarea" maxlength=10 @input="oninput" @change="onchange" @focus="onfocus" @blur="onblur"></textarea>
</div>
</template>
<script>
const modal = weex.requireModule('modal')
export default {
methods: {
oninput (event) {
console.log('oninput:', event.value)
modal.toast({
message: `oninput: ${event.value}`,
duration: 0.8
})
},
onchange (event) {
console.log('onchange:', event.value)
modal.toast({
message: `onchange: ${event.value}`,
duration: 0.8
})
},
onfocus (event) {
console.log('onfocus:', event.value)
modal.toast({
message: `onfocus: ${event.value}`,
duration: 0.8
})
},
onblur (event) {
console.log('onblur:', event.value)
modal.toast({
message: `input …
```

+ [ios] textarea add maxlength ,because android textarea has this attributes

---

doc/source/v-0.10/references/components/list.md
doc/source/v-0.10/references/components/refresh-loading.md

fix doc examples: recommend to use inline function binding to deprecate the access of `e.target.attr`.

[doc] use inline event handler binding.

---

doc/_config.yml
doc/themes/weex/layout/_partial/header.ejs

We have hidden the two tools for developers. These links will be replace  with the url of`weex-toolkit`.

*[Doc]remove weexpack and devtool link

---

html5/render/vue/modules/dom.js
package.json

scrollToElement method support no animation.
weex.requireModule('dom').scrollToElement(el, {animated: false})

* [html5] scrollToElement method support no animation

---

ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.m
ios/sdk/WeexSDK/Sources/Bridge/WXJSCoreBridge.m
ios/sdk/WeexSDK/Sources/Protocol/WXBridgeProtocol.h

support jsfm call timer directly , not through bridge.
Because wxtimermodule execute until the jsbridge thread finish.  it will delay .
the minimum time interval  is 14ms average  and is not precarious in the old method
the minimum time interval  is 3ms average and is Stable in new method
Android PR:https://github.com/apache/incubator-weex/pull/221

+ [ios] add feature timer

---

ios/sdk/WeexSDK/Sources/Monitor/WXMonitor.m

* [ios] bug fix: customMonitorInfo only deal dictionary and string

* [ios] bug fix: customMonitorInfo only deal dictionary and string

---

ios/sdk/WeexSDK/Sources/Module/WXPickerModule.m

+ [ios] picker support custom 
title
titleColor
cancelTitle
confirmTitle
cancelTitleColor
confirmTitleColor
titleBackgroundColor
height
textColor
selectionColor
demo
```
<template>
<scroller>
<wxc-panel title="picker module" type="primary">
<text style="margin-bottom: 20px;">pick value: {{value}}</text>
<wxc-button type="primary" onclick="{{pick}}" value="single pick" style="margin-bottom: 20px;"></wxc-button>
<wxc-button type="primary" onclick="{{pickDate}}" value="pickDate" style="margin-bottom: 20px;"></wxc-button>
<wxc-button type="primary" onclick="{{pickTime}}" value="pickTime"></wxc-button>
</wxc-panel>
<wxc-panel title="input component" type="primary">
<text>onchange: {{txtChange}}</text>
<input
type="date"
placeholder="select date"
class="input"
autofocus="false"
value="" …
```

+ [ios] picker support custom title title color background color and etc

---

android/sdk/src/main/java/com/taobao/weex/utils/WXResourceUtils.java
android/sdk/src/test/java/com/taobao/weex/utils/WXResourceUtilsTest.java

Use Pair instead of Exception in WXResourceUtils to imply an error occur as NullPointerException has poor performance in ART environment.

* [android] Use Pair in WXResourceUtils to imply error

---

android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
android/sdk/src/main/java/com/taobao/weex/dom/action/AnimationAction.java
android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java

For certain custom weex instance, one can disable the ability of changing layerType by call `WXSDKInstance.enableLayerType(boolean)`. The default value for this flag is true and setting this to false will have performance punishment。

* [Android] Add the ability of disable changing layerType

---

ios/sdk/WeexSDK/Sources/Component/WXSliderComponent.m

remove start event and stop event from slider component. and fix the crash in didscroll method on iOS 8.x .

0.12 dev old slider remove start end events

---

android/sdk/src/main/java/com/taobao/weex/ui/component/WXEmbed.java

when one weex page has many embed component with empty src, it will lead to downgrade logic, and will cause performance low, so should stop load when src is empty

* [android] stop load when src is empty

---

ios/sdk/WeexSDK/Sources/Controller/WXBaseViewController.h
ios/sdk/WeexSDK/Sources/Controller/WXBaseViewController.m
ios/sdk/WeexSDK/Sources/Controller/WXRootViewController.m

这是一个早期修改右滑手势返回留下的bug，我在源仓库中提过一个[pr](https://github.com/alibaba/weex/pull/2667),但是并没有被合并到主仓库中，目前发现这bug依然存在。希望能够解决一下。
-----
在[#2433](https://github.com/alibaba/weex/pull/2433)中，我将sdk中添加用来右滑返回的手势，更换成系统提供的方式，但是在最近的开发中，发现这种添加方式存在以下问题：
在WXBaseViewController中设置navigationController.interactivePopGestureRecognizer.delegate，每次创建baseVC对象时，那么delegate都会指向这个新的baseVC，导致了navigator的手势效果始终都只有栈顶的baseVC有； 这样当栈顶的baseVC弹出后，navigationController.interactivePopGestureRecognizer.delegate=nil,导致了后面的baseVC都不能够使用手势返回； 
为了保证interactivePopGestureRecognizer的代理始终存在，将其设置在WXRootViewController的viewDidLoad()中，保证这个手势的delegate始终都不会为nil，这样也降低了WXBaseVC每次都去增加手势的任务
如果是在项目中集成weex页面的，也只需在本地项目中的navigationController的viewDidLoad()中，设置interactivePopGestureRecognizer代理即可

修复iOS SDK添加系统返回手势的bug

---

ios/sdk/WeexSDK/Sources/Protocol/WXURLRewriteProtocol.h

fix a bug on WXURLRewriteProtocol.h.
The unfixed code will lead to a bug which cause the implement of WXURLRewriteProtocol would receive a static resource type.

解决rewrite协议的一个bug

---

ios/sdk/WeexSDK/Sources/Bridge/WXJSCoreBridge.m

- support bota and atob
- demo
```html
<template>
<div id="test" style="" onlongpress="longpress" onclick="click">
<text id="canvas_demo" style="backgroundColor:yellow;width:750;height:100;">demo 1</text>
<text if="{{shown}}" style="width:750;height:100;">{{original}}</text>
<text if="{{shown}}" style="width:750;height:100;">{{encode}}</text>
<text if="{{shown}}" style="width:750;height:100;">{{decode}}</text>
<text id="canvas_demo2" style="backgroundColor:yellow;width:750;height:100;">demo 2</text>
</div>
</template>
<script>
console.log("[index.we::script] start...");
module.exports = {
data: {
shown: true,
original: '',
encode: '',
decode: ''
},
methods: {
longpress: function(e) {
console.log('long:', e);
},
click: function(e) {
//runNextCase();
},
disable: function() { …
```

+ [ios]support bota and atob

---

ios/sdk/WeexSDK/Sources/Component/WXEmbedComponent.m

embed component frame isn’t changed when resizing root view frame

* [ios] fix embed components frame when resizing root view frame

---

ios/sdk/WeexSDK.xcodeproj/project.pbxproj
ios/sdk/WeexSDK/Sources/Module/WXAnimationLayout.h
ios/sdk/WeexSDK/Sources/Module/WXAnimationLayout.m
ios/sdk/WeexSDK/Sources/Module/WXAnimationModule.m

add support of all views' layout when animating.Use needlayout argument to open this feature.

0.13 dev animate

---

android/sdk/src/main/java/com/taobao/weex/dom/action/AnimationAction.java
android/sdk/src/main/java/com/taobao/weex/ui/animation/DimensionUpdateListener.java
android/sdk/src/main/java/com/taobao/weex/ui/animation/WXAnimationBean.java
android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java

Fix the [WEEX-28](https://issues.apache.org/jira/browse/WEEX-28)
add support of all views' layout when animating.
Use `needLayout` argument to open this feature.
testcase:http://dotwe.org/weex/77b71bd7a331f141521bea05a86c2ad0

+ [android] add needLayout option for animation module

---

android/sdk/src/main/java/com/taobao/weex/LayoutFinishListener.java
android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
android/sdk/src/main/java/com/taobao/weex/bridge/WXModuleManager.java
android/sdk/src/main/java/com/taobao/weex/dom/DOMActionContextImpl.java
android/sdk/src/main/java/com/taobao/weex/dom/WXDomHandler.java
android/sdk/src/main/java/com/taobao/weex/dom/WXDomManager.java
android/sdk/src/main/java/com/taobao/weex/dom/action/Actions.java
android/sdk/src/main/java/com/taobao/weex/dom/action/CreateFinishAction.java
android/sdk/src/main/java/com/taobao/weex/dom/action/ExecutableAction.java
android/sdk/src/main/java/com/taobao/weex/dom/action/ExecutableRenderAction.java
android/sdk/src/main/java/com/taobao/weex/dom/action/ModuleInvocationAction.java
android/sdk/src/main/java/com/taobao/weex/ui/module/WXTimerModule.java

introduction : https://issues.apache.org/jira/browse/WEEX-27?jql=project%20%3D%20WEEX%20AND%20resolution%20%3D%20Unresolved%20AND%20priority%20%3D%20Major%20ORDER%20BY%20key%20DESC

+ [android] support prerender

---

android/sdk/src/main/java/com/taobao/weex/ui/view/border/BorderDrawable.java

When combining border-color(rgba) and background-image together, the alpha in border-color also has an unexpected influence on background-image due to border and background-image share the same paint.
Refer http://dotwe.org/vue/d97477731dd85fedb3970fb106953fb9 to see a demo.

* [android] Fix mixing background-color and border-color(rgba)

---

html5/render/native/index.js
html5/render/native/setup.js

Move setup to a seperate file.    
Default weex project will setup frameworks under `../../frameworks/index`. In some custom case, you can use whatever you want by pass the frameworks as arguments to  this `setup` function.

Jsfm setup function

---

ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.m

iOS UIScrollView's built-in pagingEnabled feature is more natural than using pan gesture.

* [ios] add pagingEnabled attribute for scroller component

---

ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.m
ios/sdk/WeexSDK/Sources/Events/WXComponent+Events.m

add force value for touchEvent, [w3c](https://github.com/w3c/touch-events/pull/81) document
about [touch](https://w3c.github.io/touch-events/#widl-Touch-force) update it about a month ago,
note: the force value is range `0` to `1`, where 0 is no pressure, and 1 is the highest level of pressure the touch device is capable of sensing; 0 if no value is known. In environments where force is known, the absolute pressure represented by the force attribute, and the sensitivity in levels of pressure, may vary.
case: http://dotwe.org/weex/653ec363683c3c69bf2884c6eb7f061d

* [ios] add force touch `force` value for touch event

---

android/sdk/src/main/java/com/taobao/weex/utils/WXResourceUtils.java

As support-v4 actually supports api 9 from support library [24.2.0 and higher](https://developer.android.com/topic/libraries/support-library/index.html#api-versions). Any class reference in v4 library that is expected to work lower than API 9 and higher than API 4 should be [migrated](https://developer.android.com/topic/libraries/support-library/rev-archive.html).

* [android] Use pair in android.util.pair.

---

android/sdk/src/main/java/com/taobao/weex/ui/module/WXTimerModule.java
android/sdk/src/test/java/com/taobao/weex/ui/module/WXTimerModuleTest.java

Due the implementation of [int auto-boxing](https://stackoverflow.com/questions/3130311/weird-integer-boxing-in-java) and [messageQueue](https://stackoverflow.com/questions/36190851/android-os-handler-removemessages-doesnt-work-when-poxing-value-type-as-msg-obj), clearTimeout and clearTimeout won't work when funId is greater than 127. It works fine when funId is smaller than 127.

* [android] Fixing clearTimeout and clearInterval doesn't work when funId is greater than 127

---

android/sdk/src/main/java/com/taobao/weex/ui/component/AbstractEditComponent.java

JIRA Issue: https://issues.apache.org/jira/browse/WEEX-41

* [android] remove some reference of DomObject on input

---

html5/shared/console.js

As Weex switched its js engine to JSC on Android, the legacy hack of the console should be removed.

[jsfm] Fix the console API to adapt JSC on Android

---

android/sdk/src/main/java/com/taobao/weex/dom/action/Actions.java

* [android] fix invalid call scrollToElement when has not option param

---

android/sdk/src/main/java/com/taobao/weex/ui/component/WXScroller.java
android/sdk/src/main/java/com/taobao/weex/ui/view/WXHorizontalScrollView.java
android/sdk/src/main/java/com/taobao/weex/ui/view/WXScrollView.java

+ [android] add scroll event on horizontal scroller

---

ios/sdk/WeexSDK/Sources/Component/WXCycleSliderComponent.m

bug fix: initial index of WXCycleSliderComponent may be incorrect if
inserting subviews after layoutDidFinish (occurs when creating
time-consuming subview/components)

[iOS] fix WXCycleSliderComponent initial index

---

html5/render/vue/components/scrollable/list/index.js
html5/render/vue/components/scrollable/scroller.js
html5/render/vue/components/scrollable/waterfall.js
html5/render/vue/components/slider/slideMixin.js
html5/render/vue/core/node.js
html5/render/vue/env/wx-env.js
html5/render/vue/mixins/base.js
html5/render/vue/mixins/scrollable.js
html5/render/vue/utils/style.js
html5/test/render/vue/core/node.js
package.json
packages/weex-vue-render/package.json

* support fast click
* use `weex.config.env.osName` to tell is Android or iOS.
* support hairlines (1px device width) border.

[vue-render] support fast click & env.osName & hairlines border.

---

android/sdk/src/main/java/com/taobao/weex/dom/WXTextDomObject.java

* [android] fix bug that WXText lines cannot be reset @notdanger

---

android/sdk/src/main/java/com/taobao/weex/dom/WXRecyclerDomObject.java
android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
android/sdk/src/main/java/com/taobao/weex/ui/component/list/WXListComponent.java

bugfix : list OOM cause by viewHolder cache，set the upper limit for the viewHolder cache pool

* [android] fix : list OOM cause by viewHolder cache，set the upper limit for the viewHolder cache pool

---

ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.m
ios/sdk/WeexSDK/Sources/Bridge/WXModuleMethod.h
ios/sdk/WeexSDK/Sources/Bridge/WXModuleMethod.m
ios/sdk/WeexSDK/Sources/Manager/WXComponentManager.m
ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
ios/sdk/WeexSDK/Sources/Protocol/WXValidateProtocol.h

Add `options` for module validation to get `isvAppKey`. For component validation, `isvAppKey` would be fetched from `superComponent`.

+[ios] 0.16-dev update code for component/module validation

---

android/playground/app/src/main/java/com/alibaba/weex/IndexActivity.java
android/sdk/src/main/java/com/taobao/weex/WXSDKManager.java
android/sdk/src/main/java/com/taobao/weex/common/WXWorkThreadManager.java
android/sdk/src/main/java/com/taobao/weex/ui/component/WXImage.java
android/sdk/src/main/java/com/taobao/weex/utils/WXViewToImageUtil.java

support to save the image to Photo Album in image component method
case: http://dotwe.org/vue/55b9f0683f9c8bb9e12788626608da4c
jira issues: https://issues.apache.org/jira/browse/WEEX-62

+ [android] support new feature image component can save to Photo Album

---

android/sdk/src/main/java/com/taobao/weex/ui/component/AbstractEditComponent.java

RT.
For render delay reason, when the view is not created, the SHOW_IMPLICIT not works on some android devices.

[android] fix android input , autoforce not work on some device.

---

examples/vue/market/gcanvas.vue

1.  h5, `weex-gcanvas` does not recognize the gcanvas tag because the` weex-gcanvas` library can not be coupled to vue so that the gcanvas tag can not be registered. Need to judge.
2.  We need to set the `width` and` height` attributes of the canvas tag, otherwise the display is incorrect.
> weex-gcanvas version should be more than the 0.5.2

fix: gcanvas example support to html5

---

android/sdk/src/main/java/com/taobao/weex/ui/component/WXText.java
android/sdk/src/main/java/com/taobao/weex/utils/TypefaceUtil.java

Testcase: http://dotwe.org/vue/6ece072d0abd9a9e5718eb26bd5719f8
**NOTE: .woff font not supported in Android Nougat**

* [android] fix wrong draw on first download iconfont

---

android/sdk/src/main/java/com/taobao/weex/appfram/pickers/DatePickerImpl.java

The pickDate method in Android's Picker Module will return date like '2017-09-6' instead of '2017-09-06', this PR correct the problem.

* [android] correct the format of the date returned by pickDate method.

---

android/sdk/src/main/java/com/taobao/weex/ui/module/WXTimerModule.java
android/sdk/src/test/java/com/taobao/weex/ui/module/WXTimerModuleTest.java
test/pages/modules/vue_timer.vue
test/pages/modules/we_timer.we

The timer in Android will supports float interval/delay and transform them to int.
As some coders always ignore the docs and pass float value, which is not supported, the sdk has no way but to be tolerant with wrong behavior.
Refer <https://issues.apache.org/jira/browse/WEEX-68>

* [android] The timer in Android will supports float interval/delay

---

android/sdk/src/main/java/com/taobao/weex/ui/component/AbstractEditComponent.java

Fix the redundant `oninput` callback when default value to be seted
Testcase:
http://dotwe.org/vue/5ad804cd421805f7a2627cc81422a6e5

* [android] fix redundant input event

---

android/sdk/src/main/java/com/taobao/weex/dom/action/MoveElementAction.java
android/sdk/src/main/java/com/taobao/weex/ui/component/WXScroller.java
android/sdk/src/main/java/com/taobao/weex/ui/component/WXSlider.java
android/sdk/src/main/java/com/taobao/weex/ui/component/WXSliderNeighbor.java
android/sdk/src/main/java/com/taobao/weex/ui/component/WXVContainer.java
android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
android/sdk/src/main/java/com/taobao/weex/ui/component/list/template/WXRecyclerTemplateList.java

Fix that moveElement doesn't work when parent is not a list.
This bug may exist for more than two years.

* [Android] Fix that moveElement doesn't work when parent is not a list

---

android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
android/sdk/src/main/java/com/taobao/weex/ui/component/WXVContainer.java

Now we only add box-shadow view into WXFrameLayout
Testcase:
http://dotwe.org/vue/6bc1c6eae6ec927e1bd97c5ee2e18720

* [android] fix wrong logic when set box-shadow on adapter view

---

android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java

Ignore create ViewOverlay if has not `box-shadow` in current styles

* [android] memory optimization for box-shadow

---

android/sdk/src/main/java/com/taobao/weex/ui/view/WXImageView.java

onVisibilityChanged most sense right. but when native component custom set parent visibility, the method not paired on some platform, e.g when parent become invisible, changedView is this, visibility is invisible.

custom bugfix when native custom component  set visibility

---

html5/runtime/api/init.js
html5/runtime/bridge/receiver.js

Move the `callJS` and `receiveTasks` into a separate file. This feature has no breaking change.
By support the `receiveTasks` in `weex-js-runtime`, this method can be removed from `weex-vue-framework` and `weex-rax-framework`. It can keep the js-native communication have the same behavior.

[jsfm] Support receive tasks in weex-js-runtime

---

html5/runtime/bridge/CallbackManager.js
html5/runtime/bridge/TaskCenter.js
html5/runtime/bridge/receiver.js

Support to receive the `componentHook` task via `callJS`, and expose the `registerHook` and `triggerHook` APIs in the task center.
This feature can be used to achieve the lifecycle hook within `<recycle-list>`. The design proposal can be found in https://github.com/Hanks10100/weex-native-directive/tree/master/component .
The front-end frameworks (Vue.js, Rax) rely on this feature to implement the virtual component.

[jsfm] Support register and trigger component hooks

---

ios/sdk/WeexSDK/Sources/Events/WXComponent+Events.m

In most case , element in cell will be re-use for memory especially in very
long list, but if add event for this element, here will generate a new view for
this element,if it's nil due to a  getter method whether it is off-screen.
For instance, image element in cell will re-use if it is disappear in vision area,
loaded again while it back to visual area. In this case , when it disappear, just
add event such as click, touch and so on , it will then create a new view,
and load image again, although it is off-screen.
If the view is not loaded, so won't add gesture or call this view getter to create
any view until the view is loaded, then it will init events according to record in
component.
Bug: 98

[WEEX-98][iOS]bug-fix addEvent lead to generate a new view while it as been recycled

---

ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.m

As iOS developers all knowns, assign property will not be set nil when
its object deallocated, and weak object will does, so we must set it to the 
nil value, in case of crash about messaging to zombie object. In iOS 8 and
the older iOS, the property of delegate of UIScrollView is assign, so we
must set it to nil manually when object deallocated. And in iOS 9 and later
iOS, apple change the delegate property of UIScrollView it to weak, so we
don't set it to nil value any more. For compatibility on iOS 8, here we must
set it to nil value.
Bug: 94

[WEEX-94][iOS] fix iOS 8 scrollview assign delegate crash

---

ios/sdk/WeexSDK/Sources/Bridge/WXJSCoreBridge.m
ios/sdk/WeexSDK/Sources/Component/WXListComponent.m

In most case , element in cell will be re-use for memory especially in very
long list, but if add event for this element, here will generate a new view for
this element,if it's nil due to a  getter method whether it is off-screen.
For instance, image element in cell will re-use if it is disappear in vision area,
loaded again while it back to visual area. In this case , when it disappear, just
add event such as click, touch and so on , it will then create a new view,
and load image again, although it is off-screen.
If the view is not loaded, so won't add gesture or call this view getter to create
any view until the view is loaded, then it will init events according to record in
component.
Bug: 98

[WEEX-96][iOS] bug-fix about timer exposed on JSContext

---

ios/sdk/WeexSDK/Sources/Module/WXMetaModule.m

[WEEX-99][iOS] fix setViewport: sometimes doesn't work.
The setViewport method in WXMetaModule is ASYN right now which makes weexInstance.viewportWidth setted after view created.
Bug:99

[WEEX-99][iOS] fix setViewport: sometimes doesn't work

---

html5/runtime/api/init.js
html5/runtime/utils.js

Add a tracker to collect the bundle type usage message. If the developer is still using the legacy ".we" framework, it'll print an error in console and record the bundle messages.
References: [WEEX-90: Remove The Legacy Weex DSL 1.0 (.we) Front-End Framework](https://issues.apache.org/jira/browse/WEEX-90)

[jsfm] Add a tracker for legacy ".we" framework

---

android/sdk/src/main/java/com/taobao/weex/WXSDKEngine.java
android/sdk/src/main/java/com/taobao/weex/ui/module/WXLocalModule.java

+ [android] new local module

---

ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.m

[WEEX-109] [iOS]  add scrollstart and scrollend event's interface for scroller
Just use fireEvent to make UIScrollViewDelegate exposed to the front users.
Now can use  'scrollstart' and 'scrollend' to get scroller's status.
https://issues.apache.org/jira/browse/WEEX-109
http://dotwe.org/vue/96421f059fb7481faa4af86adb813efa
http://dotwe.org/vue/30fce705bf5c8a0763a95367c9b8dcfe

[WEEX-109][iOS] add scrollstart and scrollend event's interface for scroller

---

ios/sdk/WeexSDK/Sources/Component/WXTransform.m

We found that in AnimationModule's transform do not support examples such as ' translateX(10px) translateY(20px)',and we fix this bug in 0.17.0.

[WEEX-124][iOS]Transform's parse problem about translate

---

ios/sdk/WeexSDK/Sources/Component/WXListComponent.m
ios/sdk/WeexSDK/Sources/Layout/WXComponent+Layout.m

try to protect nan crash when set frame containing nan value.
Last Exception Backtrace:
```
0   CoreFoundation                  0x00000001830301c0 __exceptionPreprocess :124 (in CoreFoundation)
1   libobjc.A.dylib                 0x0000000181a6855c _objc_exception_throw :56 (in libobjc.A.dylib)
2   CoreFoundation                  0x0000000183030108 +[NSException raise:format:] :116 (in CoreFoundation)
3   QuartzCore                      0x0000000186335db8 CA::Layer::set_position(CA::Vec2 const&, bool) :152 (in QuartzCore)
4   QuartzCore                      0x0000000186335f2c -[CALayer setPosition:] :40 (in QuartzCore)
5   QuartzCore                      0x00000001863364c4 -[CALayer setFrame:] :448 (in QuartzCore)
6   UIKit                           0x0000000188e71e2c -[UIView(Geometry) …
```

[WEEX-105][iOS] bug-fix about setting nan frame crash

---

ios/sdk/WeexSDK/Sources/Component/WXListComponent.m

according to  https://stackoverflow.com/questions/46445661/ios-11-uitableview-behaviour-changed/46447370#46447370
https://forums.developer.apple.com/message/245686  this estimation action will make tableview edit abnormal, crash sometimes
so disable it from iOS 11.
Bug: 119

[WEEX-119][iOS] disable tableview estimation row or section height.

---

ios/sdk/WeexSDK/Sources/Component/WXComponent_internal.h
ios/sdk/WeexSDK/Sources/Model/WXComponent.m

Consider an app that shows items in vertical columns. Normally, voiceOver would navigate through
these items in horizontal rows. Setting the value of this property to YES on the parent element of the
items in the vertical columns causes VoiceOver to respect the app’s grouping and navigate them.Andthe default of this property is NO.
Bug:101

[WEEX-101][iOS] specify voice-over navigation order is column or vertical

---

ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
ios/sdk/WeexSDK/Sources/Utility/WXUtility.h
ios/sdk/WeexSDK/Sources/Utility/WXUtility.m

this action will let iOS decide whether it should draw float pixel.
Bug:122
here are some cases about this problem
http://dotwe.org/vue/b0a242260e1df1b93964834b43bd25f7
http://dotwe.org/vue/32c8940df1673c2642abfd39f0ce9421
and the screenshot, the right one has been correct.

[WEEX-122][iOS]bugfix round float pixel lead to the lack of pixel

---

ios/sdk/WeexSDK/Sources/Component/WXTextComponent.m

there are case when text update frequently, so when main thread drawing text, here updates come,
so the text value must protect here from be setting in multithread, here use lock temporarily.
Bug:121

[WEEX-121][iOS] bug-fix draw text crash

---

ios/playground/WeexDemo/WXConfigCenterDefaultImpl.m
ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.m

if the view has not been loaded or has not been added to its scroller view, it should not be
notified appear event, because it cannot scroll to appear area as the scrollview scroll.
Bug:102
you can try this case http://dotwe.org/vue/26c9717b1c60304668899b996ac8a9ac

[WEEX-102][iOS]bugfix appear event will fire wrongly while the view has not been loaded

---

ios/sdk/WeexSDK/Sources/Component/WXTextComponent.m

the order of drawing text and the action of building font-family in javaScript is not reliable,
so the observer needs to be added to every text component  which specify the font-family,
when the the custom font download finish, redraw action will compare the font-family with
font-family of text who received notification  and then execute redrawing action.
Bug: 173

[WEEX-173][iOS] fix iconfont draw failed sometimes

---

html5/runtime/vdom/operation.js
html5/test/unit/default/vm/vm.js

See this example: http://dotwe.org/vue/c479b4f8b2e7243efe1cfed2f442e35a
Even there is an append="tree" on the root element, js framework will send two render directives to native. JS Framework does it on purpose to ensure the performance of sending the first render directive (`createBody`). I think this feature is no longer needed.

[WEEX-183][jsfm] support append tree on root element

---

ios/sdk/WeexSDK/Sources/Bridge/WXBridgeMethod.m
ios/sdk/WeexSDK/Sources/Bridge/WXModuleMethod.m

Fix the problem that getting `nil` return value when weex api validation is failed beofre invoking.

fix no return value problem when validation is failed.

---

ios/sdk/WeexSDK/Sources/Utility/WXUtility.m

In iOS SDK WXUtility.m file, the #import <coreText/CoreText.h> header file  written error

#import <coreText/CoreText.h>   ==>   #import <CoreText/CoreText.h>

---

android/sdk/src/main/java/com/taobao/weex/utils/ImageDrawable.java

PaintDrawable will crash on Api 21
crash stack:
SIGSEGV(SEGV_MAPERR):
#00 pc 000b0a4e /system/vendor/lib/egl/libGLESv2_adreno.so [armeabi-v7a::98aa079c3b61e1d8483bc6915a4ea80f]
#1 pc 000b12b3 /system/vendor/lib/egl/libGLESv2_adreno.so (oxili_tile_texture+282) [armeabi-v7a::98aa079c3b61e1d8483bc6915a4ea80f]
#2 pc 00087d9b /system/vendor/lib/egl/libGLESv2_adreno.so [armeabi-v7a::98aa079c3b61e1d8483bc6915a4ea80f]
#3 pc 00089b31 /system/vendor/lib/egl/libGLESv2_adreno.so (rb_texture_update_hw_subimage+4220) [armeabi-v7a::98aa079c3b61e1d8483bc6915a4ea80f]
#4 pc 0008ad35 /system/vendor/lib/egl/libGLESv2_adreno.so (rb_texture_loadimage+218) [armeabi-v7a::98aa079c3b61e1d8483bc6915a4ea80f]
#5 pc 00065dab /system/vendor/lib/egl/libGLESv2_adreno.so (TexImageLoad+234) …

fix api 21 PaintDrawable Crash

---

runtime/api/WeexInstance.js

Using native `Proxy` will cause strange behavior in some old mobile devices. They offered the `Proxy` object but the behavior is not exactly same as the spec.

[jsfm] Stop using ES6 Proxy to require a module

---

android/sdk/src/main/java/com/taobao/weex/common/Constants.java
android/sdk/src/main/java/com/taobao/weex/utils/FontDO.java
android/sdk/src/main/java/com/taobao/weex/utils/TypefaceUtil.java

- support `url('data:font/truetype;charset=utf-8;base64,...')` to import font-face
- change the font file cache directory from external storage to application cache
Testcase:
http://dotwe.org/vue/6472fc77dff5afda68864c070643f5ce

[WEEX-203][Android] base64 font-face support

---

android/sdk/src/main/java/com/taobao/weex/adapter/DefaultUriAdapter.java
android/sdk/src/main/java/com/taobao/weex/ui/component/WXImage.java
android/sdk/src/test/java/com/taobao/weex/adapter/DefaultUriAdapterTest.java

[WEEX-212][android] When PlaceHolder is empty, should not use rewrite

[WEEX-212][android] When PlaceHolder is empty, should not use rewrite

---

ios/sdk/WeexSDK/Sources/Component/RecycleList/WXRecycleListComponent.m

recycle-list scroll orientation support
testcase:http://dotwe.org/vue/08b5618c05bd544c0c095c7c1946fbd4

[WEEX-215][iOS] recycle-list scroll orientation support

---

android/sdk/src/main/java/com/taobao/weex/WXSDKEngine.java
android/sdk/src/main/java/com/taobao/weex/dom/action/Actions.java
android/sdk/src/main/java/com/taobao/weex/dom/action/AnimationAction.java
android/sdk/src/main/java/com/taobao/weex/ui/animation/WXAnimationModule.java
android/sdk/src/main/java/com/taobao/weex/utils/WXReflectionUtils.java
android/sdk/src/test/java/com/taobao/weex/ui/animation/WXAnimationModuleTest.java
android/sdk/src/test/java/com/taobao/weex/utils/WXReflectionUtilsTest.java

[WEEX-216][android] WXAnimation Fix Memory Leak and performance improve

[WEEX-216][android] WXAnimation Fix Memory Leak and performance improve

---

android/sdk/src/main/java/com/taobao/weex/common/Constants.java
android/sdk/src/main/java/com/taobao/weex/dom/WXRecyclerDomObject.java
android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java
android/sdk/src/main/java/com/taobao/weex/ui/component/list/GapItemDecoration.java
android/sdk/src/main/java/com/taobao/weex/ui/component/list/WXListComponent.java
android/sdk/src/main/java/com/taobao/weex/ui/component/list/template/WXRecyclerTemplateList.java

1、support leftGap and rightGap for waterfall
http://dotwe.org/vue/6b97a748789aa809c8d86e499ca74978
http://dotwe.org/vue/6b97a748789aa809c8d86e499ca74978
http://dotwe.org/vue/bf26aae8a117f76d7d2a8d6790e1b14d
http://dotwe.org/vue/67274235ec95fc402e1b2e6b0a695f29
2、recycle-list's orientation support update attrs
http://dotwe.org/vue/08b5618c05bd544c0c095c7c1946fbd4

[WEEX-218][android] support leftGap and rightGap for waterfall recycle-list's orientation support update attrs

---

android/playground/app/src/main/assets/weex_config_search.json
android/playground/app/src/main/java/com/alibaba/weex/WXApplication.java
android/sdk/src/main/java/com/taobao/weex/InitConfig.java
android/sdk/src/main/java/com/taobao/weex/WXSDKEngine.java
android/sdk/src/main/java/com/taobao/weex/WXSDKManager.java
android/sdk/src/main/java/com/taobao/weex/adapter/ClassLoaderAdapter.java
android/sdk/src/main/java/com/taobao/weex/bridge/WXModuleManager.java
android/sdk/src/main/java/com/taobao/weex/ui/ExternalLoaderComponentHolder.java
android/sdk/src/main/java/com/taobao/weex/ui/SimpleComponentHolder.java
android/sdk/src/main/java/com/taobao/weex/ui/config/AutoScanConfigRegister.java
android/sdk/src/main/java/com/taobao/weex/ui/config/ConfigComponentHolder.java
android/sdk/src/main/java/com/taobao/weex/ui/config/ConfigModuleFactory.java

[WEEX-210][android] Weex Auto Scan Component And Module Discover Mechanism

[WEEX-210][android] Weex Auto Scan Component And Module Discover 

---

android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java

[WEEX-222][android] Sticky header in waterfall is not sticky
http://dotwe.org/vue/8336befdb83e87f127a86f2cfb5a3324

[WEEX-222][android] Sticky header in waterfall is not sticky

---

android/sdk/src/main/java/com/taobao/weex/common/Constants.java
android/sdk/src/main/java/com/taobao/weex/dom/WXDomObject.java
android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
android/sdk/src/main/java/com/taobao/weex/ui/view/gesture/WXGesture.java

[WEEX-228][android] ShouldStopPropagation Use ShortName StopPropagation

[WEEX-228][android] ShouldStopPropagation Use ShortName StopPropagation

---

android/sdk/src/main/java/com/taobao/weex/common/Constants.java
android/sdk/src/main/java/com/taobao/weex/dom/WXTextDomObject.java

Set whether the text includes extra top and bottom padding to make room for accents that go above the normal ascent and descent. The default is `false`.
Testcase:
http://dotwe.org/vue/9272973e92c60b4a12fc8835059d1528

[Android] Add property include-font-padding to text

---

ios/sdk/WeexSDK/Sources/Component/WXTextComponent.m

you can specify an attribute enableCopy='true' to enable the copy action
by long press gesture, default is disable.
try case : http://dotwe.org/vue/77b7d735efaf55d6b84c5c8fb5196bd9

[WEEX-219][iOS]support copy action for text component

---

ios/sdk/WeexSDK/Sources/Component/WXVideoComponent.h
ios/sdk/WeexSDK/Sources/Component/WXVideoComponent.m

+ [iOS] add WXVideoComponent poster feature and add support "poster" attribute to <video>
testcase: http://dotwe.org/vue/4bf373d06d3b8021441a88b7f841ef3b
feature:241

[WEEX-241][iOS] add WXVideoComponent "poster" attribute

---

ios/sdk/WeexSDK/Sources/Component/WXListComponent.m
ios/sdk/WeexSDK/Sources/Component/WXRefreshComponent.h
ios/sdk/WeexSDK/Sources/Component/WXRefreshComponent.m
ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.m
ios/sdk/WeexSDK/Sources/Protocol/WXScrollerProtocol.h

Currently WXListComponent data update only supports insertRows. This can't be satisfied under some drop-down loading scenes. For example, the pulldown load needs to be positioned to the original position. When the tableView is still decaling and inserts and tries to fix the position, the cell will blink. Because when deceiring, the externally modified contentOffset will be re-edited by the internal implementation of tableView, altering contentOffset alternately will cause flicker problems. If you use the tableView reloadData this is not a problem, so you need to support the WXListComponent in the drop-down restore location scene to add the reload attribute.
feat：270
Please makes sure that these checkboxes are checked before submitting your …

[WEEX-270][iOS]WXListComponent should add reload type of data update

---

android/sdk/src/main/java/com/taobao/weex/common/Constants.java
android/sdk/src/main/java/com/taobao/weex/ui/component/WXSwitch.java
android/sdk/src/main/java/com/taobao/weex/ui/view/WXSwitchView.java

Hi, It's solution to support setting color for `<switch>` component in android. And the api was according to [ios design](https://github.com/apache/incubator-weex/pull/1076), a slight difference is `<switch>` can accept 4 attributes in android:
||android|ios|
|---|---|---|
|tint-color|√|√|
|on-tint-color|√|√|
|thumb-tint-color|√|√|
|on-thumb-tint-color|√|×|
Weex Vue Demo: [http://dotwe.org/vue/e9d87730e016bec01225e546ff10ef0d](http://dotwe.org/vue/e9d87730e016bec01225e546ff10ef0d)

[Weex-260][android]switch supports setting color

---

ios/sdk/WeexSDK/Sources/Protocol/WXImgLoaderProtocol.h

parameter 'progressBlock:' not found in the function declaration [-Werror,-Wdocumentation]
* @param progressBlock: A block called while the download start
^~~~~~~~~~~~~~
错别字修改、新 demo、较小的 bugfix、甚至较大的功能都可以直接提到 `master` 分支；

Fix compile problem. 'progressBlock:' not found in the function declaration [-Werror,-Wdocumentation]

---

ios/sdk/WeexSDK/Sources/Layout/WXComponent+Layout.m
ios/sdk/WeexSDK/Sources/Utility/WXConvert.h
ios/sdk/WeexSDK/Sources/Utility/WXConvert.m
ios/sdk/WeexSDKTests/WXConvertTests.m

Update WXComponent+layout.m to support CSS "direction:rtl".
Few languages such as Arabic, Hebrew, or Persian are written from Right to Left, but weex not support RTL layouts. To handle them. Since this PR merged, we can use weex for RTL languages.
Modified WXComponent+Layout.m:
1.set direction value to  cssNode
2.setNeedLayout changed to trigger sibling component recalculate cssNode->layout
Modified WXConvert.h/m:
add convert for "direction"
Modified WXConvertTests.m:
add Tests for convert direction

[WEEX-282][iOS] update layout system to support rtl direction

---

ios/sdk/WeexSDK/Sources/Component/WXImageComponent.m

From iOS 11, NSPhotoLibraryAddUsageDescription is required in info.plist to save image to album.
Bug [297](https://issues.apache.org/jira/browse/WEEX-297)

[WEEX-297][iOS] fix iOS 11 save image permission

---

android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
android/sdk/src/main/java/com/taobao/weex/ui/module/WXTimerModule.java

fix nullPointException on multithreading case。

[WEEX-303] [Android] fix nullPoint

---

ios/sdk/WeexSDK/Sources/Component/WXTextComponent.h
ios/sdk/WeexSDK/Sources/Component/WXTextComponent.m
ios/sdk/WeexSDK/Sources/Layout/Layout.c
ios/sdk/WeexSDK/Sources/Layout/WXComponent+Layout.m

* [WEEX-313][iOS]fix RTL issue
fix FB layout engine bug to resolve 
1. when "direction:rtl" the layout performance is not so stable
update WXTextComponent to resolve Text can not inherit the CSS "direction:rtl"

* [WEEX-313][iOS]fix RTL issue

---

android/sdk/src/main/java/com/taobao/weex/ui/view/gesture/WXGesture.java

[WEEX-299][android] Touch event will transmit to next layer, requestDisallowInterceptTouchEvent should be reset for every touch event

[WEEX-299][android] Touch event will transmit to next layer, requestDisallowInterceptTouchEvent should be reset for every touch event

---

android/sdk/src/main/java/com/taobao/weex/ui/SimpleComponentHolder.java

weex_enchane throw exception, weex should catch the exception and not  effect other component and weex sdk.  [WEEX-325][android] Some MeiZhu Mobole throw NoClassDefFoundError: android/support/design/widget/AppBarLayout$OnOffsetChangedListener

[WEEX-325][android] Some MeiZhu Mobole throw NoClassDefFoundError: android/support/design/widget/AppBarLayout$OnOffsetChangedListener

---

android/sdk/src/main/java/com/taobao/weex/ui/component/WXVContainer.java
android/sdk/src/main/java/com/taobao/weex/utils/BoxShadowUtil.java
test/pages/css/border.vue

Hi ~ I found some problem in Android side when i use box-shadow. Look that:
**In H5 side:**
**In iOS side:**
**In Android side:**
Now, you see the bug.
The box-shadow style should cover box's padding and border when render the shadow. But Android side is different from the iOS and H5 side.
These change fix this Bug.
This is a test case. [android-bugfix-boxshadow-testcase](http://dotwe.org/vue/4ab90f1cae7c5313c31ab4316b306a6e)

*[Android] box-shadow size should cover padding and border

---

ios/sdk/WeexSDK/Sources/Module/WXAnimationModule.m

Because of a very old mistake, when parsing the transform property, the error scaleY is parsed
You can see demo in http://dotwe.org/vue/95a7067fde100e6b8f5219d4bf1913c3

[WEEX-343] [iOS] Failure of "scaleY" on animationModule

---

build/build.js
build/config.js
package.json
runtime/entries/polyfill.js

Build a standalone polyfill package which can be used in some outdated versions of iOS.
The `weex-polyfill` package contains:
+ `Array.from`
+ `Object.assign`
+ `Object.setPrototypeOf`
+ `Promise`

[jsfm] Support to build a standalone polyfill package

---

runtime/bridge/TaskCenter.js

In some cases, the `options` argument of a module call may contain functions and complex structures, such as the `weex.imporsScript` api. The value of the `options` should be deep normalized.

[jsfm] Deep normalize the options when calling native module

---

weex_core/Source/android/jsengine/multiprocess/WeexProxy.cpp
weex_core/Source/android/jsengine/multiprocess/WeexProxy.h

serializer will be freed after framework inited finished.
So if we use it for re initialize. Will cause null ptr.
Bug: WEEX-360
JIRA  https://issues.apache.org/jira/browse/WEEX-360

[WEEX-360] [Android] Fix crash when reinit framework

---

ios/sdk/WeexSDK.xcodeproj/project.pbxproj
ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.mm
ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
ios/sdk/WeexSDK/Sources/Protocol/WXPageEventNotifyEvent.h
ios/sdk/WeexSDK/Sources/View/WXRootView.m

[WEEX-375][iOS] add Protocol for PageEventNotifyEvent
the handler will called in situations such as rootView clicked,
scrollView scrolled,a new page start and ended.
feature:375

[WEEX-375][iOS] add Protocol for PageEventNotifyEvent

---

ios/sdk/WeexSDK/Sources/Component/WXTransform.m

The problem is because when parsing transform, the component thread wait until main thread finish its work with  main thread still waiting component thead work done.
You can try demo on this dotwe.http://dotwe.org/vue/caeb8e370f1ddd7d249263c153ea7694

[WEEX-413] [iOS] Fix when main thread parse transform cause deadlock

---

weex_core/Source/CMakeLists.txt
weex_core/Source/android/bridge/impl/native_render_object_utils_impl_android.cpp
weex_core/Source/core/parser/dom_wson.cpp
weex_core/Source/core/render/action/render_action_appendtree_createfinish.cpp
weex_core/Source/core/render/node/render_appbar.h
weex_core/Source/core/render/node/render_list.h
weex_core/Source/core/render/node/render_mask.h
weex_core/Source/core/render/node/render_object.h
weex_core/Source/core/render/node/render_scroller.h
weex_core/Source/core/render/page/render_page.cpp
weex_core/Source/core/render/page/render_page.h

- rm jni code from weexcore
- jni.h
- bridge_impl_android.h
- android/base/string/string_utils.h
- android/base/log_utils.h
- edit cmake compile option 
- use `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")` to replace `add_compile_options(-std=c++11)`  (see: https://blog.csdn.net/10km/article/details/51731959)
- for wson error: invalid arguments "-std=c++11" not allowed with 'C

[WEEX-433] [core] rm jni code from weexcore

---

android/sdk/src/main/java/com/taobao/weex/WXEnvironment.java
android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
android/sdk/src/main/java/com/taobao/weex/bridge/WXParams.java
android/sdk/src/main/java/com/taobao/weex/utils/WXFileUtils.java
android/sdk/src/main/java/com/taobao/weex/utils/WXSoInstallMgrSdk.java
weex_core/Source/android/jsengine/multiprocess/WeexJSConnection.cpp
weex_core/Source/android/jsengine/multiprocess/WeexProxy.cpp
weex_core/Source/android/jsengine/multiprocess/WeexProxy.h
weex_core/Source/core/render/node/render_object.h

[WEEX-454][Android] fix can't find libweexjss when deploy
fix can't find libweexjss when deploy
Bug: WEEX-454
https://issues.apache.org/jira/projects/WEEX/issues/WEEX-454

[WEEX-454][Android] fix can't find libweexjss when deploy

---

ios/sdk/WeexSDK/Sources/View/WXComponent+ViewManagement.mm

only transform ONCE when incoming styles has both `transform` and `transformOrigin`, and use input `transformOrigin` replace `self.styles[@"transformOrigin"]`

[WEEX-453][iOS] transform/transformOrigin conflict when updateStyles

---

android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
android/sdk/src/main/java/com/taobao/weex/ui/action/GraphicActionAddElement.java
android/sdk/src/main/java/com/taobao/weex/ui/action/GraphicActionMoveElement.java
android/sdk/src/main/java/com/taobao/weex/ui/action/GraphicActionRemoveElement.java
android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
android/sdk/src/main/java/com/taobao/weex/ui/module/WXTimerModule.java

- use jsCreateFinish flag to replace mEnd
- call onElementChanged()  just in add/rm element action
- proteted mWXSDKInstance.getWXPerformance() null ptr

[WEEX-465][Android]fix performance point interactionTime record bug

---

HOW-TO-BUILD.md
README.md

Update the dependent version of Node.js to keep consistent with [package.json](https://github.com/apache/incubator-weex/blob/939be31e6f37340f81fa396df7bbec27e50c7c15/package.json#L34-L36). (To build js framework correctly, the version of Node.js should be higher than `v7.6.0`.)

[build] update dependent version of node.js

---

LICENSE

Fix the file path in the license statement. Some codes under the `runtime/frameworks/legacy/core` path are from the Vue.js 1.0.

[doc] update license statement about the vuejs codes

---

scripts/generate_apache_release.sh

Use Mac sed to generate release source packages instead of using
gnu-sed, if you installed gnu-sed on your Mac.

[Relese] Fixed the sed issue

---

runtime/api/init.js

CheckList:
This is a API for internal usage, so no test and no doc update.

[WEEX-445][jsfm] export requireModule to global

---

ios/sdk/WeexSDK/Sources/Component/WXTransform.m

When third-party developer(no-taobao) parsing transform parameter, they may get failure of transform's animation.

[WEEX-484][iOS] Failure of parsing transform parameter when in third-party environment

---

build/build.js
package.json

The `rollup-watch` package is deprecated and it will cause error:
```
$ npm run dev:jsfm
(node:40511) UnhandledPromiseRejectionWarning: TypeError: Cannotread property 'map' of undefined
```
Using `rollup.watch` to fix this issue.

* [jsfm] using rollup.watch to fix dev build

---

ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.m

Try to fix a crash:
Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndexedSubscript:]: index 0 beyond bounds for empty array'
Last Exception Backtrace:
0 CoreFoundation __exceptionPreprocess :228 (in CoreFoundation)
1 _objc_exception_throw :56
2 CoreFoundation _CFThrowFormattedException :112 (in CoreFoundation)
3 -[__NSArrayM objectAtIndexedSubscript:] :192 (in CoreFoundation)
4 -[WXThreadSafeMutableArray objectAtIndex:] WXThreadSafeMutableArray.m:0
5 -[WXBridgeContext topInstance] WXBridgeContext.m:0
6 +[WXSDKEngine topInstance] WXSDKEngine.m:277

[WEEX-524][iOS] Try to fix a crash operating mutable array in multi-thread

---

runtime/api/init.js
runtime/bridge/debug.js

Stop tracking the DSL type in js framework.

[WEEX-461][jsfm] Remove useless trace function in js framework

---

runtime/bridge/CallbackManager.js
runtime/vdom/Element.js

In practice, most js error happens in the js bundle code, which could be a callback function or event handler of js framework. Add try catch on them could make js framework more stable and reduce js crashes.

[jsfm] add try catch for callback function and event handler

---

scripts/beta-branchoff.sh
scripts/common.sh

The script beta-branchoff.sh is to automate the weekly beta release
branch-off procedure. It helps to identify which is the latest
non-RC version number and release a new beta branch with the number.
The branch will be branched-off from origin/master and will be pushed
onto apache after its creation.
A valid beta version number looks like: 0.18.0-beta1
A Valid beta branch name looks like: 0.18.0-beta1-180720
common.sh provides some useful gadgets for the scripts and can be
shared across scripts.

[WEEX-525] Created the automate beta branch-off scripts.

---

runtime/api/WeexInstance.js

JS Framework has a cache strategy for module proxies which is good for performance. But it also a potential reason for the memory leak.

[WEEX-547][jsfm] Remove module proxy cache of weex.requireModule

---

ios/sdk/WeexSDK/Sources/Component/RecycleList/WXCellSlotComponent.h
ios/sdk/WeexSDK/Sources/Component/RecycleList/WXCellSlotComponent.mm
ios/sdk/WeexSDK/Sources/Component/RecycleList/WXComponent+DataBinding.mm
ios/sdk/WeexSDK/Sources/Component/RecycleList/WXRecycleListComponent.h
ios/sdk/WeexSDK/Sources/Component/RecycleList/WXRecycleListComponent.mm
ios/sdk/WeexSDK/Sources/Component/WXComponent_internal.h
ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.mm
ios/sdk/WeexSDK/Sources/Controller/WXBaseViewController.m
ios/sdk/WeexSDK/Sources/Model/WXComponent.mm
ios/sdk/WeexSDK/Sources/Module/WXAnimationModule.m

[WEEX-502][iOS] Weex Template List Support Animation & queryElement
Recycle List is now support animation.transitionPostion, scollTo, queryElement.
You can try demo on http://dotwe.org/vue/0d1da9d9673d6133fbaf884f861a7b1a

[WEEX-502][iOS] Weex Template List Support Animation & queryElement

---

android/commons/src/main/java/com/alibaba/weex/commons/adapter/ImageAdapter.java
android/playground/app/src/main/java/com/alibaba/weex/WXApplication.java
android/playground/app/src/main/java/com/alibaba/weex/extend/adapter/ApmGenerator.java
android/playground/app/src/main/java/com/alibaba/weex/extend/adapter/WXInstanceApmAdapter.java
android/sdk/src/main/java/com/taobao/weex/InitConfig.java
android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
android/sdk/src/main/java/com/taobao/weex/WXSDKManager.java
android/sdk/src/main/java/com/taobao/weex/adapter/DefaultWXHttpAdapter.java
android/sdk/src/main/java/com/taobao/weex/bridge/WXBridge.java
android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
android/sdk/src/main/java/com/taobao/weex/common/WXImageStrategy.java
android/sdk/src/main/java/com/taobao/weex/common/WXPerformance.java
android/sdk/src/main/java/com/taobao/weex/performance/IApmGenerator.java
android/sdk/src/main/java/com/taobao/weex/performance/IWXApmMonitorAdapter.java
android/sdk/src/main/java/com/taobao/weex/performance/WXInstanceApm.java
android/sdk/src/main/java/com/taobao/weex/ui/RenderContextImpl.java
android/sdk/src/main/java/com/taobao/weex/ui/WXRenderManager.java
android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
android/sdk/src/main/java/com/taobao/weex/ui/component/WXEmbed.java
android/sdk/src/main/java/com/taobao/weex/ui/component/WXImage.java
android/sdk/src/main/java/com/taobao/weex/ui/component/WXScroller.java
android/sdk/src/main/java/com/taobao/weex/ui/component/list/WXCell.java
android/sdk/src/main/java/com/taobao/weex/ui/module/WXTimerModule.java

apm solution for weexperformance
- playground test case
- sdk add performance point 
- scroller, 
- img is recycle 
- cell is recycle
- large img record
- net/img request 
-  ....

[WEEX-545] [Android] apm for weex perofrmance

---

weex_core/Source/base/ViewUtils.h

This commit may trigger the mistake of Layout which need a better solution.

Revert "* [android] Use rint on getFloatByViewport."

---

android/sdk/src/main/java/com/taobao/weex/WXSDKEngine.java

Switch all the global modules in weex_sdk to instance modules.
(cherry picked from commit 77fa800)

* [Android] Fix module memroy leak. 

---

ios/playground/WeexDemo.xcodeproj/project.pbxproj
ios/playground/WeexDemo/AppDelegate.m
ios/playground/WeexDemo/extend/handler/WXApmGeneratorImpl.h
ios/playground/WeexDemo/extend/handler/WXApmGeneratorImpl.m
ios/playground/WeexDemo/extend/handler/WXApmImpl.h
ios/playground/WeexDemo/extend/handler/WXApmImpl.m
ios/playground/WeexDemo/extend/handler/WXImgLoaderDefaultImpl.m
ios/sdk/WeexSDK.xcodeproj/project.pbxproj
ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.m
ios/sdk/WeexSDK/Sources/Component/WXCellComponent.mm
ios/sdk/WeexSDK/Sources/Component/WXImageComponent.m
ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.mm
ios/sdk/WeexSDK/Sources/Component/WXVideoComponent.m
ios/sdk/WeexSDK/Sources/Handler/WXNavigationDefaultImpl.m
ios/sdk/WeexSDK/Sources/Layout/WXComponent+Layout.mm
ios/sdk/WeexSDK/Sources/Manager/WXBridgeManager.m
ios/sdk/WeexSDK/Sources/Manager/WXComponentManager.mm
ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.h
ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
ios/sdk/WeexSDK/Sources/Model/WXSDKInstance_performance.h
ios/sdk/WeexSDK/Sources/Module/WXTimerModule.m
ios/sdk/WeexSDK/Sources/Monitor/WXMonitor.h
ios/sdk/WeexSDK/Sources/Performance/WXApmForInstance.h
ios/sdk/WeexSDK/Sources/Performance/WXInstanceApm.m
ios/sdk/WeexSDK/Sources/Protocol/WXApmProtocol.h
ios/sdk/WeexSDK/Sources/Utility/WXUtility.h
ios/sdk/WeexSDK/Sources/Utility/WXUtility.m
ios/sdk/WeexSDK/Sources/WeexSDK.h

- use new protocol `WXApmProtocol ` to record weex page performance
- record stage (download -> success/falied -> renderStart -> fsRenderTime -> interactionTime -> destroy)
- record property , such as wxInstanceType(page/embed) ,wxParentPage(for embed) ...
- record stats : wxBundleSize、wxMaxDeepVDomLayer、wxCellUnReUseCount
- reord event : gc、press home  and so on (not impl now)
- deprecated `WXMonitor`
- more performance point 
- add `WXApmGeneratorImpl` (WXApmProtocol impl case ) in demo

[WEEX-552][iOS] apm for ios

---

android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
android/sdk/src/main/java/com/taobao/weex/common/WXErrorCode.java
android/sdk/src/main/java/com/taobao/weex/performance/WXInstanceApm.java

1. bug fix ,in multiThread case ,HashMap.get may cause null point when resize
2. add extInfo of jsFrame init failed (initTime and extMsg)

[WEEX-560][Android] fix null point of apm && report initJSFM fail info

---

android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java

https://issues.apache.org/jira/browse/WEEX-565
[WEEX-565][Android] do not set view's id if there is a id in this view
do not set view's id if there is a id in this view
Bug: WEEX-565

[WEEX-565][Android] do not set view's id if there is a id in this view

---

ios/sdk/WeexSDK/Sources/Utility/WXUtility.m

[WEEX-563][iOS] fix the attribute of linear-gradient  on iOS 
https://issues.apache.org/jira/projects/WEEX/issues/WEEX-563?filter=allopenissues

[WEEX-563][iOS] fix the attribute of linear-gradient on iOS

---

ios/playground/Podfile
ios/playground/WeexDemo/Scanner/WXScannerVC.m
ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.m
ios/sdk/WeexSDK/Sources/Component/RecycleList/WXComponent+DataBinding.mm
ios/sdk/WeexSDK/Sources/Engine/WXSDKEngine.m
ios/sdk/WeexSDK/Sources/Manager/WXBridgeManager.m

An old bug with no consider of recycle list' case.

[WEEX-548][iOS] Weex devtool can not debug recycle list

---

android/sdk/src/main/java/com/taobao/weex/WXEnvironment.java
android/sdk/src/main/java/com/taobao/weex/utils/WXSoInstallMgrSdk.java

https://issues.apache.org/jira/browse/WEEX-566
[WEEX-566][Android] add jsb version file to make jsb.so can update
add jsb version file to make jsb.so can update
Bug: WEEX-566

[WEEX-566][Android] add jsb version file to make jsb.so can update

---

android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java

Do not call clearOnScrollListeners when create RecyclerView, because PagerSnapHelper will set OnScrollListener and need to rely on it.

[WEEX-575][Android] fix ListComponent pagingEnabled bug

---

android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
android/sdk/src/main/java/com/taobao/weex/performance/WXInstanceExceptionRecord.java
android/sdk/src/main/java/com/taobao/weex/utils/WXExceptionUtils.java

- rm useless code
- add more info to report for emptyException

[WEEX-590][Android] add more info to report

---

ios/sdk/WeexSDK/Sources/Component/WXImageComponent.m

bugfix about can not show correct borderRadius
you can see deme here:http://rax.alibaba-inc.com/playground/f52475b6-a7b6-4b8d-9293-16ebe803ba69

[WEEX-593][iOS]image can not show correct borderRadius

---

ios/sdk/WeexSDK/Sources/Performance/WXInstanceApm.m

- limit 2s between destroy and render(url) 
- limit 1s between destroy and render(template) 
same logic (Android):https://github.com/apache/incubator-weex/pull/1475

[WEEX-596][iOS]fix report empty when too fast between render and destroy

---

ios/sdk/WeexSDK/Sources/Component/WXEditComponent.mm

[iOS] Fix on iOS9, text cannot be deleted when exceeds maxLength.

---

android/sdk/src/main/java/com/taobao/weex/utils/FontDO.java

issue: https://issues.apache.org/jira/browse/WEEX-558
use costumer fontFace like this:
```
const domModule = weex.requireModule('dom')
domModule.addRule('fontFace', {
'fontFamily': "iconfont2",
'src': "url('http://at.alicdn.com/t/font_1469606063_76593.ttf')"
})
```
double quotes is outside for font file url,  it will make an error with lint.
when set as this, the font face does not work with android:
```
'src': 'url("http://at.alicdn.com/t/font_1469606063_76593.ttf")'
```
it cause by [FontDO](https://github.com/apache/incubator-weex/blob/master/android/sdk/src/main/java/com/taobao/weex/utils/FontDO.java#76)

[WEEX-558][Android] Font file url compatible with ' and "

---

android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
android/sdk/src/main/java/com/taobao/weex/common/WXErrorCode.java
android/sdk/src/main/java/com/taobao/weex/common/WXJSExceptionInfo.java
android/sdk/src/main/java/com/taobao/weex/performance/WXInstanceApm.java
android/sdk/src/main/java/com/taobao/weex/performance/WXInstanceExceptionRecord.java
android/sdk/src/main/java/com/taobao/weex/utils/WXExceptionUtils.java

* [Android] writescreen check limit stage and 3s js execute time
* [Android] add writescreen swtich
* [Android] monitor download failed
* [Android] when download success,report download stage

[WEEX-606][Android]fix monitor data

---

android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
android/sdk/src/main/java/com/taobao/weex/common/WXErrorCode.java
android/sdk/src/main/java/com/taobao/weex/performance/WXInstanceExceptionRecord.java
android/sdk/src/main/java/com/taobao/weex/ui/component/WXEmbed.java

* [Android] deprece old white screen check logic
* [Android] set flag to excptionReporter when embed receive exception
* [Android] check empty sceen by action

[WEEX-608][Android] apm monitor logic modify

---

runtime/bridge/TaskCenter.js
runtime/shared/env/console.js
runtime/shared/utils.js
runtime/vdom/Document.js
runtime/vdom/Element.js

Notable changes:
* Move log level check to `shared/utils.js`.
* Add more debug logs for
* `createBody`
* `createElement`
* `appendChild`
* `insertAfter`
* `insertBefore`
* `removeChild`
* `addEvent`
* `removeEvent`
* `fireEvent`
* `destroy`
The log level can be controlled by native SDK, and those debug logs will NOT be print in the release version.

[jsfm] Add more debug logs for vdom operation

---

android/sdk/src/main/java/com/taobao/weex/ui/component/WXScroller.java

https://issues.apache.org/jira/browse/WEEX-619
[WEEX-619][Android] Keep Page index if pageEnabled is enabled
Keep Page index if pageEnabled is enabled
Bug: WEEX-619

keep pageIndex if pageEnabled seted

---

ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.m
ios/sdk/WeexSDK/Sources/Component/RecycleList/WXComponent+DataBinding.mm
ios/sdk/WeexSDK/Sources/Component/RecycleList/WXJSASTParser.h
ios/sdk/WeexSDK/Sources/Component/RecycleList/WXJSASTParser.mm
ios/sdk/WeexSDK/Sources/Component/WXComponent_internal.h
ios/sdk/WeexSDK/Sources/Component/WXTextComponent.mm
ios/sdk/WeexSDK/Sources/Model/WXComponent.mm
ios/sdk/WeexSDK/Sources/Module/WXAnimationModule.m
ios/sdk/WeexSDK/Sources/Utility/WXLog.m
weex_core/Source/core/render/node/render_object.cpp

Fix leaks crashes 0927

---

ios/sdk/WeexSDK/Sources/Monitor/WXMonitor.m

- when set firstScreenRenderTime ,reporter has stop record data.

[WEEX-629][iOS] fix report firstScreenRenderTime failed

---

android/sdk/src/main/java/com/taobao/weex/InitConfig.java
android/sdk/src/main/java/com/taobao/weex/WXSDKEngine.java
android/sdk/src/main/java/com/taobao/weex/WXSDKManager.java
android/sdk/src/main/java/com/taobao/weex/adapter/IWXJsFileLoaderAdapter.java
android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java

https://issues.apache.org/jira/browse/WEEX-628
[WEEX-628][Android] add jsframework load adapter
add jsframework load adapter
Bug: WEEX-628

[WEEX-628][Android] add jsframework load adapter

---

ios/sdk/WeexSDK/Sources/Module/WXAnimationModule.m

[iOS] Protect animation module.

---

android/sdk/src/main/java/com/taobao/weex/common/WXPerformance.java
android/sdk/src/main/java/com/taobao/weex/performance/WXInstanceApm.java

- record renderUnixTimeOrigin use `WXUtils.getFixUnixTime()` to replace `System.currentTimeMillis()`

[WEEX-634][Android] fix old performance record time

---

runtime/vdom/Document.js
runtime/vdom/Node.js

Revert the modification of the destroy logic in #1529 , it may cause breaking change when 
executing `destroyInstance`.

[jsfm] Revert destroy logic modification in #1529

---

android/sdk/src/main/java/com/taobao/weex/ui/WXRenderManager.java
android/sdk/src/main/java/com/taobao/weex/ui/action/BasicGraphicAction.java
android/sdk/src/main/java/com/taobao/weex/ui/action/GraphicActionBatchAction.java
android/sdk/src/main/java/com/taobao/weex/ui/action/GraphicActionBatchBegin.java
android/sdk/src/main/java/com/taobao/weex/ui/action/GraphicActionBatchEnd.java
android/sdk/src/main/java/com/taobao/weex/ui/module/WXDomModule.java

introduce a native batch for dom operations generating from JavaScript
wrap a series of dom operations with beginBatch and endBatch directives, when every V-sync signal comes, we try to ensure that the operations between beginBatch and endBatch can be performed in current V-sync, this policy can drop frames maybe, for our policy dropping frames, we only allow 20 frames at most.
see iOS pull request https://github.com/apache/incubator-weex/pull/1644
feature:648

[WEEX-648][Android]native batch for dom operations generating from JavaScript

---

ios/sdk/WeexSDK/Sources/Manager/WXComponentManager.h
ios/sdk/WeexSDK/Sources/Manager/WXComponentManager.mm
ios/sdk/WeexSDK/Sources/Module/WXDomModule.m

introduce a native batch for dom operations generating from JavaScript
wrap a series of dom operations with beginBatch and endBatch directives, when every V-sync signal comes, we try to ensure that the operations between beginBatch and endBatch can be performed in current V-sync, this policy can drop frames maybe, for our policy dropping frames, we only allow 20 frames at most.
see Android policy pull request #1647 
feature:648

[WEEX-648][iOS]native batch for dom operations generating from JavaScript

---

scripts/build_from_source.sh
scripts/generate_apache_release.sh

Added 'npm run build:rax' to generate Rax precompiled js files, and
updated the build command and generated project for iOS.

[devtool] Updated the Apache release scripts.

---

weex_core/Source/wson/wson_util.cpp

[WEEX-666][Android]Some Emoji emotion not Show On Android 9.0

[WEEX-666][Android]Some Emoji emotion not Show On Android 9.0

---

ios/sdk/WeexSDK/Sources/Bridge/WXCoreBridge.h
ios/sdk/WeexSDK/Sources/Bridge/WXCoreBridge.mm
ios/sdk/WeexSDK/Sources/Bridge/WXJSCoreBridge.mm
ios/sdk/WeexSDK/Sources/Bridge/WXModuleMethod.m
ios/sdk/WeexSDK/Sources/Manager/WXComponentManager.mm
ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
ios/sdk/WeexSDK/Sources/Model/WXSDKInstance_performance.m
ios/sdk/WeexSDK/Sources/Monitor/WXAnalyzerCenter+Transfer.h
ios/sdk/WeexSDK/Sources/Monitor/WXAnalyzerCenter.h
ios/sdk/WeexSDK/Sources/Monitor/WXAnalyzerCenter.m
ios/sdk/WeexSDK/Sources/Monitor/WXMonitor.m
ios/sdk/WeexSDK/Sources/Performance/WXApmForInstance.h
ios/sdk/WeexSDK/Sources/Performance/WXApmForInstance.m

- transfer peformance info to devtool
- add log switch of jsengin/jsfm/weexcore ,to analyze interactionTime

[WEEX-661][iOS] new feature for analyze interaction info (dev_tool)

---

runtime/bridge/CallbackManager.js
runtime/vdom/Element.js

Fix #1798
Javascript exceptions should be handled by native engines, catch them in the js framework will omit some errors and make developers hard to find reasons.

[jsfm] Still throw caught errors in event handler and callback

---

LICENSE
android/playground/app/build.gradle
android/sdk/build.gradle
android/sdk/gradle.properties
android/sdk/proguard-rules.pro
android/sdk/publish.sh
ios/sdk/WeexSDK/Sources/Layout/WXComponent+Layout.h
ios/sdk/WeexSDK/Sources/Layout/WXComponent+Layout.mm
ios/sdk/WeexSDK/Sources/Utility/WXDefine.h
ios/sdk/WeexSDK/Sources/Utility/WXVersion.m
scripts/build_from_source.sh
scripts/generate_apache_release.sh
weex_core/CMakeLists.txt
weex_core/Source/CMakeLists.txt
weex_core/Source/IPC/CMakeLists.txt
weex_core/Source/android/wrap/native_render_object_utils_impl_android.cpp
weex_core/Source/core/data_render/class_factory.cc
weex_core/Source/core/data_render/tokenizer.cc
weex_core/Source/core/layout/flex_enum.h
weex_core/Source/core/layout/layout.h
weex_core/Source/core/layout/style.h
weex_core/Source/third_party/json11/CMakeLists.txt
weex_core/Source/weexjsc_version_script.txt
weex_core/Source/wson/CMakeLists.txt

Merge rc20

---

android/sdk/build.gradle

Specify `weexVersion` from command line using `-PweexVersion`. If there is no such variable in command line, use the version in build.gradle instead.
./gradlew clean assemble -PweexVersion="xxxx"

* [Android] Read weex version from command

---

ios/sdk/WeexSDK/Sources/Component/RecycleList/WXRecycleListComponent.mm
ios/sdk/WeexSDK/Sources/Component/WXListComponent.mm
ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.mm
ios/sdk/WeexSDK/Sources/Utility/WXUtility.h

Fix `scrollStart` and `scrollEnd` can not be triggered when setting scroller's contentOffset.
You can try demo here:
http://dotwe.org/vue/2c26231ee368ac1a28a8b6872456e5a5
http://dotwe.org/vue/6722f649532342b45fea5e44a2b93299

[iOS] Fix `scrollStart` and `scrollEnd` can not be triggered when setting scroller's contentOffset

---

android/sdk/src/main/java/com/taobao/weex/utils/WXLogUtils.java

[WEEX][Android] Bugfix java.lang.NullPointerException: println needs a message  at android.util.Log.println(Log.java:357)at com.taobao.weex.utils.WXLogUtils.log(WXLogUtils.java:80)

[WEEX][Android] Bugfix java.lang.NullPointerException: println needs a message

---

android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java

Use JSON instead of simple string compare to find bundleType
Regular Expression is really slow, there is no reason we should use it.

* [Android] Use JSON to find bundleType

---

android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java

[WEEX][Android] When LoadMoreOffset Not Set  Load More Function Not Fired

[WEEX][Android] When LoadMoreOffset Not Set  Load More Function Not Fired

---

android/sdk/src/main/java/com/taobao/weex/appfram/storage/DefaultWXStorage.java
android/sdk/src/main/java/com/taobao/weex/appfram/storage/WXSQLiteOpenHelper.java

fix a crash for storageModule:
crash stack
java stack
java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:962)
at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:599)
at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
at android.database.sqlite.SQLiteSession.executeForLong(SQLiteSession.java:650)
at android.database.sqlite.SQLiteStatement.simpleQueryForLong(SQLiteStatement.java:125)
at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:886)
at …

Android data base fix

---

ios/sdk/WeexSDK/Sources/Bridge/WXBridgeMethod.m
ios/sdk/WeexSDK/Sources/Utility/WXUtility.h

[iOS] Allow redundant arguments provided for callNative.

---

android/sdk/src/main/java/com/taobao/weex/appfram/storage/DefaultWXStorage.java

try to fix threadpool rejectException when ShutDown

* [Android] try to fix threadpool rejectException when ShutDown

---

android/playground/app/build.gradle
android/playground/app/src/main/java/com/alibaba/weex/WXApplication.java

weex playground add bindingx plugin. 
BindingX provides a way called expression binding for handling complex user interaction with views at 60 FPS.See https://github.com/alibaba/bindingx.

[Weex][android] feat: add bindingx weex plugin

---

android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java

[WEEX][Android] When View Not InstanceOf WXGestureObservable, mGestureType is Null, remove event has none affect,
demo:
http://rax.alibaba-inc.com/playground/e5d4fe01-48d6-4e18-a4d2-f96b63065546

[WEEX][Android] When View Not InstanceOf WXGestureObservable, mGestureType is Null, remove event has none affect,

---

android/sdk/src/main/java/com/taobao/weex/ui/component/WXVContainer.java

[WEEX][Android] Weex Bugfix For Scroller Remove Failed Because Of Edit Of Scroller Touch Event

[WEEX][Android] Weex Bugfix For Scroller Remove Failed Because Of Edit Of Scroller Touch Event

---

android/playground/app/src/main/java/com/alibaba/weex/IndexActivity.java
android/playground/app/src/main/java/com/alibaba/weex/extend/module/WXEventModule.java

For `ActivityCompat.shouldShowRequestPermissionRationale()`, it means your app should display a dialog or something else to explain why you are going to request this permission, and **try again to request the permission**, see https://developer.android.com/training/permissions/requesting and https://github.com/googlesamples/android-RuntimePermissionsBasic/blob/master/Application/src/main/java/com/example/android/basicpermissions/MainActivity.java#L124
For the original code, if the permission was **NOT** granted, the `ContextCompat.checkSelfPermission(mWXSDKInstance.getContext(), Manifest.permission.CAMERA) != PackageManager.PERMISSION_GRANTED` will always returns `true` and `ActivityCompat.shouldShowRequestPermissionRationale((Activity) mWXSDKInstance.getContext(), …

[WEEX-435][android] modify playground app camera runtime permission request behavior

---

android/sdk/src/main/java/com/taobao/weex/layout/measurefunc/TextContentBoxMeasurement.java

This may cause crash if TextContentBoxMeasurement is destroyed and mComponent may be null

* [Android] Fix potential NPE in TextContentBoxMeasurement

---

android/sdk/src/main/java/com/taobao/weex/appfram/storage/DefaultWXStorage.java

[Android]fix storage 异步执行导致service执行异常的问题

---

android/sdk/src/main/java/com/taobao/weex/utils/ImageDrawable.java

Fixed image component anti-alias problem when rendering some non-standard cut image under Android (ios have no such problem)

make android support anti-aliased image

---

android/sdk/src/main/java/com/taobao/weex/ui/component/WXVContainer.java

[WEEX][Android] Only Scroller Use Real View Remove, For List use old logic because On XiaoMi May Not Render Right.

[WEEX][Android] Only Scroller Use Real View Remove, For List use old logic because On XiaoMi May Not Render Right.

---

weex_core/Source/core/render/node/render_list.cpp
weex_core/Source/core/render/node/render_list.h
weex_core/Source/core/render/node/render_object.h

[Android]  Fix Waterfall Can't Change Column Count Bug   https://github.com/apache/incubator-weex/issues/1995
Demo http://dotwe.org/vue/96fcc3687dcfe91f6c5094e482936cc0

[Android]  Fix Waterfall Can't Change Column Count Bug

---

ios/sdk/WeexSDK/Sources/Component/WXRichText.mm

[iOS] Fix richtext creating text view in sub thread.

---

ios/sdk/WeexSDK/Sources/Component/WXImageComponent.m

[iOS] Fix bug that when imagesrc is nil, image loader is still called.

---

android/sdk/src/main/java/com/taobao/weex/ui/component/WXScroller.java

- feture: if scrooler has attr `scrollToBegin=false`,then   scroller will not scroller to begin position auto when content layout change
- doc pr: https://github.com/apache/incubator-weex-site/pull/334

[Android]  add params for scroller to control auto scroller to beginposition

---

runtime/api/component.js
runtime/api/module.js
runtime/frameworks/legacy/app/register.js
runtime/shared/utils.js
runtime/vdom/WeexElement.js

Add safe type check for the `registerModules` and `registerComponents` API, make sure it won't throw js error even if the parameter has an invalid type.

[jsfm] add type check for register modules and components

---

android/sdk/src/main/java/com/taobao/weex/ui/component/WXScroller.java
ios/sdk/WeexSDK/Sources/Component/WXScrollerComponent.mm

Since i start use Rax UI Framework - Nuke, i found i can't scroll to correct element on RTL layout.
Because Nuke will add a  container div between scroller and scroller's child element. 
ScrollToElement only can scroll to the direct child element on RTL direction in the online version，
now i fix the problem，scrollToElement can scroll to indirect child element.
BTW. i found scroll to begin let front-end engineer confused, now i found a better way to key offset when layout direction changed.
Nuke DEMO： https://jsplayground.taobao.org/raxplayground/5bf4b469-8eb1-4f5d-91df-912cd085ab7b
Direction chang DEMO：http://dotwe.org/vue/09cb6e35412f96c25c423fd50a929597

[iOS][Android] fix scrollToElement performance incorrect  offset

---

ios/sdk/WeexSDK/Sources/Module/WXAnimationModule.m

[iOS] Fix animation module crash when working with layout.

---

ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m

When convert a nonnull NSString to NSURL failed, should try url encode.
issue detail: #2135

[iOS] Fix <image> can't display picture with url which contains Chinese words. (#2135)

---

ios/sdk/WeexSDK/Sources/Component/WXComponent_internal.h
ios/sdk/WeexSDK/Sources/Display/WXComponent+Display.m

The point is `_needsDrawBorder` in [WXComponent needsDrawRect]. 
When the border width changes to 0 from a non-zero value, it calls `... --> display --> _willDisplayLayer: --> needsDrawRect --> ...`. Then the border drawing is according to the result of  `needsDrawRect`. 
```
- (void)_willDisplayLayer:(CALayer *)layer
{
...
BOOL needsDrawRect = [self needsDrawRect];
WXDisplayBlock displayBlock;
if (_useCompositing) {
displayBlock = [self _compositeDisplayBlock];
} else {
displayBlock = [self _displayBlock];
}
WXDisplayCompletionBlock completionBlock = [self _displayCompletionBlock];
if (!displayBlock || !needsDrawRect) {
if (completionBlock) {
completionBlock(layer, NO);
}
return;
}
...
}
```
And the result of `needsDrawRect` is related on the result of `_needsDrawBorder`.
```objc
- …
```

[iOS] Fix the border of view hasn't gone after changing border width to 0 dynamically; (#2153)

---

ios/sdk/WeexSDK/Sources/Component/WXComponent_internal.h
ios/sdk/WeexSDK/Sources/Events/WXComponent+Events.m
ios/sdk/WeexSDK/Sources/Model/WXComponent.mm

[iOS] Fix custom component receive touch events when root componet has click event.
* bugfix: If a root component has click event, the custom component inside can't receive touch events.

[iOS] Fix custom component receive touch events.

---

ios/sdk/WeexSDK/Sources/Component/WXLoadingIndicator.m

* feature: Support to use loading-indicator separately. Use animating property to control.
* doc pr: apache/incubator-weex-site#363
* demo: http://dotwe.org/vue/15b0ac96db6e1837ef5c27c0345b7fb6

[iOS] Support to use loading-indicator separately.

---

ios/sdk/WeexSDK/Sources/Component/WXRichText.mm

* feature: If a span is clicked which is in an a-label of a richtext component, an itemclick event will be fired.
* demo: http://editor.weex.io/p/sunshl/Contribute/commit/b21e1133830b48767c6d00d712e415b2
* doc pr: apache/incubator-weex-site#362

[iOS] Fire event when span within an a-label is clicked.

---

android/sdk/src/main/java/com/taobao/weex/common/Constants.java
android/sdk/src/main/java/com/taobao/weex/ui/component/WXLoadingIndicator.java

* feature: Support to use loading-indicator separately. Use animating property to control.
* doc pr: https://github.com/apache/incubator-weex-site/pull/363
* demo: http://dotwe.org/vue/15b0ac96db6e1837ef5c27c0345b7fb6

[Android] Support to use loading-indicator separately.

---

android/sdk/src/main/java/com/taobao/weex/ui/component/list/BasicListComponent.java

* issue: https://github.com/apache/incubator-weex/issues/2250
The list should not be frozen when the 'keepPositionCell' is null.

[Android] Fix list frozen in wrong condition.

---

android/sdk/build.gradle

copy libweexcore.so and libweexjss.so to libs automatically

copy libweexcore.so and libweexjss.so to libs automatically

---

runtime/bridge/receiver.js

Still throw the caught exception in the "componentHook" anyway, it should be processed by the native for consistent error collecting.

[jsfm] Throw the caught exception in componentHook

---

weex_core/Source/android/multiprocess/weex_js_connection.cpp

Throw exception if create pthread failed

Throw exception if create pthread failed

---

android/build.gradle
android/sdk/build.gradle

Remove armABIOnly flag, which will cause 32 bits so and 64 bits cross link problem.

* [Android] Fix android playground run unexpectedly on arm-v7a platform

---

runtime/vdom/Document.js

Remove the useless temporary variable `result` in the `fireEvent` method.

[jsfm] Fix the lint error in Document

---

weex_core/Source/core/layout/layout.cpp
weex_core/Source/core/layout/layout.h

We fount that, when flex-direction is row-reverse, justify-content:flex-end is not available, not matter justify-content is flex-start or flex-end, layout system always layout items as flex-start.
Demo:
https://jsplayground.taobao.org/raxplayground/a3ad1d37-a6b7-41bb-9b72-3c00ab4ee161

[core] fix flex-end in row-reverse

---

android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
android/sdk/src/main/java/com/taobao/weex/common/WXErrorCode.java

change error report function name to CreatePageWithContent.

[data-render] reportJSException compare funtion name using CreatePageWithContent

---

android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java

Degrade to h5 if can not reload this page

Degrade to h5 if can not reload this page

---

android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
weex_core/Source/core/bridge/platform/core_side_in_platform.cpp

1. Add weex-rax-api.js for all eagle page
2. If it is `eagle` and `Vue`, set the value of `weex-rax-api.js` to `\0`
3. Change the json structure of `weex.config.env`.
* Before
* Normal Page
{
"bundleType": "Vue",
"bundleUrl": "xxxx",
"env": {
"deviceHeight": "1200",
"deviceWidth": "720",
"enableBackupThread": "true",
"enableBackupThreadCache": "true",
.....
},
"render_strategy": "DATA_RENDER"
}
* Eagle Page
As bundleType is `Others`, `env.options` will not be merged into `env`.
{
"bundleType": "Others",
"bundleUrl": "xxxx",
"env": {
"deviceHeight": "1200",
"deviceWidth": "720",
"options": {
"enableBackupThread": "true",
"enableBackupThreadCache": "true",
.....
}
....
},
"render_strategy": "DATA_RENDER"
}
* After
1. No matter what bundleType, always merge `env.options` into `env`
1. For …

[Android] Add weex-rax-api.js for eagle

---

ios/sdk/WeexSDK/Sources/Module/WXTransition.mm

已反馈 Issue #2347 [[iOS] iOS上对视图进行位移等动画处理时，最后位移的结果相比预期值要多或少位移若干像素。](https://github.com/apache/incubator-weex/issues/2347) ，详细问题描述可跳转过去查看。

[BUG] 修正动画处理时逐帧模拟的计算误差及逻辑问题，详见 #2347 。

---

android/sdk/build.gradle

1. The version must have 4 sections like `0.20.0.1`
2. The leading three section must be number, and the last section is odd number with or without suffix string.
3. Version check can be ignored by `-PignoreVersionCheck=true`

[Android] Check weexVersion

---

android/sdk/build.gradle

Use a dedicated way to copy unstripped `.so` file without the importable file path.

[Android] Copy so.

---

android/sdk/build.gradle
scripts/build_from_source.sh
scripts/publish_release_official.sh

* Change default android version to `0.24.0.1`
* Ignore version check of android during Apache Release

Chagne Android Version

---

scripts/publish_release_official.sh

The release script of Weex relies on [release-it](https://github.com/release-it/release-it), which always push all local tags to remote repo. 
I am fixing it by disable the ability of pushing tag in release-it.

Fix the tag pushing problems for apache release script

---

ios/sdk/WeexSDK/Sources/Bridge/WXCoreBridge.mm
weex_core/Source/android/jsengine/wson/wson_jsc.cpp
weex_core/Source/base/android/log_utils.h
weex_core/Source/base/log_defines.cpp
weex_core/Source/base/log_defines.h
weex_core/Source/base/utils/log_utils.cpp
weex_core/Source/base/utils/log_utils.h
weex_core/Source/core/bridge/log_bridge.h
weex_core/Source/third_party/IPC/IPCLog.h

Weex used to mix the following android log together:
* `weex_core/Source/base/android/log_utils.h`
* `weex_core/Source/android/jsengine/wson/wson_jsc.cpp`
* `weex_core/Source/base/utils/log_utils.h`
* `weex_core/Source/third_party/IPC/IPCLog.h`
Now, all android log should redirect to `weex_core/Source/base/log_defines.h`

Redirect all invocation of Android C++ log to log_defines.h

---

weex_core/Source/base/log_defines.h

Log functions fix. Allow LOGI to output in release bundle.

---

android/sdk/src/main/java/com/taobao/weex/WXEnvironment.java
android/sdk/src/main/java/com/taobao/weex/WXSDKEngine.java
android/sdk/src/main/java/com/taobao/weex/ui/module/ConsoleLogModule.java
android/sdk/src/main/java/com/taobao/weex/utils/LogLevel.java
android/sdk/src/main/java/com/taobao/weex/utils/WXLogUtils.java
weex_core/Source/base/log_defines.h

1. Add ConsoleLogModule, developers could change log using javascript. Ref demo http://editor.weex.io/vue/8fb63b977fad1bf816b9a9ad79a43fbd
1. Print log to logcat and devtool only if WXEnviroment.sLogLevel is bigger than the log being printed.
1. Change WXEnviroment.sLogLevel to INFO under debug apk, change it to WARN otherwise. Before this change WXEnvironment.sApplication was always null when initializing WXEnviroment.sLogLevel, so WXEnviroment.sLogLevel was always debug regardless it's actually debuggable or not.
1. Enable LogI no matter it's debuggable or not.
1. Change the value of LogLevel.value, which should have no influence.

[Android] developers could change log level using javascript

---

android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java

Add nav onSupportNavigateUp event

---

android/sdk/src/main/java/com/taobao/weex/utils/WXViewUtils.java

Reverts apache/incubator-weex#2536

Revert "[Android] fix Android9 inaccurate ScreenHeight problem"

---

android/sdk/src/main/java/com/taobao/weex/utils/BoxShadowUtil.java

The implementation of `box-shadow` relies on an Android bug, which has been fixed when target API is bigger than 26.
This PR just disables the ability of `box-shadow` if target API is bigger than 26.
Ref #2279 to see detail

Fix crash issue caused by box-shadow.

---

ios/sdk/WeexSDK/Sources/Component/WXImageComponent.m

Fix image placeholder

---

weex_core/Source/CMakeLists.txt
weex_core/Source/android/jsengine/object/weex_global_object.cpp
weex_core/Source/android/wrap/wx_bridge.cpp
weex_core/Source/base/log_defines.cpp
weex_core/Source/base/log_defines.h
weex_core/Source/base/utils/log_utils.cpp
weex_core/Source/base/utils/log_utils.h
weex_core/Source/core/config/core_environment.cpp

1. Add a variable (DebugMode) in namespace of WeexCore. Sub-process and main-process would WeexCore::DebugMode separately.
2. The default log out is enable only if WeexCore::DebugMode is true.
3. As for LOGD printed before sub-process setting WeexCore::DebugMode, just delete -DDEBUG=1 in CMAKE
This is not a final fix, just a temporary one.

[Android] Disable all log level in release app and enable log level above debug app.

---

android/playground/app/src/main/java/com/alibaba/weex/WXApplication.java
android/playground/app/src/main/java/com/alibaba/weex/extend/adapter/DefaultConfigAdapter.java
android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
android/sdk/src/main/java/com/taobao/weex/WXSDKManager.java
android/sdk/src/main/java/com/taobao/weex/bridge/WXBridge.java
android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
android/sdk/src/main/java/com/taobao/weex/common/WXErrorCode.java
android/sdk/src/main/java/com/taobao/weex/performance/WXStateRecord.java
android/sdk/src/main/java/com/taobao/weex/performance/WhiteScreenUtils.java
android/sdk/src/main/java/com/taobao/weex/ui/action/GraphicActionAddElement.java
android/sdk/src/main/java/com/taobao/weex/utils/WXExceptionUtils.java

white screen check (if didn't render LeafView )
- report view/component tree
- report run state (task、jsc crash、reload)

[Android] add new white screen check logic

---

android/sdk/src/main/java/com/taobao/weex/ui/component/WXText.java

Fix iconFont render error when download from network first time

Fix iconFont render error when download from network first time

---

android/sdk/.gitignore
android/sdk/build.gradle

Enable this feature by `./gradlew assembleRelease -PsupportArmeabi="true"`

[Android] Copy shared library from armeabi-v7a into armeabi

---

weex_core/Source/core/bridge/eagle_bridge.cpp

Make a forceLayout before RefreshFinish in eagle to make sure view & props is stable after onRefreshFinish callback.

[data-render] ForceRefresh before RefreshFinish in eagle

---

android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java

```
java.lang.RuntimeException: android.os.DeadSystemException
at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4103)
at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4069)
at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4043)
at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4017)
at android.app.ActivityThread.-wrap18(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1640)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6646)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:146 …
```

[Android] Fix potential NPE

---

android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java

JSEngine 并行渲染的开关从每次打开页面都检查生效变为应用启动时检查生效

Do not check multi thread flag when create instance

---

android/sdk/src/main/java/com/taobao/weex/ui/component/helper/ScrollStartEndHelper.java

[Android] bugfix of  the scrollstart and scrollend  event mismatching
* [water-fall](https://alibaba.github.io/rax/jsplayground/f0e48f35-b8d0-4365-9a77-561c9b72db24)
* [list-view](https://alibaba.github.io/rax/jsplayground/d05c8037-007f-4c3e-b5a3-4d460b45f3ee)
* [recycler-view](https://alibaba.github.io/rax/jsplayground/2f808e14-3f1a-452f-ac95-1fe7592ac876)

[Android] bugfix of  the scrollstart and scrollend  event mismatching

---

package.json
runtime/shared/polyfill/promise.js

Since the internal Promise API may have unpredictable behavior on some legacy Android devices, so using the js polyfill instead (as iOS does).
Modify the js framework version in package.json, since it has already been updated in #2669

[jsfm] Also enable the promise polyfill on Android

---

ios/sdk/WeexSDK/Sources/Bridge/WXBridgeContext.m
ios/sdk/WeexSDK/Sources/Bridge/WXBridgeMethod.h
ios/sdk/WeexSDK/Sources/Bridge/WXBridgeMethod.m
ios/sdk/WeexSDK/Sources/Bridge/WXJSCoreBridge.mm
ios/sdk/WeexSDK/Sources/Engine/WXSDKEngine.m
ios/sdk/WeexSDK/Sources/Manager/WXBridgeManager.m
ios/sdk/WeexSDK/Sources/Utility/WXUtility.h
ios/sdk/WeexSDK/Sources/Utility/WXUtility.m

Pass immutable arguments to JS to avoid JSC crash.

---

android/sdk/src/main/java/com/taobao/weex/common/WXPerformance.java
android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java

add bigCell detail msg for analyzer on debug performance mode

[Android] add bigCell detail msg for analyzer on debug performance mode

---

weex_core/Source/js_runtime/weex/binding/weex_global_binding.cpp

jsfm on Android
jsfm on Android env
```
microTimerFunc = macroTimerFunc = setTimeout = setTimeoutNative (Android)
```
so  setTimeoutNative args get error cause microTask timing er chaos

[Android] fix timeout args get and fix js microtask Timing

---

android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
android/sdk/src/main/java/com/taobao/weex/bridge/WXBridge.java
android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
android/sdk/src/main/java/com/taobao/weex/common/IWXBridge.java
weex_core/Source/base/android/jniprebuild/jniheader/WXBridge_jni.h

[Demo](http://dotwe.org/vue/db55ace59f716bbe58f89dcfd3bf1fc7)

[Android]fix setViewPort invalid

---

ios/sdk/WeexSDK/Sources/Component/WXTextComponent.mm

If lineHeight property is not nil, adjut position of first line, and confirm other line's lineOrigin  according of first line.

Fix text line-height property error

---

android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java
android/sdk/src/main/java/com/taobao/weex/bridge/WXBridge.java
android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
android/sdk/src/main/java/com/taobao/weex/performance/WXInstanceApm.java
android/sdk/src/main/java/com/taobao/weex/ui/action/GraphicActionAddElement.java
weex_core/Source/android/wrap/wx_bridge.cpp
weex_core/Source/base/android/jniprebuild/jniheader/WXBridge_jni.h
weex_core/Source/core/moniter/render_performance.cpp
weex_core/Source/core/moniter/render_performance.h
weex_core/Source/core/render/page/render_page_base.cpp
weex_core/Source/core/render/page/render_page_base.h

-  build view time
- build component  time
- layout  time
- js execute time (next version)

 [Android] record performance detail cost

---

ios/sdk/WeexSDK/Sources/Module/WXAnimationModule.m

[iOS] Protect animation argument missing which cause crash on iOS.

---

android/sdk/.gitignore
android/sdk/lint.xml
android/sdk/src/main/java/com/taobao/weex/WXEnvironment.java
android/sdk/src/main/java/com/taobao/weex/ui/component/WXScroller.java
android/sdk/src/main/java/com/taobao/weex/ui/view/refresh/circlebar/CircleProgressBar.java

1. Fix permission problem of getSystemService(Context.TELEPHONY_SERVICE))
2. Fix allocate new object problem in CircleProgressBra.onLayout
3. Fix boxing/unboxing problem in WXScroller
4. Add `lint.xml` to git

[Android] Fix problems in Android Lint

---

android/sdk/src/main/java/com/taobao/weex/bridge/RequestHandler.java
android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
weex_core/Source/core/bridge/eagle_bridge.cpp
weex_core/Source/core/network/android/default_request_handler.cc

[Android] Fix Android Crash in `PostTaskToMsgLoop`
As `WeexCoreManager::Instance()->script_thread()` is initialized in `WeexCore::InitFramework`, `EagleBridge::WeexCoreHandler::PostTaskToMsgLoop` will crash if `WeexCore::InitFramework` is not invoked.
Fix this problem by not supporting `EagleBridge::WeexCoreHandler::PostTaskToMsgLoop` anymore.
Stackstrace:
```
libweexcore.so (_ZN8WeexCore11EagleBridge15WeexCoreHandler17PostTaskToMsgLoopERKNSt6__ndk18functionIFvvEEE+13)
```
* Demo:

[Android] Fix Android Crash in PostTaskToMsgLoop

---

weex_core/Source/android/wrap/wx_bridge.cpp

The return value of `jString2StrFast(env, instanceId)` could be `std::string(nullptr)`` if instanceId is `nullptr`, in which case the return value would cause crash.
```
#00 pc 0x4aaec libweexcore.so (_ZNSt6__ndk16__treeINS_12__value_typeINS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEPN8WeexCore14RenderPageBaseEEENS_19__map_value_compareIS7_SB_NS_4lessIS7_EELb1EEENS5_ISB_EEE13__lower_boundIS7_EENS_15__tree_iteratorISB_PNS_11__tree_nodeISB_PvEEiEERKT_SN_PNS_15__tree_end_nodeIPNS_16__tree_node_baseISL_EEEE+23)
#01 pc 0x4aa6b libweexcore.so (_ZNSt6__ndk16__treeINS_12__value_typeINS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEPN8WeexCore14RenderPageBaseEEENS_19__map_value_compareIS7_SB_NS_4lessIS7_EELb1EEENS5_ISB_EEE4findIS7_EENS_15__tree_iteratorISB_PNS_11__tree_nodeISB …
```

[Android] Fix C++ Crash in WeexCore::NotifyLayout

---

ios/sdk/WeexSDK/Sources/Performance/WXApmForInstance.h
ios/sdk/WeexSDK/Sources/WeexSDK.h

Fix nullable annotation.

---

android/sdk/src/main/AndroidManifest.xml
android/sdk/src/main/java/com/taobao/weex/common/WXWorkThreadManager.java
android/sdk/src/main/java/com/taobao/weex/ui/module/WXDomModule.java

Remove duplicate receiver in manifest and remove class definition
* [Manifest demo](http://dotwe.org/vue/3351b6b69cac58d852ce0aef43d8eb85), work as before.
* [globalEvent Documentation](https://weex.apache.org/docs/modules/globalEvent.html#globalevent)
* As there is no `intent-filter` for the receiver in the manifest, the receiver in the manifest is useless. Actually, the receiver is registered in [code](https://github.com/apache/incubator-weex/blob/23821f9f0843a2ef14b6a7b15b0a4b3cda6afedd/android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java#L1316) with an intent.

[Android] Remove duplicate receiver in manifest and remove class definition

---

android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java

Fix the following crash
```
java.lang.IllegalArgumentException: Receiver not registered: com.taobao.weex.WXGlobalEventReceiver@df9ef3f
at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1095)
at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1500)
at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:608)
at com.taobao.weex.WXSDKInstance.destroy(WXSDKInstance.java:1832)
at com.taobao.weex.WXSDKInstance.onActivityDestroy(WXSDKInstance.java:1457)
```
* Demo:

[Android] Fix crash in receiver.

---

android/sdk/src/main/java/com/taobao/weex/dom/WXStyle.java
android/sdk/src/main/java/com/taobao/weex/ui/animation/TransformParser.java

This is a bug in default value introduced by https://github.com/apache/incubator-weex/pull/2783 ,which change some default value from `0` to `Float.NAN` . This commit will revert the behaviour change.
* Demo:

[Android] Change default value to from Float.NAN to 0

---

ios/sdk/WeexSDK/Sources/Manager/WXBridgeManager.m
ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m
ios/sdk/WeexSDK/Sources/Performance/WXApmForInstance.m
weex_core/Source/core/bridge/script_bridge.h
weex_core/Source/core/render/action/render_action_createfinish.cpp
weex_core/Source/core/render/manager/render_manager.cpp

Optimize iOS logs.

---

android/sdk/src/main/java/com/taobao/weex/WXSDKInstance.java

add For Webview get OnActivity Result

add For Webview get OnActivity Result

---

android/sdk/src/main/java/com/taobao/weex/adapter/IWXConfigAdapter.java
android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
weex_core/Source/android/jsengine/bridge/script/script_bridge_in_multi_process.cpp
weex_core/Source/android/jsengine/bridge/script/script_bridge_in_multi_process.h
weex_core/Source/android/jsengine/object/weex_env.h
weex_core/Source/base/crash/crash_handler.cpp
weex_core/Source/base/crash/crash_handler.h

- changlog
- __fix white screen cause deadlock (crash_handler.cpp)__ 
- add switch for open/close fixlogic
handleSignal maybe cause sig delivered deadLock,and maybe block weexCoreThread on ipc，then cause whiteScreen or other issue unless restart app
- bug
- cause 1: [sigaction handler should use async-signal-safe func](http://man7.org/linux/man-pages/man7/signal-safety.7.html#top_of_page)
- cause 2:other logic crash or dl.
- solution: 
- google breakPad dump crash on a new process to avoid bugs.
- tmp solution (we use): setTimeout 1s,force exit on handleExitAlarm(if has deadLock)

[Android] fix white screen cause deadlock

---

android/sdk/src/main/java/com/taobao/weex/WeexFrameRateControl.java
android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java

There is a concurrent read/write operation to `RenderManager::pages_` during `CoreSideInPlatform::NotifyLayout`where MainThread is reading `RenderManager::pages_` while other thread may be writing to it.
```
std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >::__is_long() const at string:1266
(inlined by) std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >::size() const at string:905
(inlined by) std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >::compare(std::__ndk1::basic_string_view<char, std::__ndk1::char_traits<char> >) const at string:3455
(inlined by) std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> …
```

[Android] Fix Crash in NotifyLayout

---

.travis.yml

[Travis] Fail travis if Android build fails

---

android/sdk/src/main/java/com/taobao/weex/WeexFrameRateControl.java
android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java

Revert https://github.com/apache/incubator-weex/pull/2902
* Demo:

[Android] Revert WeexFrame

---

ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.h
ios/sdk/WeexSDK/Sources/Model/WXSDKInstance.m

[iOS] Add last page info.

---

android/sdk/build.gradle
android/sdk/buildSrc/packageName.gradle

JNI string such as `com.taobao.weex` to `org.apache.weex` in cpp/h file during compiling.

* [Android] Change JNI string in cpp/h file

---

android/sdk/src/main/java/com/taobao/weex/bridge/WXBridgeManager.java
android/sdk/src/main/java/com/taobao/weex/common/WXErrorCode.java
weex_core/Source/core/render/page/render_page.cpp

* [Android] Avoid ArrayIndexOutOfBounds in RenderPage::MoveRenderObject

---

ios/sdk/WeexSDK/Sources/Component/WXComponent_internal.h
ios/sdk/WeexSDK/Sources/Display/WXComponent+Display.m
ios/sdk/WeexSDK/Sources/Loader/WXResourceLoader.m
ios/sdk/WeexSDK/Sources/Model/WXComponent.mm
ios/sdk/WeexSDK/Sources/Utility/WXConvert.h
ios/sdk/WeexSDK/Sources/Utility/WXConvert.m
ios/sdk/WeexSDK/Sources/View/WXComponent+ViewManagement.mm

[iOS] Fix problem that _backgroundColor causing multithread crashing.

---

ios/sdk/WeexSDK/Sources/Component/WXTextComponent.mm

Issue: https://github.com/apache/incubator-weex/issues/2935
Playground: http://dotwe.org/vue/7d2bf6e112ea26984fd5930663f092e0
Reference: https://github.com/xiangwangfeng/M80AttributedLabel/pull/44
* Demo:

Fix CTFont changed under xcode11 build.

---

ios/sdk/WeexSDK/Sources/Component/WXComponent_internal.h
ios/sdk/WeexSDK/Sources/Display/WXComponent+Display.m
ios/sdk/WeexSDK/Sources/Model/WXComponent.mm
ios/sdk/WeexSDK/Sources/View/WXComponent+ViewManagement.mm

[iOS Use property to access 'backgroundColor'.

---

android/sdk/build.gradle
android/sdk/buildSrc/asan.gradle
android/sdk/buildSrc/download_jsc.gradle
android/sdk/buildSrc/packageName.gradle

[Android] Fix task order problem.
